pub mod ext;
pub mod xcb;

#[path = "generated/ffi/big_requests.rs"]
pub mod big_requests;
#[path = "generated/ffi/composite.rs"]
pub mod composite;
#[path = "generated/ffi/damage.rs"]
pub mod damage;
#[path = "generated/ffi/dpms.rs"]
pub mod dpms;
#[path = "generated/ffi/dri2.rs"]
pub mod dri2;
#[path = "generated/ffi/dri3.rs"]
pub mod dri3;
#[path = "generated/ffi/genericevent.rs"]
pub mod genericevent;
#[path = "generated/ffi/glx.rs"]
pub mod glx;
#[path = "generated/ffi/present.rs"]
pub mod present;
#[path = "generated/ffi/randr.rs"]
pub mod randr;
#[path = "generated/ffi/record.rs"]
pub mod record;
#[path = "generated/ffi/render.rs"]
pub mod render;
#[path = "generated/ffi/res.rs"]
pub mod res;
#[path = "generated/ffi/screensaver.rs"]
pub mod screensaver;
#[path = "generated/ffi/selinux.rs"]
pub mod selinux;
#[path = "generated/ffi/shape.rs"]
pub mod shape;
#[path = "generated/ffi/shm.rs"]
pub mod shm;
#[path = "generated/ffi/sync.rs"]
pub mod sync;
#[path = "generated/ffi/test.rs"]
pub mod test;
#[path = "generated/ffi/x_print.rs"]
pub mod x_print;
#[path = "generated/ffi/xc_misc.rs"]
pub mod xc_misc;
#[path = "generated/ffi/xevie.rs"]
pub mod xevie;
#[path = "generated/ffi/xf86dri.rs"]
pub mod xf86dri;
#[path = "generated/ffi/xf86vidmode.rs"]
pub mod xf86vidmode;
#[path = "generated/ffi/xfixes.rs"]
pub mod xfixes;
#[path = "generated/ffi/xinerama.rs"]
pub mod xinerama;
#[path = "generated/ffi/xinput.rs"]
pub mod xinput;
#[path = "generated/ffi/xkb.rs"]
pub mod xkb;
#[path = "generated/ffi/xproto.rs"]
pub mod xproto;
#[path = "generated/ffi/xv.rs"]
pub mod xv;
#[path = "generated/ffi/xvmc.rs"]
pub mod xvmc;
