use crate::lazy::*;
use crate::*;
use libloading::{Error, Library};
use std::mem::MaybeUninit;
use std::os::raw::*;
use std::ptr;

#[rustfmt::skip]
pub struct Xcb {
    pub(crate) lib: NamedLibrary,
    pub(crate) xcb_alloc_color: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t, red: u16, green: u16, blue: u16) -> xcb_alloc_color_cookie_t>,
    pub(crate) xcb_alloc_color_cells: LazySymbol<unsafe fn(c: *mut xcb_connection_t, contiguous: u8, cmap: xcb_colormap_t, colors: u16, planes: u16) -> xcb_alloc_color_cells_cookie_t>,
    pub(crate) xcb_alloc_color_cells_masks: LazySymbol<unsafe fn(R: *const xcb_alloc_color_cells_reply_t) -> *mut u32>,
    pub(crate) xcb_alloc_color_cells_masks_end: LazySymbol<unsafe fn(R: *const xcb_alloc_color_cells_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_alloc_color_cells_masks_length: LazySymbol<unsafe fn(R: *const xcb_alloc_color_cells_reply_t) -> c_int>,
    pub(crate) xcb_alloc_color_cells_pixels: LazySymbol<unsafe fn(R: *const xcb_alloc_color_cells_reply_t) -> *mut u32>,
    pub(crate) xcb_alloc_color_cells_pixels_end: LazySymbol<unsafe fn(R: *const xcb_alloc_color_cells_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_alloc_color_cells_pixels_length: LazySymbol<unsafe fn(R: *const xcb_alloc_color_cells_reply_t) -> c_int>,
    pub(crate) xcb_alloc_color_cells_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_alloc_color_cells_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_alloc_color_cells_reply_t>,
    pub(crate) xcb_alloc_color_cells_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, contiguous: u8, cmap: xcb_colormap_t, colors: u16, planes: u16) -> xcb_alloc_color_cells_cookie_t>,
    pub(crate) xcb_alloc_color_planes: LazySymbol<unsafe fn(c: *mut xcb_connection_t, contiguous: u8, cmap: xcb_colormap_t, colors: u16, reds: u16, greens: u16, blues: u16) -> xcb_alloc_color_planes_cookie_t>,
    pub(crate) xcb_alloc_color_planes_pixels: LazySymbol<unsafe fn(R: *const xcb_alloc_color_planes_reply_t) -> *mut u32>,
    pub(crate) xcb_alloc_color_planes_pixels_end: LazySymbol<unsafe fn(R: *const xcb_alloc_color_planes_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_alloc_color_planes_pixels_length: LazySymbol<unsafe fn(R: *const xcb_alloc_color_planes_reply_t) -> c_int>,
    pub(crate) xcb_alloc_color_planes_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_alloc_color_planes_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_alloc_color_planes_reply_t>,
    pub(crate) xcb_alloc_color_planes_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, contiguous: u8, cmap: xcb_colormap_t, colors: u16, reds: u16, greens: u16, blues: u16) -> xcb_alloc_color_planes_cookie_t>,
    pub(crate) xcb_alloc_color_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_alloc_color_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_alloc_color_reply_t>,
    pub(crate) xcb_alloc_color_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t, red: u16, green: u16, blue: u16) -> xcb_alloc_color_cookie_t>,
    pub(crate) xcb_alloc_named_color: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t, name_len: u16, name: *const c_char) -> xcb_alloc_named_color_cookie_t>,
    pub(crate) xcb_alloc_named_color_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_alloc_named_color_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_alloc_named_color_reply_t>,
    pub(crate) xcb_alloc_named_color_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t, name_len: u16, name: *const c_char) -> xcb_alloc_named_color_cookie_t>,
    pub(crate) xcb_allow_events: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_allow_events_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_arc_end: LazySymbol<unsafe fn(i: *mut xcb_arc_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_arc_next: LazySymbol<unsafe fn(i: *mut xcb_arc_iterator_t)>,
    pub(crate) xcb_atom_end: LazySymbol<unsafe fn(i: *mut xcb_atom_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_atom_next: LazySymbol<unsafe fn(i: *mut xcb_atom_iterator_t)>,
    pub(crate) xcb_bell: LazySymbol<unsafe fn(c: *mut xcb_connection_t, percent: i8) -> xcb_void_cookie_t>,
    pub(crate) xcb_bell_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, percent: i8) -> xcb_void_cookie_t>,
    pub(crate) xcb_big_requests_enable: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_big_requests_enable_cookie_t>,
    pub(crate) xcb_big_requests_enable_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_big_requests_enable_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_big_requests_enable_reply_t>,
    pub(crate) xcb_big_requests_enable_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_big_requests_enable_cookie_t>,
    pub(crate) xcb_big_requests_id: LazySymbol<*mut xcb_extension_t>,
    pub(crate) xcb_button_end: LazySymbol<unsafe fn(i: *mut xcb_button_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_button_next: LazySymbol<unsafe fn(i: *mut xcb_button_iterator_t)>,
    pub(crate) xcb_change_active_pointer_grab: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cursor: xcb_cursor_t, time: xcb_timestamp_t, event_mask: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_active_pointer_grab_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cursor: xcb_cursor_t, time: xcb_timestamp_t, event_mask: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_gc: LazySymbol<unsafe fn(c: *mut xcb_connection_t, gc: xcb_gcontext_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_gc_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, gc: xcb_gcontext_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_hosts: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8, family: u8, address_len: u16, address: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_hosts_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8, family: u8, address_len: u16, address: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_keyboard_control: LazySymbol<unsafe fn(c: *mut xcb_connection_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_keyboard_control_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_keyboard_mapping: LazySymbol<unsafe fn(c: *mut xcb_connection_t, keycode_count: u8, first_keycode: xcb_keycode_t, keysyms_per_keycode: u8, keysyms: *const xcb_keysym_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_keyboard_mapping_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, keycode_count: u8, first_keycode: xcb_keycode_t, keysyms_per_keycode: u8, keysyms: *const xcb_keysym_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_pointer_control: LazySymbol<unsafe fn(c: *mut xcb_connection_t, acceleration_numerator: i16, acceleration_denominator: i16, threshold: i16, do_acceleration: u8, do_threshold: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_pointer_control_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, acceleration_numerator: i16, acceleration_denominator: i16, threshold: i16, do_acceleration: u8, do_threshold: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8, window: xcb_window_t, property: xcb_atom_t, type_: xcb_atom_t, format: u8, data_len: u32, data: *const c_void) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_property_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8, window: xcb_window_t, property: xcb_atom_t, type_: xcb_atom_t, format: u8, data_len: u32, data: *const c_void) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_save_set: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_save_set_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_window_attributes: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_change_window_attributes_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_char2b_end: LazySymbol<unsafe fn(i: *mut xcb_char2b_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_char2b_next: LazySymbol<unsafe fn(i: *mut xcb_char2b_iterator_t)>,
    pub(crate) xcb_charinfo_end: LazySymbol<unsafe fn(i: *mut xcb_charinfo_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_charinfo_next: LazySymbol<unsafe fn(i: *mut xcb_charinfo_iterator_t)>,
    pub(crate) xcb_circulate_window: LazySymbol<unsafe fn(c: *mut xcb_connection_t, direction: u8, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_circulate_window_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, direction: u8, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_clear_area: LazySymbol<unsafe fn(c: *mut xcb_connection_t, exposures: u8, window: xcb_window_t, x: i16, y: i16, width: u16, height: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_clear_area_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, exposures: u8, window: xcb_window_t, x: i16, y: i16, width: u16, height: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_client_message_data_end: LazySymbol<unsafe fn(i: *mut xcb_client_message_data_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_client_message_data_next: LazySymbol<unsafe fn(i: *mut xcb_client_message_data_iterator_t)>,
    pub(crate) xcb_close_font: LazySymbol<unsafe fn(c: *mut xcb_connection_t, font: xcb_font_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_close_font_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, font: xcb_font_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_coloritem_end: LazySymbol<unsafe fn(i: *mut xcb_coloritem_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_coloritem_next: LazySymbol<unsafe fn(i: *mut xcb_coloritem_iterator_t)>,
    pub(crate) xcb_colormap_end: LazySymbol<unsafe fn(i: *mut xcb_colormap_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_colormap_next: LazySymbol<unsafe fn(i: *mut xcb_colormap_iterator_t)>,
    pub(crate) xcb_configure_window: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, value_mask: u16, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_configure_window_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, value_mask: u16, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_connect: LazySymbol<unsafe fn(displayname: *const c_char, screenp: *mut c_int) -> *mut xcb_connection_t>,
    pub(crate) xcb_connect_to_display_with_auth_info: LazySymbol<unsafe fn(display: *const c_char, auth: *mut xcb_auth_info_t, screen: *mut c_int) -> *mut xcb_connection_t>,
    pub(crate) xcb_connect_to_fd: LazySymbol<unsafe fn(fd: c_int, auth_info: *mut xcb_auth_info_t) -> *mut xcb_connection_t>,
    pub(crate) xcb_connection_has_error: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> c_int>,
    pub(crate) xcb_convert_selection: LazySymbol<unsafe fn(c: *mut xcb_connection_t, requestor: xcb_window_t, selection: xcb_atom_t, target: xcb_atom_t, property: xcb_atom_t, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_convert_selection_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, requestor: xcb_window_t, selection: xcb_atom_t, target: xcb_atom_t, property: xcb_atom_t, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_copy_area: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src_drawable: xcb_drawable_t, dst_drawable: xcb_drawable_t, gc: xcb_gcontext_t, src_x: i16, src_y: i16, dst_x: i16, dst_y: i16, width: u16, height: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_copy_area_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src_drawable: xcb_drawable_t, dst_drawable: xcb_drawable_t, gc: xcb_gcontext_t, src_x: i16, src_y: i16, dst_x: i16, dst_y: i16, width: u16, height: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_copy_colormap_and_free: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mid: xcb_colormap_t, src_cmap: xcb_colormap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_copy_colormap_and_free_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mid: xcb_colormap_t, src_cmap: xcb_colormap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_copy_gc: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src_gc: xcb_gcontext_t, dst_gc: xcb_gcontext_t, value_mask: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_copy_gc_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src_gc: xcb_gcontext_t, dst_gc: xcb_gcontext_t, value_mask: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_copy_plane: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src_drawable: xcb_drawable_t, dst_drawable: xcb_drawable_t, gc: xcb_gcontext_t, src_x: i16, src_y: i16, dst_x: i16, dst_y: i16, width: u16, height: u16, bit_plane: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_copy_plane_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src_drawable: xcb_drawable_t, dst_drawable: xcb_drawable_t, gc: xcb_gcontext_t, src_x: i16, src_y: i16, dst_x: i16, dst_y: i16, width: u16, height: u16, bit_plane: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_create_colormap: LazySymbol<unsafe fn(c: *mut xcb_connection_t, alloc: u8, mid: xcb_colormap_t, window: xcb_window_t, visual: xcb_visualid_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_create_colormap_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, alloc: u8, mid: xcb_colormap_t, window: xcb_window_t, visual: xcb_visualid_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_create_cursor: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cid: xcb_cursor_t, source: xcb_pixmap_t, mask: xcb_pixmap_t, fore_red: u16, fore_green: u16, fore_blue: u16, back_red: u16, back_green: u16, back_blue: u16, x: u16, y: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_create_cursor_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cid: xcb_cursor_t, source: xcb_pixmap_t, mask: xcb_pixmap_t, fore_red: u16, fore_green: u16, fore_blue: u16, back_red: u16, back_green: u16, back_blue: u16, x: u16, y: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_create_gc: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cid: xcb_gcontext_t, drawable: xcb_drawable_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_create_gc_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cid: xcb_gcontext_t, drawable: xcb_drawable_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_create_glyph_cursor: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cid: xcb_cursor_t, source_font: xcb_font_t, mask_font: xcb_font_t, source_char: u16, mask_char: u16, fore_red: u16, fore_green: u16, fore_blue: u16, back_red: u16, back_green: u16, back_blue: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_create_glyph_cursor_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cid: xcb_cursor_t, source_font: xcb_font_t, mask_font: xcb_font_t, source_char: u16, mask_char: u16, fore_red: u16, fore_green: u16, fore_blue: u16, back_red: u16, back_green: u16, back_blue: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_create_pixmap: LazySymbol<unsafe fn(c: *mut xcb_connection_t, depth: u8, pid: xcb_pixmap_t, drawable: xcb_drawable_t, width: u16, height: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_create_pixmap_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, depth: u8, pid: xcb_pixmap_t, drawable: xcb_drawable_t, width: u16, height: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_create_window: LazySymbol<unsafe fn(c: *mut xcb_connection_t, depth: u8, wid: xcb_window_t, parent: xcb_window_t, x: i16, y: i16, width: u16, height: u16, border_width: u16, class: u16, visual: xcb_visualid_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_create_window_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, depth: u8, wid: xcb_window_t, parent: xcb_window_t, x: i16, y: i16, width: u16, height: u16, border_width: u16, class: u16, visual: xcb_visualid_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_cursor_end: LazySymbol<unsafe fn(i: *mut xcb_cursor_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_cursor_next: LazySymbol<unsafe fn(i: *mut xcb_cursor_iterator_t)>,
    pub(crate) xcb_delete_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, property: xcb_atom_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_delete_property_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, property: xcb_atom_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_depth_end: LazySymbol<unsafe fn(i: *mut xcb_depth_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_depth_next: LazySymbol<unsafe fn(i: *mut xcb_depth_iterator_t)>,
    pub(crate) xcb_depth_visuals: LazySymbol<unsafe fn(R: *const xcb_depth_t) -> *mut xcb_visualtype_t>,
    pub(crate) xcb_depth_visuals_iterator: LazySymbol<unsafe fn(R: *const xcb_depth_t) -> xcb_visualtype_iterator_t>,
    pub(crate) xcb_depth_visuals_length: LazySymbol<unsafe fn(R: *const xcb_depth_t) -> c_int>,
    pub(crate) xcb_destroy_subwindows: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_destroy_subwindows_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_destroy_window: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_destroy_window_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_discard_reply64: LazySymbol<unsafe fn(c: *mut xcb_connection_t, sequence: u64)>,
    pub(crate) xcb_discard_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, sequence: c_uint)>,
    pub(crate) xcb_disconnect: LazySymbol<unsafe fn(c: *mut xcb_connection_t)>,
    pub(crate) xcb_drawable_end: LazySymbol<unsafe fn(i: *mut xcb_drawable_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_drawable_next: LazySymbol<unsafe fn(i: *mut xcb_drawable_iterator_t)>,
    pub(crate) xcb_fill_poly: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, shape: u8, coordinate_mode: u8, points_len: u32, points: *const xcb_point_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_fill_poly_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, shape: u8, coordinate_mode: u8, points_len: u32, points: *const xcb_point_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_flush: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> c_int>,
    pub(crate) xcb_font_end: LazySymbol<unsafe fn(i: *mut xcb_font_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_font_next: LazySymbol<unsafe fn(i: *mut xcb_font_iterator_t)>,
    pub(crate) xcb_fontable_end: LazySymbol<unsafe fn(i: *mut xcb_fontable_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_fontable_next: LazySymbol<unsafe fn(i: *mut xcb_fontable_iterator_t)>,
    pub(crate) xcb_fontprop_end: LazySymbol<unsafe fn(i: *mut xcb_fontprop_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_fontprop_next: LazySymbol<unsafe fn(i: *mut xcb_fontprop_iterator_t)>,
    pub(crate) xcb_force_screen_saver: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_force_screen_saver_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_format_end: LazySymbol<unsafe fn(i: *mut xcb_format_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_format_next: LazySymbol<unsafe fn(i: *mut xcb_format_iterator_t)>,
    pub(crate) xcb_free_colormap: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_free_colormap_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_free_colors: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t, plane_mask: u32, pixels_len: u32, pixels: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_free_colors_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t, plane_mask: u32, pixels_len: u32, pixels: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_free_cursor: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cursor: xcb_cursor_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_free_cursor_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cursor: xcb_cursor_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_free_gc: LazySymbol<unsafe fn(c: *mut xcb_connection_t, gc: xcb_gcontext_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_free_gc_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, gc: xcb_gcontext_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_free_pixmap: LazySymbol<unsafe fn(c: *mut xcb_connection_t, pixmap: xcb_pixmap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_free_pixmap_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, pixmap: xcb_pixmap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_gcontext_end: LazySymbol<unsafe fn(i: *mut xcb_gcontext_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_gcontext_next: LazySymbol<unsafe fn(i: *mut xcb_gcontext_iterator_t)>,
    pub(crate) xcb_generate_id: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> u32>,
    pub(crate) xcb_get_atom_name: LazySymbol<unsafe fn(c: *mut xcb_connection_t, atom: xcb_atom_t) -> xcb_get_atom_name_cookie_t>,
    pub(crate) xcb_get_atom_name_name: LazySymbol<unsafe fn(R: *const xcb_get_atom_name_reply_t) -> *mut c_char>,
    pub(crate) xcb_get_atom_name_name_end: LazySymbol<unsafe fn(R: *const xcb_get_atom_name_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_get_atom_name_name_length: LazySymbol<unsafe fn(R: *const xcb_get_atom_name_reply_t) -> c_int>,
    pub(crate) xcb_get_atom_name_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_atom_name_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_atom_name_reply_t>,
    pub(crate) xcb_get_atom_name_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, atom: xcb_atom_t) -> xcb_get_atom_name_cookie_t>,
    pub(crate) xcb_get_extension_data: LazySymbol<unsafe fn(c: *mut xcb_connection_t, ext: *mut xcb_extension_t) -> *const xcb_query_extension_reply_t>,
    pub(crate) xcb_get_file_descriptor: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> c_int>,
    pub(crate) xcb_get_font_path: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_font_path_cookie_t>,
    pub(crate) xcb_get_font_path_path_iterator: LazySymbol<unsafe fn(R: *const xcb_get_font_path_reply_t) -> xcb_str_iterator_t>,
    pub(crate) xcb_get_font_path_path_length: LazySymbol<unsafe fn(R: *const xcb_get_font_path_reply_t) -> c_int>,
    pub(crate) xcb_get_font_path_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_font_path_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_font_path_reply_t>,
    pub(crate) xcb_get_font_path_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_font_path_cookie_t>,
    pub(crate) xcb_get_geometry: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t) -> xcb_get_geometry_cookie_t>,
    pub(crate) xcb_get_geometry_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_geometry_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_geometry_reply_t>,
    pub(crate) xcb_get_geometry_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t) -> xcb_get_geometry_cookie_t>,
    pub(crate) xcb_get_image: LazySymbol<unsafe fn(c: *mut xcb_connection_t, format: u8, drawable: xcb_drawable_t, x: i16, y: i16, width: u16, height: u16, plane_mask: u32) -> xcb_get_image_cookie_t>,
    pub(crate) xcb_get_image_data: LazySymbol<unsafe fn(R: *const xcb_get_image_reply_t) -> *mut u8>,
    pub(crate) xcb_get_image_data_end: LazySymbol<unsafe fn(R: *const xcb_get_image_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_get_image_data_length: LazySymbol<unsafe fn(R: *const xcb_get_image_reply_t) -> c_int>,
    pub(crate) xcb_get_image_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_image_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_image_reply_t>,
    pub(crate) xcb_get_image_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, format: u8, drawable: xcb_drawable_t, x: i16, y: i16, width: u16, height: u16, plane_mask: u32) -> xcb_get_image_cookie_t>,
    pub(crate) xcb_get_input_focus: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_input_focus_cookie_t>,
    pub(crate) xcb_get_input_focus_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_input_focus_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_input_focus_reply_t>,
    pub(crate) xcb_get_input_focus_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_input_focus_cookie_t>,
    pub(crate) xcb_get_keyboard_control: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_keyboard_control_cookie_t>,
    pub(crate) xcb_get_keyboard_control_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_keyboard_control_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_keyboard_control_reply_t>,
    pub(crate) xcb_get_keyboard_control_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_keyboard_control_cookie_t>,
    pub(crate) xcb_get_keyboard_mapping: LazySymbol<unsafe fn(c: *mut xcb_connection_t, first_keycode: xcb_keycode_t, count: u8) -> xcb_get_keyboard_mapping_cookie_t>,
    pub(crate) xcb_get_keyboard_mapping_keysyms: LazySymbol<unsafe fn(R: *const xcb_get_keyboard_mapping_reply_t) -> *mut xcb_keysym_t>,
    pub(crate) xcb_get_keyboard_mapping_keysyms_end: LazySymbol<unsafe fn(R: *const xcb_get_keyboard_mapping_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_get_keyboard_mapping_keysyms_length: LazySymbol<unsafe fn(R: *const xcb_get_keyboard_mapping_reply_t) -> c_int>,
    pub(crate) xcb_get_keyboard_mapping_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_keyboard_mapping_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_keyboard_mapping_reply_t>,
    pub(crate) xcb_get_keyboard_mapping_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, first_keycode: xcb_keycode_t, count: u8) -> xcb_get_keyboard_mapping_cookie_t>,
    pub(crate) xcb_get_maximum_request_length: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> u32>,
    pub(crate) xcb_get_modifier_mapping: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_modifier_mapping_cookie_t>,
    pub(crate) xcb_get_modifier_mapping_keycodes: LazySymbol<unsafe fn(R: *const xcb_get_modifier_mapping_reply_t) -> *mut xcb_keycode_t>,
    pub(crate) xcb_get_modifier_mapping_keycodes_end: LazySymbol<unsafe fn(R: *const xcb_get_modifier_mapping_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_get_modifier_mapping_keycodes_length: LazySymbol<unsafe fn(R: *const xcb_get_modifier_mapping_reply_t) -> c_int>,
    pub(crate) xcb_get_modifier_mapping_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_modifier_mapping_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_modifier_mapping_reply_t>,
    pub(crate) xcb_get_modifier_mapping_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_modifier_mapping_cookie_t>,
    pub(crate) xcb_get_motion_events: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, start: xcb_timestamp_t, stop: xcb_timestamp_t) -> xcb_get_motion_events_cookie_t>,
    pub(crate) xcb_get_motion_events_events: LazySymbol<unsafe fn(R: *const xcb_get_motion_events_reply_t) -> *mut xcb_timecoord_t>,
    pub(crate) xcb_get_motion_events_events_iterator: LazySymbol<unsafe fn(R: *const xcb_get_motion_events_reply_t) -> xcb_timecoord_iterator_t>,
    pub(crate) xcb_get_motion_events_events_length: LazySymbol<unsafe fn(R: *const xcb_get_motion_events_reply_t) -> c_int>,
    pub(crate) xcb_get_motion_events_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_motion_events_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_motion_events_reply_t>,
    pub(crate) xcb_get_motion_events_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, start: xcb_timestamp_t, stop: xcb_timestamp_t) -> xcb_get_motion_events_cookie_t>,
    pub(crate) xcb_get_pointer_control: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_pointer_control_cookie_t>,
    pub(crate) xcb_get_pointer_control_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_pointer_control_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_pointer_control_reply_t>,
    pub(crate) xcb_get_pointer_control_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_pointer_control_cookie_t>,
    pub(crate) xcb_get_pointer_mapping: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_pointer_mapping_cookie_t>,
    pub(crate) xcb_get_pointer_mapping_map: LazySymbol<unsafe fn(R: *const xcb_get_pointer_mapping_reply_t) -> *mut u8>,
    pub(crate) xcb_get_pointer_mapping_map_end: LazySymbol<unsafe fn(R: *const xcb_get_pointer_mapping_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_get_pointer_mapping_map_length: LazySymbol<unsafe fn(R: *const xcb_get_pointer_mapping_reply_t) -> c_int>,
    pub(crate) xcb_get_pointer_mapping_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_pointer_mapping_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_pointer_mapping_reply_t>,
    pub(crate) xcb_get_pointer_mapping_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_pointer_mapping_cookie_t>,
    pub(crate) xcb_get_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, delete: u8, window: xcb_window_t, property: xcb_atom_t, type_: xcb_atom_t, long_offset: u32, long_length: u32) -> xcb_get_property_cookie_t>,
    pub(crate) xcb_get_property_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_property_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_property_reply_t>,
    pub(crate) xcb_get_property_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, delete: u8, window: xcb_window_t, property: xcb_atom_t, type_: xcb_atom_t, long_offset: u32, long_length: u32) -> xcb_get_property_cookie_t>,
    pub(crate) xcb_get_property_value: LazySymbol<unsafe fn(R: *const xcb_get_property_reply_t) -> *mut c_void>,
    pub(crate) xcb_get_property_value_end: LazySymbol<unsafe fn(R: *const xcb_get_property_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_get_property_value_length: LazySymbol<unsafe fn(R: *const xcb_get_property_reply_t) -> c_int>,
    pub(crate) xcb_get_screen_saver: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_screen_saver_cookie_t>,
    pub(crate) xcb_get_screen_saver_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_screen_saver_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_screen_saver_reply_t>,
    pub(crate) xcb_get_screen_saver_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_get_screen_saver_cookie_t>,
    pub(crate) xcb_get_selection_owner: LazySymbol<unsafe fn(c: *mut xcb_connection_t, selection: xcb_atom_t) -> xcb_get_selection_owner_cookie_t>,
    pub(crate) xcb_get_selection_owner_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_selection_owner_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_selection_owner_reply_t>,
    pub(crate) xcb_get_selection_owner_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, selection: xcb_atom_t) -> xcb_get_selection_owner_cookie_t>,
    pub(crate) xcb_get_setup: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> *const xcb_setup_t>,
    pub(crate) xcb_get_window_attributes: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_get_window_attributes_cookie_t>,
    pub(crate) xcb_get_window_attributes_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_get_window_attributes_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_get_window_attributes_reply_t>,
    pub(crate) xcb_get_window_attributes_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_get_window_attributes_cookie_t>,
    pub(crate) xcb_grab_button: LazySymbol<unsafe fn(c: *mut xcb_connection_t, owner_events: u8, grab_window: xcb_window_t, event_mask: u16, pointer_mode: u8, keyboard_mode: u8, confine_to: xcb_window_t, cursor: xcb_cursor_t, button: u8, modifiers: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_grab_button_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, owner_events: u8, grab_window: xcb_window_t, event_mask: u16, pointer_mode: u8, keyboard_mode: u8, confine_to: xcb_window_t, cursor: xcb_cursor_t, button: u8, modifiers: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_grab_key: LazySymbol<unsafe fn(c: *mut xcb_connection_t, owner_events: u8, grab_window: xcb_window_t, modifiers: u16, key: xcb_keycode_t, pointer_mode: u8, keyboard_mode: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_grab_key_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, owner_events: u8, grab_window: xcb_window_t, modifiers: u16, key: xcb_keycode_t, pointer_mode: u8, keyboard_mode: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_grab_keyboard: LazySymbol<unsafe fn(c: *mut xcb_connection_t, owner_events: u8, grab_window: xcb_window_t, time: xcb_timestamp_t, pointer_mode: u8, keyboard_mode: u8) -> xcb_grab_keyboard_cookie_t>,
    pub(crate) xcb_grab_keyboard_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_grab_keyboard_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_grab_keyboard_reply_t>,
    pub(crate) xcb_grab_keyboard_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, owner_events: u8, grab_window: xcb_window_t, time: xcb_timestamp_t, pointer_mode: u8, keyboard_mode: u8) -> xcb_grab_keyboard_cookie_t>,
    pub(crate) xcb_grab_pointer: LazySymbol<unsafe fn(c: *mut xcb_connection_t, owner_events: u8, grab_window: xcb_window_t, event_mask: u16, pointer_mode: u8, keyboard_mode: u8, confine_to: xcb_window_t, cursor: xcb_cursor_t, time: xcb_timestamp_t) -> xcb_grab_pointer_cookie_t>,
    pub(crate) xcb_grab_pointer_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_grab_pointer_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_grab_pointer_reply_t>,
    pub(crate) xcb_grab_pointer_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, owner_events: u8, grab_window: xcb_window_t, event_mask: u16, pointer_mode: u8, keyboard_mode: u8, confine_to: xcb_window_t, cursor: xcb_cursor_t, time: xcb_timestamp_t) -> xcb_grab_pointer_cookie_t>,
    pub(crate) xcb_grab_server: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_grab_server_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_host_address: LazySymbol<unsafe fn(R: *const xcb_host_t) -> *mut u8>,
    pub(crate) xcb_host_address_end: LazySymbol<unsafe fn(R: *const xcb_host_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_host_address_length: LazySymbol<unsafe fn(R: *const xcb_host_t) -> c_int>,
    pub(crate) xcb_host_end: LazySymbol<unsafe fn(i: *mut xcb_host_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_host_next: LazySymbol<unsafe fn(i: *mut xcb_host_iterator_t)>,
    pub(crate) xcb_image_text_16: LazySymbol<unsafe fn(c: *mut xcb_connection_t, string_len: u8, drawable: xcb_drawable_t, gc: xcb_gcontext_t, x: i16, y: i16, string: *const xcb_char2b_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_image_text_16_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, string_len: u8, drawable: xcb_drawable_t, gc: xcb_gcontext_t, x: i16, y: i16, string: *const xcb_char2b_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_image_text_8: LazySymbol<unsafe fn(c: *mut xcb_connection_t, string_len: u8, drawable: xcb_drawable_t, gc: xcb_gcontext_t, x: i16, y: i16, string: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_image_text_8_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, string_len: u8, drawable: xcb_drawable_t, gc: xcb_gcontext_t, x: i16, y: i16, string: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_install_colormap: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_install_colormap_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_intern_atom: LazySymbol<unsafe fn(c: *mut xcb_connection_t, only_if_exists: u8, name_len: u16, name: *const c_char) -> xcb_intern_atom_cookie_t>,
    pub(crate) xcb_intern_atom_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_intern_atom_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_intern_atom_reply_t>,
    pub(crate) xcb_intern_atom_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, only_if_exists: u8, name_len: u16, name: *const c_char) -> xcb_intern_atom_cookie_t>,
    pub(crate) xcb_keycode_end: LazySymbol<unsafe fn(i: *mut xcb_keycode_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_keycode_next: LazySymbol<unsafe fn(i: *mut xcb_keycode_iterator_t)>,
    pub(crate) xcb_keysym_end: LazySymbol<unsafe fn(i: *mut xcb_keysym_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_keysym_next: LazySymbol<unsafe fn(i: *mut xcb_keysym_iterator_t)>,
    pub(crate) xcb_kill_client: LazySymbol<unsafe fn(c: *mut xcb_connection_t, resource: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_kill_client_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, resource: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_list_extensions: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_list_extensions_cookie_t>,
    pub(crate) xcb_list_extensions_names_iterator: LazySymbol<unsafe fn(R: *const xcb_list_extensions_reply_t) -> xcb_str_iterator_t>,
    pub(crate) xcb_list_extensions_names_length: LazySymbol<unsafe fn(R: *const xcb_list_extensions_reply_t) -> c_int>,
    pub(crate) xcb_list_extensions_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_list_extensions_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_list_extensions_reply_t>,
    pub(crate) xcb_list_extensions_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_list_extensions_cookie_t>,
    pub(crate) xcb_list_fonts: LazySymbol<unsafe fn(c: *mut xcb_connection_t, max_names: u16, pattern_len: u16, pattern: *const c_char) -> xcb_list_fonts_cookie_t>,
    pub(crate) xcb_list_fonts_names_iterator: LazySymbol<unsafe fn(R: *const xcb_list_fonts_reply_t) -> xcb_str_iterator_t>,
    pub(crate) xcb_list_fonts_names_length: LazySymbol<unsafe fn(R: *const xcb_list_fonts_reply_t) -> c_int>,
    pub(crate) xcb_list_fonts_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_list_fonts_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_list_fonts_reply_t>,
    pub(crate) xcb_list_fonts_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, max_names: u16, pattern_len: u16, pattern: *const c_char) -> xcb_list_fonts_cookie_t>,
    pub(crate) xcb_list_fonts_with_info: LazySymbol<unsafe fn(c: *mut xcb_connection_t, max_names: u16, pattern_len: u16, pattern: *const c_char) -> xcb_list_fonts_with_info_cookie_t>,
    pub(crate) xcb_list_fonts_with_info_name: LazySymbol<unsafe fn(R: *const xcb_list_fonts_with_info_reply_t) -> *mut c_char>,
    pub(crate) xcb_list_fonts_with_info_name_end: LazySymbol<unsafe fn(R: *const xcb_list_fonts_with_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_list_fonts_with_info_name_length: LazySymbol<unsafe fn(R: *const xcb_list_fonts_with_info_reply_t) -> c_int>,
    pub(crate) xcb_list_fonts_with_info_properties: LazySymbol<unsafe fn(R: *const xcb_list_fonts_with_info_reply_t) -> *mut xcb_fontprop_t>,
    pub(crate) xcb_list_fonts_with_info_properties_iterator: LazySymbol<unsafe fn(R: *const xcb_list_fonts_with_info_reply_t) -> xcb_fontprop_iterator_t>,
    pub(crate) xcb_list_fonts_with_info_properties_length: LazySymbol<unsafe fn(R: *const xcb_list_fonts_with_info_reply_t) -> c_int>,
    pub(crate) xcb_list_fonts_with_info_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_list_fonts_with_info_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_list_fonts_with_info_reply_t>,
    pub(crate) xcb_list_fonts_with_info_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, max_names: u16, pattern_len: u16, pattern: *const c_char) -> xcb_list_fonts_with_info_cookie_t>,
    pub(crate) xcb_list_hosts: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_list_hosts_cookie_t>,
    pub(crate) xcb_list_hosts_hosts_iterator: LazySymbol<unsafe fn(R: *const xcb_list_hosts_reply_t) -> xcb_host_iterator_t>,
    pub(crate) xcb_list_hosts_hosts_length: LazySymbol<unsafe fn(R: *const xcb_list_hosts_reply_t) -> c_int>,
    pub(crate) xcb_list_hosts_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_list_hosts_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_list_hosts_reply_t>,
    pub(crate) xcb_list_hosts_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_list_hosts_cookie_t>,
    pub(crate) xcb_list_installed_colormaps: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_list_installed_colormaps_cookie_t>,
    pub(crate) xcb_list_installed_colormaps_cmaps: LazySymbol<unsafe fn(R: *const xcb_list_installed_colormaps_reply_t) -> *mut xcb_colormap_t>,
    pub(crate) xcb_list_installed_colormaps_cmaps_end: LazySymbol<unsafe fn(R: *const xcb_list_installed_colormaps_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_list_installed_colormaps_cmaps_length: LazySymbol<unsafe fn(R: *const xcb_list_installed_colormaps_reply_t) -> c_int>,
    pub(crate) xcb_list_installed_colormaps_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_list_installed_colormaps_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_list_installed_colormaps_reply_t>,
    pub(crate) xcb_list_installed_colormaps_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_list_installed_colormaps_cookie_t>,
    pub(crate) xcb_list_properties: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_list_properties_cookie_t>,
    pub(crate) xcb_list_properties_atoms: LazySymbol<unsafe fn(R: *const xcb_list_properties_reply_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_list_properties_atoms_end: LazySymbol<unsafe fn(R: *const xcb_list_properties_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_list_properties_atoms_length: LazySymbol<unsafe fn(R: *const xcb_list_properties_reply_t) -> c_int>,
    pub(crate) xcb_list_properties_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_list_properties_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_list_properties_reply_t>,
    pub(crate) xcb_list_properties_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_list_properties_cookie_t>,
    pub(crate) xcb_lookup_color: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t, name_len: u16, name: *const c_char) -> xcb_lookup_color_cookie_t>,
    pub(crate) xcb_lookup_color_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_lookup_color_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_lookup_color_reply_t>,
    pub(crate) xcb_lookup_color_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t, name_len: u16, name: *const c_char) -> xcb_lookup_color_cookie_t>,
    pub(crate) xcb_map_subwindows: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_map_subwindows_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_map_window: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_map_window_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_no_operation: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_no_operation_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_open_font: LazySymbol<unsafe fn(c: *mut xcb_connection_t, fid: xcb_font_t, name_len: u16, name: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_open_font_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, fid: xcb_font_t, name_len: u16, name: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_parse_display: LazySymbol<unsafe fn(name: *const c_char, host: *mut *mut c_char, display: *mut c_int, screen: *mut c_int) -> c_int>,
    pub(crate) xcb_pixmap_end: LazySymbol<unsafe fn(i: *mut xcb_pixmap_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_pixmap_next: LazySymbol<unsafe fn(i: *mut xcb_pixmap_iterator_t)>,
    pub(crate) xcb_point_end: LazySymbol<unsafe fn(i: *mut xcb_point_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_point_next: LazySymbol<unsafe fn(i: *mut xcb_point_iterator_t)>,
    pub(crate) xcb_poll_for_event: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> *mut xcb_generic_event_t>,
    pub(crate) xcb_poll_for_queued_event: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> *mut xcb_generic_event_t>,
    pub(crate) xcb_poll_for_special_event: LazySymbol<unsafe fn(c: *mut xcb_connection_t, se: *mut xcb_special_event_t) -> *mut xcb_generic_event_t>,
    pub(crate) xcb_poly_arc: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, arcs_len: u32, arcs: *const xcb_arc_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_arc_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, arcs_len: u32, arcs: *const xcb_arc_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_fill_arc: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, arcs_len: u32, arcs: *const xcb_arc_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_fill_arc_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, arcs_len: u32, arcs: *const xcb_arc_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_fill_rectangle: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, rectangles_len: u32, rectangles: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_fill_rectangle_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, rectangles_len: u32, rectangles: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_line: LazySymbol<unsafe fn(c: *mut xcb_connection_t, coordinate_mode: u8, drawable: xcb_drawable_t, gc: xcb_gcontext_t, points_len: u32, points: *const xcb_point_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_line_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, coordinate_mode: u8, drawable: xcb_drawable_t, gc: xcb_gcontext_t, points_len: u32, points: *const xcb_point_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_point: LazySymbol<unsafe fn(c: *mut xcb_connection_t, coordinate_mode: u8, drawable: xcb_drawable_t, gc: xcb_gcontext_t, points_len: u32, points: *const xcb_point_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_point_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, coordinate_mode: u8, drawable: xcb_drawable_t, gc: xcb_gcontext_t, points_len: u32, points: *const xcb_point_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_rectangle: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, rectangles_len: u32, rectangles: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_rectangle_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, rectangles_len: u32, rectangles: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_segment: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, segments_len: u32, segments: *const xcb_segment_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_segment_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, segments_len: u32, segments: *const xcb_segment_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_text_16: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, x: i16, y: i16, items_len: u32, items: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_text_16_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, x: i16, y: i16, items_len: u32, items: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_text_8: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, x: i16, y: i16, items_len: u32, items: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_poly_text_8_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, x: i16, y: i16, items_len: u32, items: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_prefetch_extension_data: LazySymbol<unsafe fn(c: *mut xcb_connection_t, ext: *mut xcb_extension_t)>,
    pub(crate) xcb_prefetch_maximum_request_length: LazySymbol<unsafe fn(c: *mut xcb_connection_t)>,
    pub(crate) xcb_put_image: LazySymbol<unsafe fn(c: *mut xcb_connection_t, format: u8, drawable: xcb_drawable_t, gc: xcb_gcontext_t, width: u16, height: u16, dst_x: i16, dst_y: i16, left_pad: u8, depth: u8, data_len: u32, data: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_put_image_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, format: u8, drawable: xcb_drawable_t, gc: xcb_gcontext_t, width: u16, height: u16, dst_x: i16, dst_y: i16, left_pad: u8, depth: u8, data_len: u32, data: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_query_best_size: LazySymbol<unsafe fn(c: *mut xcb_connection_t, class: u8, drawable: xcb_drawable_t, width: u16, height: u16) -> xcb_query_best_size_cookie_t>,
    pub(crate) xcb_query_best_size_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_query_best_size_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_query_best_size_reply_t>,
    pub(crate) xcb_query_best_size_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, class: u8, drawable: xcb_drawable_t, width: u16, height: u16) -> xcb_query_best_size_cookie_t>,
    pub(crate) xcb_query_colors: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t, pixels_len: u32, pixels: *const u32) -> xcb_query_colors_cookie_t>,
    pub(crate) xcb_query_colors_colors: LazySymbol<unsafe fn(R: *const xcb_query_colors_reply_t) -> *mut xcb_rgb_t>,
    pub(crate) xcb_query_colors_colors_iterator: LazySymbol<unsafe fn(R: *const xcb_query_colors_reply_t) -> xcb_rgb_iterator_t>,
    pub(crate) xcb_query_colors_colors_length: LazySymbol<unsafe fn(R: *const xcb_query_colors_reply_t) -> c_int>,
    pub(crate) xcb_query_colors_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_query_colors_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_query_colors_reply_t>,
    pub(crate) xcb_query_colors_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t, pixels_len: u32, pixels: *const u32) -> xcb_query_colors_cookie_t>,
    pub(crate) xcb_query_extension: LazySymbol<unsafe fn(c: *mut xcb_connection_t, name_len: u16, name: *const c_char) -> xcb_query_extension_cookie_t>,
    pub(crate) xcb_query_extension_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_query_extension_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_query_extension_reply_t>,
    pub(crate) xcb_query_extension_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, name_len: u16, name: *const c_char) -> xcb_query_extension_cookie_t>,
    pub(crate) xcb_query_font: LazySymbol<unsafe fn(c: *mut xcb_connection_t, font: xcb_fontable_t) -> xcb_query_font_cookie_t>,
    pub(crate) xcb_query_font_char_infos: LazySymbol<unsafe fn(R: *const xcb_query_font_reply_t) -> *mut xcb_charinfo_t>,
    pub(crate) xcb_query_font_char_infos_iterator: LazySymbol<unsafe fn(R: *const xcb_query_font_reply_t) -> xcb_charinfo_iterator_t>,
    pub(crate) xcb_query_font_char_infos_length: LazySymbol<unsafe fn(R: *const xcb_query_font_reply_t) -> c_int>,
    pub(crate) xcb_query_font_properties: LazySymbol<unsafe fn(R: *const xcb_query_font_reply_t) -> *mut xcb_fontprop_t>,
    pub(crate) xcb_query_font_properties_iterator: LazySymbol<unsafe fn(R: *const xcb_query_font_reply_t) -> xcb_fontprop_iterator_t>,
    pub(crate) xcb_query_font_properties_length: LazySymbol<unsafe fn(R: *const xcb_query_font_reply_t) -> c_int>,
    pub(crate) xcb_query_font_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_query_font_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_query_font_reply_t>,
    pub(crate) xcb_query_font_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, font: xcb_fontable_t) -> xcb_query_font_cookie_t>,
    pub(crate) xcb_query_keymap: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_query_keymap_cookie_t>,
    pub(crate) xcb_query_keymap_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_query_keymap_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_query_keymap_reply_t>,
    pub(crate) xcb_query_keymap_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_query_keymap_cookie_t>,
    pub(crate) xcb_query_pointer: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_query_pointer_cookie_t>,
    pub(crate) xcb_query_pointer_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_query_pointer_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_query_pointer_reply_t>,
    pub(crate) xcb_query_pointer_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_query_pointer_cookie_t>,
    pub(crate) xcb_query_text_extents: LazySymbol<unsafe fn(c: *mut xcb_connection_t, font: xcb_fontable_t, string_len: u32, string: *const xcb_char2b_t) -> xcb_query_text_extents_cookie_t>,
    pub(crate) xcb_query_text_extents_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_query_text_extents_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_query_text_extents_reply_t>,
    pub(crate) xcb_query_text_extents_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, font: xcb_fontable_t, string_len: u32, string: *const xcb_char2b_t) -> xcb_query_text_extents_cookie_t>,
    pub(crate) xcb_query_tree: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_query_tree_cookie_t>,
    pub(crate) xcb_query_tree_children: LazySymbol<unsafe fn(R: *const xcb_query_tree_reply_t) -> *mut xcb_window_t>,
    pub(crate) xcb_query_tree_children_end: LazySymbol<unsafe fn(R: *const xcb_query_tree_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_query_tree_children_length: LazySymbol<unsafe fn(R: *const xcb_query_tree_reply_t) -> c_int>,
    pub(crate) xcb_query_tree_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_query_tree_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_query_tree_reply_t>,
    pub(crate) xcb_query_tree_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_query_tree_cookie_t>,
    pub(crate) xcb_recolor_cursor: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cursor: xcb_cursor_t, fore_red: u16, fore_green: u16, fore_blue: u16, back_red: u16, back_green: u16, back_blue: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_recolor_cursor_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cursor: xcb_cursor_t, fore_red: u16, fore_green: u16, fore_blue: u16, back_red: u16, back_green: u16, back_blue: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_rectangle_end: LazySymbol<unsafe fn(i: *mut xcb_rectangle_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_rectangle_next: LazySymbol<unsafe fn(i: *mut xcb_rectangle_iterator_t)>,
    pub(crate) xcb_register_for_special_xge: LazySymbol<unsafe fn(c: *mut xcb_connection_t, ext: *mut xcb_extension_t, eid: u32, stamp: *mut u32) -> *mut xcb_special_event_t>,
    pub(crate) xcb_reparent_window: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, parent: xcb_window_t, x: i16, y: i16) -> xcb_void_cookie_t>,
    pub(crate) xcb_reparent_window_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, parent: xcb_window_t, x: i16, y: i16) -> xcb_void_cookie_t>,
    pub(crate) xcb_request_check: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_void_cookie_t) -> *mut xcb_generic_error_t>,
    pub(crate) xcb_rgb_end: LazySymbol<unsafe fn(i: *mut xcb_rgb_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_rgb_next: LazySymbol<unsafe fn(i: *mut xcb_rgb_iterator_t)>,
    pub(crate) xcb_rotate_properties: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, atoms_len: u16, delta: i16, atoms: *const xcb_atom_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_rotate_properties_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, atoms_len: u16, delta: i16, atoms: *const xcb_atom_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_screen_allowed_depths_iterator: LazySymbol<unsafe fn(R: *const xcb_screen_t) -> xcb_depth_iterator_t>,
    pub(crate) xcb_screen_allowed_depths_length: LazySymbol<unsafe fn(R: *const xcb_screen_t) -> c_int>,
    pub(crate) xcb_screen_end: LazySymbol<unsafe fn(i: *mut xcb_screen_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_screen_next: LazySymbol<unsafe fn(i: *mut xcb_screen_iterator_t)>,
    pub(crate) xcb_segment_end: LazySymbol<unsafe fn(i: *mut xcb_segment_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_segment_next: LazySymbol<unsafe fn(i: *mut xcb_segment_iterator_t)>,
    pub(crate) xcb_send_event: LazySymbol<unsafe fn(c: *mut xcb_connection_t, propagate: u8, destination: xcb_window_t, event_mask: u32, event: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_send_event_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, propagate: u8, destination: xcb_window_t, event_mask: u32, event: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_access_control: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_access_control_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_clip_rectangles: LazySymbol<unsafe fn(c: *mut xcb_connection_t, ordering: u8, gc: xcb_gcontext_t, clip_x_origin: i16, clip_y_origin: i16, rectangles_len: u32, rectangles: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_clip_rectangles_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, ordering: u8, gc: xcb_gcontext_t, clip_x_origin: i16, clip_y_origin: i16, rectangles_len: u32, rectangles: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_close_down_mode: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_close_down_mode_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_dashes: LazySymbol<unsafe fn(c: *mut xcb_connection_t, gc: xcb_gcontext_t, dash_offset: u16, dashes_len: u16, dashes: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_dashes_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, gc: xcb_gcontext_t, dash_offset: u16, dashes_len: u16, dashes: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_font_path: LazySymbol<unsafe fn(c: *mut xcb_connection_t, font_qty: u16, font: *const xcb_str_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_font_path_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, font_qty: u16, font: *const xcb_str_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_input_focus: LazySymbol<unsafe fn(c: *mut xcb_connection_t, revert_to: u8, focus: xcb_window_t, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_input_focus_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, revert_to: u8, focus: xcb_window_t, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_modifier_mapping: LazySymbol<unsafe fn(c: *mut xcb_connection_t, keycodes_per_modifier: u8, keycodes: *const xcb_keycode_t) -> xcb_set_modifier_mapping_cookie_t>,
    pub(crate) xcb_set_modifier_mapping_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_set_modifier_mapping_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_set_modifier_mapping_reply_t>,
    pub(crate) xcb_set_modifier_mapping_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, keycodes_per_modifier: u8, keycodes: *const xcb_keycode_t) -> xcb_set_modifier_mapping_cookie_t>,
    pub(crate) xcb_set_pointer_mapping: LazySymbol<unsafe fn(c: *mut xcb_connection_t, map_len: u8, map: *const u8) -> xcb_set_pointer_mapping_cookie_t>,
    pub(crate) xcb_set_pointer_mapping_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_set_pointer_mapping_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_set_pointer_mapping_reply_t>,
    pub(crate) xcb_set_pointer_mapping_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, map_len: u8, map: *const u8) -> xcb_set_pointer_mapping_cookie_t>,
    pub(crate) xcb_set_screen_saver: LazySymbol<unsafe fn(c: *mut xcb_connection_t, timeout: i16, interval: i16, prefer_blanking: u8, allow_exposures: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_screen_saver_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, timeout: i16, interval: i16, prefer_blanking: u8, allow_exposures: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_selection_owner: LazySymbol<unsafe fn(c: *mut xcb_connection_t, owner: xcb_window_t, selection: xcb_atom_t, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_set_selection_owner_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, owner: xcb_window_t, selection: xcb_atom_t, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_setup_authenticate_end: LazySymbol<unsafe fn(i: *mut xcb_setup_authenticate_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_setup_authenticate_next: LazySymbol<unsafe fn(i: *mut xcb_setup_authenticate_iterator_t)>,
    pub(crate) xcb_setup_authenticate_reason: LazySymbol<unsafe fn(R: *const xcb_setup_authenticate_t) -> *mut c_char>,
    pub(crate) xcb_setup_authenticate_reason_end: LazySymbol<unsafe fn(R: *const xcb_setup_authenticate_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_setup_authenticate_reason_length: LazySymbol<unsafe fn(R: *const xcb_setup_authenticate_t) -> c_int>,
    pub(crate) xcb_setup_end: LazySymbol<unsafe fn(i: *mut xcb_setup_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_setup_failed_end: LazySymbol<unsafe fn(i: *mut xcb_setup_failed_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_setup_failed_next: LazySymbol<unsafe fn(i: *mut xcb_setup_failed_iterator_t)>,
    pub(crate) xcb_setup_failed_reason: LazySymbol<unsafe fn(R: *const xcb_setup_failed_t) -> *mut c_char>,
    pub(crate) xcb_setup_failed_reason_end: LazySymbol<unsafe fn(R: *const xcb_setup_failed_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_setup_failed_reason_length: LazySymbol<unsafe fn(R: *const xcb_setup_failed_t) -> c_int>,
    pub(crate) xcb_setup_next: LazySymbol<unsafe fn(i: *mut xcb_setup_iterator_t)>,
    pub(crate) xcb_setup_pixmap_formats: LazySymbol<unsafe fn(R: *const xcb_setup_t) -> *mut xcb_format_t>,
    pub(crate) xcb_setup_pixmap_formats_iterator: LazySymbol<unsafe fn(R: *const xcb_setup_t) -> xcb_format_iterator_t>,
    pub(crate) xcb_setup_pixmap_formats_length: LazySymbol<unsafe fn(R: *const xcb_setup_t) -> c_int>,
    pub(crate) xcb_setup_request_authorization_protocol_data: LazySymbol<unsafe fn(R: *const xcb_setup_request_t) -> *mut c_char>,
    pub(crate) xcb_setup_request_authorization_protocol_data_end: LazySymbol<unsafe fn(R: *const xcb_setup_request_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_setup_request_authorization_protocol_data_length: LazySymbol<unsafe fn(R: *const xcb_setup_request_t) -> c_int>,
    pub(crate) xcb_setup_request_authorization_protocol_name: LazySymbol<unsafe fn(R: *const xcb_setup_request_t) -> *mut c_char>,
    pub(crate) xcb_setup_request_authorization_protocol_name_end: LazySymbol<unsafe fn(R: *const xcb_setup_request_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_setup_request_authorization_protocol_name_length: LazySymbol<unsafe fn(R: *const xcb_setup_request_t) -> c_int>,
    pub(crate) xcb_setup_request_end: LazySymbol<unsafe fn(i: *mut xcb_setup_request_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_setup_request_next: LazySymbol<unsafe fn(i: *mut xcb_setup_request_iterator_t)>,
    pub(crate) xcb_setup_roots_iterator: LazySymbol<unsafe fn(R: *const xcb_setup_t) -> xcb_screen_iterator_t>,
    pub(crate) xcb_setup_roots_length: LazySymbol<unsafe fn(R: *const xcb_setup_t) -> c_int>,
    pub(crate) xcb_setup_vendor: LazySymbol<unsafe fn(R: *const xcb_setup_t) -> *mut c_char>,
    pub(crate) xcb_setup_vendor_end: LazySymbol<unsafe fn(R: *const xcb_setup_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_setup_vendor_length: LazySymbol<unsafe fn(R: *const xcb_setup_t) -> c_int>,
    pub(crate) xcb_store_colors: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t, items_len: u32, items: *const xcb_coloritem_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_store_colors_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t, items_len: u32, items: *const xcb_coloritem_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_store_named_color: LazySymbol<unsafe fn(c: *mut xcb_connection_t, flags: u8, cmap: xcb_colormap_t, pixel: u32, name_len: u16, name: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_store_named_color_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, flags: u8, cmap: xcb_colormap_t, pixel: u32, name_len: u16, name: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_str_end: LazySymbol<unsafe fn(i: *mut xcb_str_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_str_name: LazySymbol<unsafe fn(R: *const xcb_str_t) -> *mut c_char>,
    pub(crate) xcb_str_name_end: LazySymbol<unsafe fn(R: *const xcb_str_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_str_name_length: LazySymbol<unsafe fn(R: *const xcb_str_t) -> c_int>,
    pub(crate) xcb_str_next: LazySymbol<unsafe fn(i: *mut xcb_str_iterator_t)>,
    pub(crate) xcb_timecoord_end: LazySymbol<unsafe fn(i: *mut xcb_timecoord_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_timecoord_next: LazySymbol<unsafe fn(i: *mut xcb_timecoord_iterator_t)>,
    pub(crate) xcb_timestamp_end: LazySymbol<unsafe fn(i: *mut xcb_timestamp_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_timestamp_next: LazySymbol<unsafe fn(i: *mut xcb_timestamp_iterator_t)>,
    pub(crate) xcb_translate_coordinates: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src_window: xcb_window_t, dst_window: xcb_window_t, src_x: i16, src_y: i16) -> xcb_translate_coordinates_cookie_t>,
    pub(crate) xcb_translate_coordinates_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_translate_coordinates_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_translate_coordinates_reply_t>,
    pub(crate) xcb_translate_coordinates_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src_window: xcb_window_t, dst_window: xcb_window_t, src_x: i16, src_y: i16) -> xcb_translate_coordinates_cookie_t>,
    pub(crate) xcb_ungrab_button: LazySymbol<unsafe fn(c: *mut xcb_connection_t, button: u8, grab_window: xcb_window_t, modifiers: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_ungrab_button_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, button: u8, grab_window: xcb_window_t, modifiers: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_ungrab_key: LazySymbol<unsafe fn(c: *mut xcb_connection_t, key: xcb_keycode_t, grab_window: xcb_window_t, modifiers: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_ungrab_key_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, key: xcb_keycode_t, grab_window: xcb_window_t, modifiers: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_ungrab_keyboard: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_ungrab_keyboard_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_ungrab_pointer: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_ungrab_pointer_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_ungrab_server: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_ungrab_server_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_uninstall_colormap: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_uninstall_colormap_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cmap: xcb_colormap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_unmap_subwindows: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_unmap_subwindows_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_unmap_window: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_unmap_window_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_unregister_for_special_event: LazySymbol<unsafe fn(c: *mut xcb_connection_t, se: *mut xcb_special_event_t)>,
    pub(crate) xcb_visualid_end: LazySymbol<unsafe fn(i: *mut xcb_visualid_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_visualid_next: LazySymbol<unsafe fn(i: *mut xcb_visualid_iterator_t)>,
    pub(crate) xcb_visualtype_end: LazySymbol<unsafe fn(i: *mut xcb_visualtype_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_visualtype_next: LazySymbol<unsafe fn(i: *mut xcb_visualtype_iterator_t)>,
    pub(crate) xcb_wait_for_event: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> *mut xcb_generic_event_t>,
    pub(crate) xcb_wait_for_special_event: LazySymbol<unsafe fn(c: *mut xcb_connection_t, se: *mut xcb_special_event_t) -> *mut xcb_generic_event_t>,
    pub(crate) xcb_warp_pointer: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src_window: xcb_window_t, dst_window: xcb_window_t, src_x: i16, src_y: i16, src_width: u16, src_height: u16, dst_x: i16, dst_y: i16) -> xcb_void_cookie_t>,
    pub(crate) xcb_warp_pointer_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src_window: xcb_window_t, dst_window: xcb_window_t, src_x: i16, src_y: i16, src_width: u16, src_height: u16, dst_x: i16, dst_y: i16) -> xcb_void_cookie_t>,
    pub(crate) xcb_window_end: LazySymbol<unsafe fn(i: *mut xcb_window_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_window_next: LazySymbol<unsafe fn(i: *mut xcb_window_iterator_t)>,
    pub(crate) xcb_xc_misc_get_version: LazySymbol<unsafe fn(c: *mut xcb_connection_t, client_major_version: u16, client_minor_version: u16) -> xcb_xc_misc_get_version_cookie_t>,
    pub(crate) xcb_xc_misc_get_version_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xc_misc_get_version_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xc_misc_get_version_reply_t>,
    pub(crate) xcb_xc_misc_get_version_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, client_major_version: u16, client_minor_version: u16) -> xcb_xc_misc_get_version_cookie_t>,
    pub(crate) xcb_xc_misc_get_xid_list: LazySymbol<unsafe fn(c: *mut xcb_connection_t, count: u32) -> xcb_xc_misc_get_xid_list_cookie_t>,
    pub(crate) xcb_xc_misc_get_xid_list_ids: LazySymbol<unsafe fn(R: *const xcb_xc_misc_get_xid_list_reply_t) -> *mut u32>,
    pub(crate) xcb_xc_misc_get_xid_list_ids_end: LazySymbol<unsafe fn(R: *const xcb_xc_misc_get_xid_list_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xc_misc_get_xid_list_ids_length: LazySymbol<unsafe fn(R: *const xcb_xc_misc_get_xid_list_reply_t) -> c_int>,
    pub(crate) xcb_xc_misc_get_xid_list_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xc_misc_get_xid_list_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xc_misc_get_xid_list_reply_t>,
    pub(crate) xcb_xc_misc_get_xid_list_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, count: u32) -> xcb_xc_misc_get_xid_list_cookie_t>,
    pub(crate) xcb_xc_misc_get_xid_range: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_xc_misc_get_xid_range_cookie_t>,
    pub(crate) xcb_xc_misc_get_xid_range_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xc_misc_get_xid_range_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xc_misc_get_xid_range_reply_t>,
    pub(crate) xcb_xc_misc_get_xid_range_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_xc_misc_get_xid_range_cookie_t>,
    pub(crate) xcb_xc_misc_id: LazySymbol<*mut xcb_extension_t>,
}

const SO_NAME: &str = "libxcb.so.1";

impl Xcb {
    #[inline]
    pub unsafe fn new() -> Result<Self, Error> {
        let lib = Library::new(SO_NAME)?;
        Ok(init_lib!(lib, SO_NAME))
    }
}
