use crate::lazy::*;
use crate::*;
use libloading::{Error, Library};
use std::os::raw::*;

#[rustfmt::skip]
pub struct XcbXfixes {
    pub(crate) lib: NamedLibrary,
    pub(crate) xcb_xfixes_barrier_end: LazySymbol<unsafe fn(i: *mut xcb_xfixes_barrier_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xfixes_barrier_next: LazySymbol<unsafe fn(i: *mut xcb_xfixes_barrier_iterator_t)>,
    pub(crate) xcb_xfixes_change_cursor: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source: xcb_cursor_t, destination: xcb_cursor_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_change_cursor_by_name: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src: xcb_cursor_t, nbytes: u16, name: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_change_cursor_by_name_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src: xcb_cursor_t, nbytes: u16, name: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_change_cursor_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source: xcb_cursor_t, destination: xcb_cursor_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_change_save_set: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8, target: u8, map: u8, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_change_save_set_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: u8, target: u8, map: u8, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_copy_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source: xcb_xfixes_region_t, destination: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_copy_region_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source: xcb_xfixes_region_t, destination: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_create_pointer_barrier: LazySymbol<unsafe fn(c: *mut xcb_connection_t, barrier: xcb_xfixes_barrier_t, window: xcb_window_t, x1: u16, y1: u16, x2: u16, y2: u16, directions: u32, num_devices: u16, devices: *const u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_create_pointer_barrier_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, barrier: xcb_xfixes_barrier_t, window: xcb_window_t, x1: u16, y1: u16, x2: u16, y2: u16, directions: u32, num_devices: u16, devices: *const u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_create_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, rectangles_len: u32, rectangles: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_create_region_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, rectangles_len: u32, rectangles: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_create_region_from_bitmap: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, bitmap: xcb_pixmap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_create_region_from_bitmap_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, bitmap: xcb_pixmap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_create_region_from_gc: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, gc: xcb_gcontext_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_create_region_from_gc_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, gc: xcb_gcontext_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_create_region_from_picture: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, picture: xcb_render_picture_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_create_region_from_picture_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, picture: xcb_render_picture_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_create_region_from_window: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, window: xcb_window_t, kind: xcb_shape_kind_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_create_region_from_window_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, window: xcb_window_t, kind: xcb_shape_kind_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_delete_pointer_barrier: LazySymbol<unsafe fn(c: *mut xcb_connection_t, barrier: xcb_xfixes_barrier_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_delete_pointer_barrier_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, barrier: xcb_xfixes_barrier_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_destroy_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_destroy_region_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_expand_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source: xcb_xfixes_region_t, destination: xcb_xfixes_region_t, left: u16, right: u16, top: u16, bottom: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_expand_region_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source: xcb_xfixes_region_t, destination: xcb_xfixes_region_t, left: u16, right: u16, top: u16, bottom: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_fetch_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t) -> xcb_xfixes_fetch_region_cookie_t>,
    pub(crate) xcb_xfixes_fetch_region_rectangles: LazySymbol<unsafe fn(R: *const xcb_xfixes_fetch_region_reply_t) -> *mut xcb_rectangle_t>,
    pub(crate) xcb_xfixes_fetch_region_rectangles_iterator: LazySymbol<unsafe fn(R: *const xcb_xfixes_fetch_region_reply_t) -> xcb_rectangle_iterator_t>,
    pub(crate) xcb_xfixes_fetch_region_rectangles_length: LazySymbol<unsafe fn(R: *const xcb_xfixes_fetch_region_reply_t) -> c_int>,
    pub(crate) xcb_xfixes_fetch_region_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xfixes_fetch_region_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xfixes_fetch_region_reply_t>,
    pub(crate) xcb_xfixes_fetch_region_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t) -> xcb_xfixes_fetch_region_cookie_t>,
    pub(crate) xcb_xfixes_get_cursor_image: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_xfixes_get_cursor_image_cookie_t>,
    pub(crate) xcb_xfixes_get_cursor_image_and_name: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_xfixes_get_cursor_image_and_name_cookie_t>,
    pub(crate) xcb_xfixes_get_cursor_image_and_name_cursor_image: LazySymbol<unsafe fn(R: *const xcb_xfixes_get_cursor_image_and_name_reply_t) -> *mut u32>,
    pub(crate) xcb_xfixes_get_cursor_image_and_name_cursor_image_end: LazySymbol<unsafe fn(R: *const xcb_xfixes_get_cursor_image_and_name_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xfixes_get_cursor_image_and_name_cursor_image_length: LazySymbol<unsafe fn(R: *const xcb_xfixes_get_cursor_image_and_name_reply_t) -> c_int>,
    pub(crate) xcb_xfixes_get_cursor_image_and_name_name: LazySymbol<unsafe fn(R: *const xcb_xfixes_get_cursor_image_and_name_reply_t) -> *mut c_char>,
    pub(crate) xcb_xfixes_get_cursor_image_and_name_name_end: LazySymbol<unsafe fn(R: *const xcb_xfixes_get_cursor_image_and_name_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xfixes_get_cursor_image_and_name_name_length: LazySymbol<unsafe fn(R: *const xcb_xfixes_get_cursor_image_and_name_reply_t) -> c_int>,
    pub(crate) xcb_xfixes_get_cursor_image_and_name_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xfixes_get_cursor_image_and_name_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xfixes_get_cursor_image_and_name_reply_t>,
    pub(crate) xcb_xfixes_get_cursor_image_and_name_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_xfixes_get_cursor_image_and_name_cookie_t>,
    pub(crate) xcb_xfixes_get_cursor_image_cursor_image: LazySymbol<unsafe fn(R: *const xcb_xfixes_get_cursor_image_reply_t) -> *mut u32>,
    pub(crate) xcb_xfixes_get_cursor_image_cursor_image_end: LazySymbol<unsafe fn(R: *const xcb_xfixes_get_cursor_image_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xfixes_get_cursor_image_cursor_image_length: LazySymbol<unsafe fn(R: *const xcb_xfixes_get_cursor_image_reply_t) -> c_int>,
    pub(crate) xcb_xfixes_get_cursor_image_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xfixes_get_cursor_image_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xfixes_get_cursor_image_reply_t>,
    pub(crate) xcb_xfixes_get_cursor_image_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_xfixes_get_cursor_image_cookie_t>,
    pub(crate) xcb_xfixes_get_cursor_name: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cursor: xcb_cursor_t) -> xcb_xfixes_get_cursor_name_cookie_t>,
    pub(crate) xcb_xfixes_get_cursor_name_name: LazySymbol<unsafe fn(R: *const xcb_xfixes_get_cursor_name_reply_t) -> *mut c_char>,
    pub(crate) xcb_xfixes_get_cursor_name_name_end: LazySymbol<unsafe fn(R: *const xcb_xfixes_get_cursor_name_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xfixes_get_cursor_name_name_length: LazySymbol<unsafe fn(R: *const xcb_xfixes_get_cursor_name_reply_t) -> c_int>,
    pub(crate) xcb_xfixes_get_cursor_name_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xfixes_get_cursor_name_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xfixes_get_cursor_name_reply_t>,
    pub(crate) xcb_xfixes_get_cursor_name_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cursor: xcb_cursor_t) -> xcb_xfixes_get_cursor_name_cookie_t>,
    pub(crate) xcb_xfixes_hide_cursor: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_hide_cursor_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_id: LazySymbol<*mut xcb_extension_t>,
    pub(crate) xcb_xfixes_intersect_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source1: xcb_xfixes_region_t, source2: xcb_xfixes_region_t, destination: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_intersect_region_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source1: xcb_xfixes_region_t, source2: xcb_xfixes_region_t, destination: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_invert_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source: xcb_xfixes_region_t, bounds: xcb_rectangle_t, destination: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_invert_region_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source: xcb_xfixes_region_t, bounds: xcb_rectangle_t, destination: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_query_version: LazySymbol<unsafe fn(c: *mut xcb_connection_t, client_major_version: u32, client_minor_version: u32) -> xcb_xfixes_query_version_cookie_t>,
    pub(crate) xcb_xfixes_query_version_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xfixes_query_version_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xfixes_query_version_reply_t>,
    pub(crate) xcb_xfixes_query_version_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, client_major_version: u32, client_minor_version: u32) -> xcb_xfixes_query_version_cookie_t>,
    pub(crate) xcb_xfixes_region_end: LazySymbol<unsafe fn(i: *mut xcb_xfixes_region_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xfixes_region_extents: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source: xcb_xfixes_region_t, destination: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_region_extents_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source: xcb_xfixes_region_t, destination: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_region_next: LazySymbol<unsafe fn(i: *mut xcb_xfixes_region_iterator_t)>,
    pub(crate) xcb_xfixes_select_cursor_input: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, event_mask: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_select_cursor_input_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, event_mask: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_select_selection_input: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, selection: xcb_atom_t, event_mask: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_select_selection_input_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, selection: xcb_atom_t, event_mask: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_set_cursor_name: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cursor: xcb_cursor_t, nbytes: u16, name: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_set_cursor_name_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cursor: xcb_cursor_t, nbytes: u16, name: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_set_gc_clip_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, gc: xcb_gcontext_t, region: xcb_xfixes_region_t, x_origin: i16, y_origin: i16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_set_gc_clip_region_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, gc: xcb_gcontext_t, region: xcb_xfixes_region_t, x_origin: i16, y_origin: i16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_set_picture_clip_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, region: xcb_xfixes_region_t, x_origin: i16, y_origin: i16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_set_picture_clip_region_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, region: xcb_xfixes_region_t, x_origin: i16, y_origin: i16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_set_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, rectangles_len: u32, rectangles: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_set_region_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, rectangles_len: u32, rectangles: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_set_window_shape_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, dest: xcb_window_t, dest_kind: xcb_shape_kind_t, x_offset: i16, y_offset: i16, region: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_set_window_shape_region_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, dest: xcb_window_t, dest_kind: xcb_shape_kind_t, x_offset: i16, y_offset: i16, region: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_show_cursor: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_show_cursor_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_subtract_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source1: xcb_xfixes_region_t, source2: xcb_xfixes_region_t, destination: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_subtract_region_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source1: xcb_xfixes_region_t, source2: xcb_xfixes_region_t, destination: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_translate_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, dx: i16, dy: i16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_translate_region_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, region: xcb_xfixes_region_t, dx: i16, dy: i16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_union_region: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source1: xcb_xfixes_region_t, source2: xcb_xfixes_region_t, destination: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xfixes_union_region_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, source1: xcb_xfixes_region_t, source2: xcb_xfixes_region_t, destination: xcb_xfixes_region_t) -> xcb_void_cookie_t>,
}
