use crate::ffi::*;
use crate::lazy::*;
use libloading::{Error, Library};
use std::os::raw::*;

#[rustfmt::skip]
pub struct XcbXf86dri {
    pub(crate) lib: NamedLibrary,
    pub(crate) xcb_xf86dri_auth_connection: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, magic: u32) -> xcb_xf86dri_auth_connection_cookie_t>,
    pub(crate) xcb_xf86dri_auth_connection_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xf86dri_auth_connection_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xf86dri_auth_connection_reply_t>,
    pub(crate) xcb_xf86dri_auth_connection_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, magic: u32) -> xcb_xf86dri_auth_connection_cookie_t>,
    pub(crate) xcb_xf86dri_close_connection: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xf86dri_close_connection_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xf86dri_create_context: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, visual: u32, context: u32) -> xcb_xf86dri_create_context_cookie_t>,
    pub(crate) xcb_xf86dri_create_context_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xf86dri_create_context_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xf86dri_create_context_reply_t>,
    pub(crate) xcb_xf86dri_create_context_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, visual: u32, context: u32) -> xcb_xf86dri_create_context_cookie_t>,
    pub(crate) xcb_xf86dri_create_drawable: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, drawable: u32) -> xcb_xf86dri_create_drawable_cookie_t>,
    pub(crate) xcb_xf86dri_create_drawable_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xf86dri_create_drawable_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xf86dri_create_drawable_reply_t>,
    pub(crate) xcb_xf86dri_create_drawable_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, drawable: u32) -> xcb_xf86dri_create_drawable_cookie_t>,
    pub(crate) xcb_xf86dri_destroy_context: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, context: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xf86dri_destroy_context_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, context: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xf86dri_destroy_drawable: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, drawable: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xf86dri_destroy_drawable_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, drawable: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xf86dri_drm_clip_rect_end: LazySymbol<unsafe fn(i: *mut xcb_xf86dri_drm_clip_rect_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xf86dri_drm_clip_rect_next: LazySymbol<unsafe fn(i: *mut xcb_xf86dri_drm_clip_rect_iterator_t)>,
    pub(crate) xcb_xf86dri_get_client_driver_name: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_xf86dri_get_client_driver_name_cookie_t>,
    pub(crate) xcb_xf86dri_get_client_driver_name_client_driver_name: LazySymbol<unsafe fn(R: *const xcb_xf86dri_get_client_driver_name_reply_t) -> *mut c_char>,
    pub(crate) xcb_xf86dri_get_client_driver_name_client_driver_name_end: LazySymbol<unsafe fn(R: *const xcb_xf86dri_get_client_driver_name_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xf86dri_get_client_driver_name_client_driver_name_length: LazySymbol<unsafe fn(R: *const xcb_xf86dri_get_client_driver_name_reply_t) -> c_int>,
    pub(crate) xcb_xf86dri_get_client_driver_name_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xf86dri_get_client_driver_name_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xf86dri_get_client_driver_name_reply_t>,
    pub(crate) xcb_xf86dri_get_client_driver_name_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_xf86dri_get_client_driver_name_cookie_t>,
    pub(crate) xcb_xf86dri_get_device_info: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_xf86dri_get_device_info_cookie_t>,
    pub(crate) xcb_xf86dri_get_device_info_device_private: LazySymbol<unsafe fn(R: *const xcb_xf86dri_get_device_info_reply_t) -> *mut u32>,
    pub(crate) xcb_xf86dri_get_device_info_device_private_end: LazySymbol<unsafe fn(R: *const xcb_xf86dri_get_device_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xf86dri_get_device_info_device_private_length: LazySymbol<unsafe fn(R: *const xcb_xf86dri_get_device_info_reply_t) -> c_int>,
    pub(crate) xcb_xf86dri_get_device_info_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xf86dri_get_device_info_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xf86dri_get_device_info_reply_t>,
    pub(crate) xcb_xf86dri_get_device_info_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_xf86dri_get_device_info_cookie_t>,
    pub(crate) xcb_xf86dri_get_drawable_info: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, drawable: u32) -> xcb_xf86dri_get_drawable_info_cookie_t>,
    pub(crate) xcb_xf86dri_get_drawable_info_back_clip_rects: LazySymbol<unsafe fn(R: *const xcb_xf86dri_get_drawable_info_reply_t) -> *mut xcb_xf86dri_drm_clip_rect_t>,
    pub(crate) xcb_xf86dri_get_drawable_info_back_clip_rects_iterator: LazySymbol<unsafe fn(R: *const xcb_xf86dri_get_drawable_info_reply_t) -> xcb_xf86dri_drm_clip_rect_iterator_t>,
    pub(crate) xcb_xf86dri_get_drawable_info_back_clip_rects_length: LazySymbol<unsafe fn(R: *const xcb_xf86dri_get_drawable_info_reply_t) -> c_int>,
    pub(crate) xcb_xf86dri_get_drawable_info_clip_rects: LazySymbol<unsafe fn(R: *const xcb_xf86dri_get_drawable_info_reply_t) -> *mut xcb_xf86dri_drm_clip_rect_t>,
    pub(crate) xcb_xf86dri_get_drawable_info_clip_rects_iterator: LazySymbol<unsafe fn(R: *const xcb_xf86dri_get_drawable_info_reply_t) -> xcb_xf86dri_drm_clip_rect_iterator_t>,
    pub(crate) xcb_xf86dri_get_drawable_info_clip_rects_length: LazySymbol<unsafe fn(R: *const xcb_xf86dri_get_drawable_info_reply_t) -> c_int>,
    pub(crate) xcb_xf86dri_get_drawable_info_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xf86dri_get_drawable_info_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xf86dri_get_drawable_info_reply_t>,
    pub(crate) xcb_xf86dri_get_drawable_info_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, drawable: u32) -> xcb_xf86dri_get_drawable_info_cookie_t>,
    pub(crate) xcb_xf86dri_id: LazySymbol<*mut xcb_extension_t>,
    pub(crate) xcb_xf86dri_open_connection: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_xf86dri_open_connection_cookie_t>,
    pub(crate) xcb_xf86dri_open_connection_bus_id: LazySymbol<unsafe fn(R: *const xcb_xf86dri_open_connection_reply_t) -> *mut c_char>,
    pub(crate) xcb_xf86dri_open_connection_bus_id_end: LazySymbol<unsafe fn(R: *const xcb_xf86dri_open_connection_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xf86dri_open_connection_bus_id_length: LazySymbol<unsafe fn(R: *const xcb_xf86dri_open_connection_reply_t) -> c_int>,
    pub(crate) xcb_xf86dri_open_connection_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xf86dri_open_connection_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xf86dri_open_connection_reply_t>,
    pub(crate) xcb_xf86dri_open_connection_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_xf86dri_open_connection_cookie_t>,
    pub(crate) xcb_xf86dri_query_direct_rendering_capable: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_xf86dri_query_direct_rendering_capable_cookie_t>,
    pub(crate) xcb_xf86dri_query_direct_rendering_capable_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xf86dri_query_direct_rendering_capable_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xf86dri_query_direct_rendering_capable_reply_t>,
    pub(crate) xcb_xf86dri_query_direct_rendering_capable_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_xf86dri_query_direct_rendering_capable_cookie_t>,
    pub(crate) xcb_xf86dri_query_version: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_xf86dri_query_version_cookie_t>,
    pub(crate) xcb_xf86dri_query_version_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xf86dri_query_version_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xf86dri_query_version_reply_t>,
    pub(crate) xcb_xf86dri_query_version_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_xf86dri_query_version_cookie_t>,
}
