use crate::lazy::*;
use crate::*;
use libloading::{Error, Library};
use std::os::raw::*;

#[rustfmt::skip]
pub struct XcbXkb {
    pub(crate) lib: NamedLibrary,
    pub(crate) xcb_xkb_action_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_action_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_action_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_action_iterator_t)>,
    pub(crate) xcb_xkb_behavior_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_behavior_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_behavior_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_behavior_iterator_t)>,
    pub(crate) xcb_xkb_bell: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, bell_class: xcb_xkb_bell_class_spec_t, bell_id: xcb_xkb_id_spec_t, percent: i8, force_sound: u8, event_only: u8, pitch: i16, duration: i16, name: xcb_atom_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_bell_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, bell_class: xcb_xkb_bell_class_spec_t, bell_id: xcb_xkb_id_spec_t, percent: i8, force_sound: u8, event_only: u8, pitch: i16, duration: i16, name: xcb_atom_t, window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_bell_class_spec_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_bell_class_spec_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_bell_class_spec_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_bell_class_spec_iterator_t)>,
    pub(crate) xcb_xkb_common_behavior_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_common_behavior_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_common_behavior_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_common_behavior_iterator_t)>,
    pub(crate) xcb_xkb_counted_string_16_alignment_pad: LazySymbol<unsafe fn(R: *const xcb_xkb_counted_string_16_t) -> *mut c_void>,
    pub(crate) xcb_xkb_counted_string_16_alignment_pad_end: LazySymbol<unsafe fn(R: *const xcb_xkb_counted_string_16_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_counted_string_16_alignment_pad_length: LazySymbol<unsafe fn(R: *const xcb_xkb_counted_string_16_t) -> c_int>,
    pub(crate) xcb_xkb_counted_string_16_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_counted_string_16_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_counted_string_16_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_counted_string_16_iterator_t)>,
    pub(crate) xcb_xkb_counted_string_16_string: LazySymbol<unsafe fn(R: *const xcb_xkb_counted_string_16_t) -> *mut c_char>,
    pub(crate) xcb_xkb_counted_string_16_string_end: LazySymbol<unsafe fn(R: *const xcb_xkb_counted_string_16_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_counted_string_16_string_length: LazySymbol<unsafe fn(R: *const xcb_xkb_counted_string_16_t) -> c_int>,
    pub(crate) xcb_xkb_default_behavior_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_default_behavior_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_default_behavior_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_default_behavior_iterator_t)>,
    pub(crate) xcb_xkb_device_led_info_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_device_led_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_device_led_info_maps: LazySymbol<unsafe fn(R: *const xcb_xkb_device_led_info_t) -> *mut xcb_xkb_indicator_map_t>,
    pub(crate) xcb_xkb_device_led_info_maps_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_device_led_info_t) -> xcb_xkb_indicator_map_iterator_t>,
    pub(crate) xcb_xkb_device_led_info_maps_length: LazySymbol<unsafe fn(R: *const xcb_xkb_device_led_info_t) -> c_int>,
    pub(crate) xcb_xkb_device_led_info_names: LazySymbol<unsafe fn(R: *const xcb_xkb_device_led_info_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_device_led_info_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_device_led_info_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_device_led_info_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_device_led_info_t) -> c_int>,
    pub(crate) xcb_xkb_device_led_info_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_device_led_info_iterator_t)>,
    pub(crate) xcb_xkb_device_spec_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_device_spec_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_device_spec_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_device_spec_iterator_t)>,
    pub(crate) xcb_xkb_get_compat_map: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, groups: u8, get_all_si: u8, first_si: u16, n_si: u16) -> xcb_xkb_get_compat_map_cookie_t>,
    pub(crate) xcb_xkb_get_compat_map_group_rtrn: LazySymbol<unsafe fn(R: *const xcb_xkb_get_compat_map_reply_t) -> *mut xcb_xkb_mod_def_t>,
    pub(crate) xcb_xkb_get_compat_map_group_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_compat_map_reply_t) -> xcb_xkb_mod_def_iterator_t>,
    pub(crate) xcb_xkb_get_compat_map_group_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_compat_map_reply_t) -> c_int>,
    pub(crate) xcb_xkb_get_compat_map_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_get_compat_map_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_get_compat_map_reply_t>,
    pub(crate) xcb_xkb_get_compat_map_si_rtrn: LazySymbol<unsafe fn(R: *const xcb_xkb_get_compat_map_reply_t) -> *mut xcb_xkb_sym_interpret_t>,
    pub(crate) xcb_xkb_get_compat_map_si_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_compat_map_reply_t) -> xcb_xkb_sym_interpret_iterator_t>,
    pub(crate) xcb_xkb_get_compat_map_si_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_compat_map_reply_t) -> c_int>,
    pub(crate) xcb_xkb_get_compat_map_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, groups: u8, get_all_si: u8, first_si: u16, n_si: u16) -> xcb_xkb_get_compat_map_cookie_t>,
    pub(crate) xcb_xkb_get_controls: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t) -> xcb_xkb_get_controls_cookie_t>,
    pub(crate) xcb_xkb_get_controls_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_get_controls_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_get_controls_reply_t>,
    pub(crate) xcb_xkb_get_controls_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t) -> xcb_xkb_get_controls_cookie_t>,
    pub(crate) xcb_xkb_get_device_info: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, wanted: u16, all_buttons: u8, first_button: u8, n_buttons: u8, led_class: xcb_xkb_led_class_spec_t, led_id: xcb_xkb_id_spec_t) -> xcb_xkb_get_device_info_cookie_t>,
    pub(crate) xcb_xkb_get_device_info_btn_actions: LazySymbol<unsafe fn(R: *const xcb_xkb_get_device_info_reply_t) -> *mut xcb_xkb_action_t>,
    pub(crate) xcb_xkb_get_device_info_btn_actions_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_device_info_reply_t) -> xcb_xkb_action_iterator_t>,
    pub(crate) xcb_xkb_get_device_info_btn_actions_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_device_info_reply_t) -> c_int>,
    pub(crate) xcb_xkb_get_device_info_leds_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_device_info_reply_t) -> xcb_xkb_device_led_info_iterator_t>,
    pub(crate) xcb_xkb_get_device_info_leds_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_device_info_reply_t) -> c_int>,
    pub(crate) xcb_xkb_get_device_info_name: LazySymbol<unsafe fn(R: *const xcb_xkb_get_device_info_reply_t) -> *mut xcb_xkb_string8_t>,
    pub(crate) xcb_xkb_get_device_info_name_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_device_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_device_info_name_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_device_info_reply_t) -> c_int>,
    pub(crate) xcb_xkb_get_device_info_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_get_device_info_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_get_device_info_reply_t>,
    pub(crate) xcb_xkb_get_device_info_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, wanted: u16, all_buttons: u8, first_button: u8, n_buttons: u8, led_class: xcb_xkb_led_class_spec_t, led_id: xcb_xkb_id_spec_t) -> xcb_xkb_get_device_info_cookie_t>,
    pub(crate) xcb_xkb_get_indicator_map: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, which: u32) -> xcb_xkb_get_indicator_map_cookie_t>,
    pub(crate) xcb_xkb_get_indicator_map_maps: LazySymbol<unsafe fn(R: *const xcb_xkb_get_indicator_map_reply_t) -> *mut xcb_xkb_indicator_map_t>,
    pub(crate) xcb_xkb_get_indicator_map_maps_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_indicator_map_reply_t) -> xcb_xkb_indicator_map_iterator_t>,
    pub(crate) xcb_xkb_get_indicator_map_maps_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_indicator_map_reply_t) -> c_int>,
    pub(crate) xcb_xkb_get_indicator_map_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_get_indicator_map_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_get_indicator_map_reply_t>,
    pub(crate) xcb_xkb_get_indicator_map_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, which: u32) -> xcb_xkb_get_indicator_map_cookie_t>,
    pub(crate) xcb_xkb_get_indicator_state: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t) -> xcb_xkb_get_indicator_state_cookie_t>,
    pub(crate) xcb_xkb_get_indicator_state_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_get_indicator_state_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_get_indicator_state_reply_t>,
    pub(crate) xcb_xkb_get_indicator_state_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t) -> xcb_xkb_get_indicator_state_cookie_t>,
    pub(crate) xcb_xkb_get_kbd_by_name: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, need: u16, want: u16, load: u8) -> xcb_xkb_get_kbd_by_name_cookie_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t) -> *mut c_void>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_compat_map_group_rtrn: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_xkb_mod_def_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_compat_map_group_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_xkb_mod_def_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_compat_map_group_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_compat_map_si_rtrn: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_xkb_sym_interpret_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_compat_map_si_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_xkb_sym_interpret_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_compat_map_si_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_geometry_label_font: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_xkb_counted_string_16_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_indicator_maps_maps: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_xkb_indicator_map_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_indicator_maps_maps_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_xkb_indicator_map_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_indicator_maps_maps_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_xkb_get_kbd_by_name_replies_key_names_value_list_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_groups: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_groups_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_groups_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_indicator_names: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_indicator_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_indicator_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_key_aliases: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_xkb_key_alias_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_key_aliases_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_xkb_key_alias_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_key_aliases_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_key_names: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_xkb_key_name_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_key_names_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_xkb_key_name_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_key_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_kt_level_names: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_kt_level_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_kt_level_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_n_levels_per_type: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut u8>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_n_levels_per_type_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_n_levels_per_type_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_radio_group_names: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_radio_group_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_radio_group_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_type_names: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_type_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_type_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_virtual_mod_names: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_virtual_mod_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_key_names_value_list_virtual_mod_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_xkb_get_kbd_by_name_replies_types_map_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_acts_rtrn_acts: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_xkb_action_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_acts_rtrn_acts_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_xkb_action_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_acts_rtrn_acts_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_acts_rtrn_count: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut u8>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_acts_rtrn_count_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_acts_rtrn_count_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_behaviors_rtrn: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_xkb_set_behavior_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_behaviors_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_xkb_set_behavior_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_behaviors_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_explicit_rtrn: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_xkb_set_explicit_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_explicit_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_xkb_set_explicit_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_explicit_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_modmap_rtrn: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_xkb_key_mod_map_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_modmap_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_xkb_key_mod_map_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_modmap_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_syms_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_xkb_key_sym_map_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_syms_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_types_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_xkb_key_type_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_types_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_vmodmap_rtrn: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut xcb_xkb_key_v_mod_map_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_vmodmap_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_xkb_key_v_mod_map_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_vmodmap_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_vmods_rtrn: LazySymbol<unsafe fn(S: *const xcb_xkb_get_kbd_by_name_replies_t) -> *mut u8>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_vmods_rtrn_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_replies_types_map_vmods_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_kbd_by_name_reply_t, S: *const xcb_xkb_get_kbd_by_name_replies_t) -> c_int>,
    pub(crate) xcb_xkb_get_kbd_by_name_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_get_kbd_by_name_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_get_kbd_by_name_reply_t>,
    pub(crate) xcb_xkb_get_kbd_by_name_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, need: u16, want: u16, load: u8) -> xcb_xkb_get_kbd_by_name_cookie_t>,
    pub(crate) xcb_xkb_get_map: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, full: u16, partial: u16, first_type: u8, n_types: u8, first_key_sym: xcb_keycode_t, n_key_syms: u8, first_key_action: xcb_keycode_t, n_key_actions: u8, first_key_behavior: xcb_keycode_t, n_key_behaviors: u8, virtual_mods: u16, first_key_explicit: xcb_keycode_t, n_key_explicit: u8, first_mod_map_key: xcb_keycode_t, n_mod_map_keys: u8, first_v_mod_map_key: xcb_keycode_t, n_v_mod_map_keys: u8) -> xcb_xkb_get_map_cookie_t>,
    pub(crate) xcb_xkb_get_map_map: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t) -> *mut c_void>,
    pub(crate) xcb_xkb_get_map_map_acts_rtrn_acts: LazySymbol<unsafe fn(S: *const xcb_xkb_get_map_map_t) -> *mut xcb_xkb_action_t>,
    pub(crate) xcb_xkb_get_map_map_acts_rtrn_acts_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> xcb_xkb_action_iterator_t>,
    pub(crate) xcb_xkb_get_map_map_acts_rtrn_acts_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> c_int>,
    pub(crate) xcb_xkb_get_map_map_acts_rtrn_count: LazySymbol<unsafe fn(S: *const xcb_xkb_get_map_map_t) -> *mut u8>,
    pub(crate) xcb_xkb_get_map_map_acts_rtrn_count_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_map_map_acts_rtrn_count_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> c_int>,
    pub(crate) xcb_xkb_get_map_map_behaviors_rtrn: LazySymbol<unsafe fn(S: *const xcb_xkb_get_map_map_t) -> *mut xcb_xkb_set_behavior_t>,
    pub(crate) xcb_xkb_get_map_map_behaviors_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> xcb_xkb_set_behavior_iterator_t>,
    pub(crate) xcb_xkb_get_map_map_behaviors_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> c_int>,
    pub(crate) xcb_xkb_get_map_map_explicit_rtrn: LazySymbol<unsafe fn(S: *const xcb_xkb_get_map_map_t) -> *mut xcb_xkb_set_explicit_t>,
    pub(crate) xcb_xkb_get_map_map_explicit_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> xcb_xkb_set_explicit_iterator_t>,
    pub(crate) xcb_xkb_get_map_map_explicit_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> c_int>,
    pub(crate) xcb_xkb_get_map_map_modmap_rtrn: LazySymbol<unsafe fn(S: *const xcb_xkb_get_map_map_t) -> *mut xcb_xkb_key_mod_map_t>,
    pub(crate) xcb_xkb_get_map_map_modmap_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> xcb_xkb_key_mod_map_iterator_t>,
    pub(crate) xcb_xkb_get_map_map_modmap_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> c_int>,
    pub(crate) xcb_xkb_get_map_map_syms_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> xcb_xkb_key_sym_map_iterator_t>,
    pub(crate) xcb_xkb_get_map_map_syms_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> c_int>,
    pub(crate) xcb_xkb_get_map_map_types_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> xcb_xkb_key_type_iterator_t>,
    pub(crate) xcb_xkb_get_map_map_types_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> c_int>,
    pub(crate) xcb_xkb_get_map_map_vmodmap_rtrn: LazySymbol<unsafe fn(S: *const xcb_xkb_get_map_map_t) -> *mut xcb_xkb_key_v_mod_map_t>,
    pub(crate) xcb_xkb_get_map_map_vmodmap_rtrn_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> xcb_xkb_key_v_mod_map_iterator_t>,
    pub(crate) xcb_xkb_get_map_map_vmodmap_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> c_int>,
    pub(crate) xcb_xkb_get_map_map_vmods_rtrn: LazySymbol<unsafe fn(S: *const xcb_xkb_get_map_map_t) -> *mut u8>,
    pub(crate) xcb_xkb_get_map_map_vmods_rtrn_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_map_map_vmods_rtrn_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_map_reply_t, S: *const xcb_xkb_get_map_map_t) -> c_int>,
    pub(crate) xcb_xkb_get_map_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_get_map_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_get_map_reply_t>,
    pub(crate) xcb_xkb_get_map_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, full: u16, partial: u16, first_type: u8, n_types: u8, first_key_sym: xcb_keycode_t, n_key_syms: u8, first_key_action: xcb_keycode_t, n_key_actions: u8, first_key_behavior: xcb_keycode_t, n_key_behaviors: u8, virtual_mods: u16, first_key_explicit: xcb_keycode_t, n_key_explicit: u8, first_mod_map_key: xcb_keycode_t, n_mod_map_keys: u8, first_v_mod_map_key: xcb_keycode_t, n_v_mod_map_keys: u8) -> xcb_xkb_get_map_cookie_t>,
    pub(crate) xcb_xkb_get_named_indicator: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, led_class: xcb_xkb_led_class_spec_t, led_id: xcb_xkb_id_spec_t, indicator: xcb_atom_t) -> xcb_xkb_get_named_indicator_cookie_t>,
    pub(crate) xcb_xkb_get_named_indicator_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_get_named_indicator_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_get_named_indicator_reply_t>,
    pub(crate) xcb_xkb_get_named_indicator_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, led_class: xcb_xkb_led_class_spec_t, led_id: xcb_xkb_id_spec_t, indicator: xcb_atom_t) -> xcb_xkb_get_named_indicator_cookie_t>,
    pub(crate) xcb_xkb_get_names: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, which: u32) -> xcb_xkb_get_names_cookie_t>,
    pub(crate) xcb_xkb_get_names_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_get_names_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_get_names_reply_t>,
    pub(crate) xcb_xkb_get_names_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, which: u32) -> xcb_xkb_get_names_cookie_t>,
    pub(crate) xcb_xkb_get_names_value_list: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t) -> *mut c_void>,
    pub(crate) xcb_xkb_get_names_value_list_alignment_pad: LazySymbol<unsafe fn(S: *const xcb_xkb_get_names_value_list_t) -> *mut u8>,
    pub(crate) xcb_xkb_get_names_value_list_alignment_pad_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_names_value_list_alignment_pad_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> c_int>,
    pub(crate) xcb_xkb_get_names_value_list_groups: LazySymbol<unsafe fn(S: *const xcb_xkb_get_names_value_list_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_get_names_value_list_groups_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_names_value_list_groups_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> c_int>,
    pub(crate) xcb_xkb_get_names_value_list_indicator_names: LazySymbol<unsafe fn(S: *const xcb_xkb_get_names_value_list_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_get_names_value_list_indicator_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_names_value_list_indicator_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> c_int>,
    pub(crate) xcb_xkb_get_names_value_list_key_aliases: LazySymbol<unsafe fn(S: *const xcb_xkb_get_names_value_list_t) -> *mut xcb_xkb_key_alias_t>,
    pub(crate) xcb_xkb_get_names_value_list_key_aliases_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> xcb_xkb_key_alias_iterator_t>,
    pub(crate) xcb_xkb_get_names_value_list_key_aliases_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> c_int>,
    pub(crate) xcb_xkb_get_names_value_list_key_names: LazySymbol<unsafe fn(S: *const xcb_xkb_get_names_value_list_t) -> *mut xcb_xkb_key_name_t>,
    pub(crate) xcb_xkb_get_names_value_list_key_names_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> xcb_xkb_key_name_iterator_t>,
    pub(crate) xcb_xkb_get_names_value_list_key_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> c_int>,
    pub(crate) xcb_xkb_get_names_value_list_kt_level_names: LazySymbol<unsafe fn(S: *const xcb_xkb_get_names_value_list_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_get_names_value_list_kt_level_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_names_value_list_kt_level_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> c_int>,
    pub(crate) xcb_xkb_get_names_value_list_n_levels_per_type: LazySymbol<unsafe fn(S: *const xcb_xkb_get_names_value_list_t) -> *mut u8>,
    pub(crate) xcb_xkb_get_names_value_list_n_levels_per_type_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_names_value_list_n_levels_per_type_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> c_int>,
    pub(crate) xcb_xkb_get_names_value_list_radio_group_names: LazySymbol<unsafe fn(S: *const xcb_xkb_get_names_value_list_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_get_names_value_list_radio_group_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_names_value_list_radio_group_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> c_int>,
    pub(crate) xcb_xkb_get_names_value_list_type_names: LazySymbol<unsafe fn(S: *const xcb_xkb_get_names_value_list_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_get_names_value_list_type_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_names_value_list_type_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> c_int>,
    pub(crate) xcb_xkb_get_names_value_list_virtual_mod_names: LazySymbol<unsafe fn(S: *const xcb_xkb_get_names_value_list_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_get_names_value_list_virtual_mod_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_get_names_value_list_virtual_mod_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_get_names_reply_t, S: *const xcb_xkb_get_names_value_list_t) -> c_int>,
    pub(crate) xcb_xkb_get_state: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t) -> xcb_xkb_get_state_cookie_t>,
    pub(crate) xcb_xkb_get_state_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_get_state_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_get_state_reply_t>,
    pub(crate) xcb_xkb_get_state_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t) -> xcb_xkb_get_state_cookie_t>,
    pub(crate) xcb_xkb_id: LazySymbol<*mut xcb_extension_t>,
    pub(crate) xcb_xkb_id_spec_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_id_spec_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_id_spec_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_id_spec_iterator_t)>,
    pub(crate) xcb_xkb_indicator_map_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_indicator_map_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_indicator_map_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_indicator_map_iterator_t)>,
    pub(crate) xcb_xkb_key_alias_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_alias_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_key_alias_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_alias_iterator_t)>,
    pub(crate) xcb_xkb_key_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_key_mod_map_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_mod_map_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_key_mod_map_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_mod_map_iterator_t)>,
    pub(crate) xcb_xkb_key_name_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_name_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_key_name_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_name_iterator_t)>,
    pub(crate) xcb_xkb_key_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_iterator_t)>,
    pub(crate) xcb_xkb_key_sym_map_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_sym_map_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_key_sym_map_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_sym_map_iterator_t)>,
    pub(crate) xcb_xkb_key_sym_map_syms: LazySymbol<unsafe fn(R: *const xcb_xkb_key_sym_map_t) -> *mut xcb_keysym_t>,
    pub(crate) xcb_xkb_key_sym_map_syms_end: LazySymbol<unsafe fn(R: *const xcb_xkb_key_sym_map_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_key_sym_map_syms_length: LazySymbol<unsafe fn(R: *const xcb_xkb_key_sym_map_t) -> c_int>,
    pub(crate) xcb_xkb_key_type_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_type_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_key_type_map: LazySymbol<unsafe fn(R: *const xcb_xkb_key_type_t) -> *mut xcb_xkb_kt_map_entry_t>,
    pub(crate) xcb_xkb_key_type_map_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_key_type_t) -> xcb_xkb_kt_map_entry_iterator_t>,
    pub(crate) xcb_xkb_key_type_map_length: LazySymbol<unsafe fn(R: *const xcb_xkb_key_type_t) -> c_int>,
    pub(crate) xcb_xkb_key_type_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_type_iterator_t)>,
    pub(crate) xcb_xkb_key_type_preserve: LazySymbol<unsafe fn(R: *const xcb_xkb_key_type_t) -> *mut xcb_xkb_mod_def_t>,
    pub(crate) xcb_xkb_key_type_preserve_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_key_type_t) -> xcb_xkb_mod_def_iterator_t>,
    pub(crate) xcb_xkb_key_type_preserve_length: LazySymbol<unsafe fn(R: *const xcb_xkb_key_type_t) -> c_int>,
    pub(crate) xcb_xkb_key_v_mod_map_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_v_mod_map_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_key_v_mod_map_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_key_v_mod_map_iterator_t)>,
    pub(crate) xcb_xkb_kt_map_entry_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_kt_map_entry_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_kt_map_entry_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_kt_map_entry_iterator_t)>,
    pub(crate) xcb_xkb_kt_set_map_entry_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_kt_set_map_entry_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_kt_set_map_entry_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_kt_set_map_entry_iterator_t)>,
    pub(crate) xcb_xkb_latch_lock_state: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, affect_mod_locks: u8, mod_locks: u8, lock_group: u8, group_lock: u8, affect_mod_latches: u8, latch_group: u8, group_latch: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_latch_lock_state_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, affect_mod_locks: u8, mod_locks: u8, lock_group: u8, group_lock: u8, affect_mod_latches: u8, latch_group: u8, group_latch: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_led_class_spec_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_led_class_spec_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_led_class_spec_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_led_class_spec_iterator_t)>,
    pub(crate) xcb_xkb_list_components: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, max_names: u16) -> xcb_xkb_list_components_cookie_t>,
    pub(crate) xcb_xkb_list_components_compat_maps_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_list_components_reply_t) -> xcb_xkb_listing_iterator_t>,
    pub(crate) xcb_xkb_list_components_compat_maps_length: LazySymbol<unsafe fn(R: *const xcb_xkb_list_components_reply_t) -> c_int>,
    pub(crate) xcb_xkb_list_components_geometries_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_list_components_reply_t) -> xcb_xkb_listing_iterator_t>,
    pub(crate) xcb_xkb_list_components_geometries_length: LazySymbol<unsafe fn(R: *const xcb_xkb_list_components_reply_t) -> c_int>,
    pub(crate) xcb_xkb_list_components_keycodes_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_list_components_reply_t) -> xcb_xkb_listing_iterator_t>,
    pub(crate) xcb_xkb_list_components_keycodes_length: LazySymbol<unsafe fn(R: *const xcb_xkb_list_components_reply_t) -> c_int>,
    pub(crate) xcb_xkb_list_components_keymaps_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_list_components_reply_t) -> xcb_xkb_listing_iterator_t>,
    pub(crate) xcb_xkb_list_components_keymaps_length: LazySymbol<unsafe fn(R: *const xcb_xkb_list_components_reply_t) -> c_int>,
    pub(crate) xcb_xkb_list_components_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_list_components_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_list_components_reply_t>,
    pub(crate) xcb_xkb_list_components_symbols_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_list_components_reply_t) -> xcb_xkb_listing_iterator_t>,
    pub(crate) xcb_xkb_list_components_symbols_length: LazySymbol<unsafe fn(R: *const xcb_xkb_list_components_reply_t) -> c_int>,
    pub(crate) xcb_xkb_list_components_types_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_list_components_reply_t) -> xcb_xkb_listing_iterator_t>,
    pub(crate) xcb_xkb_list_components_types_length: LazySymbol<unsafe fn(R: *const xcb_xkb_list_components_reply_t) -> c_int>,
    pub(crate) xcb_xkb_list_components_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, max_names: u16) -> xcb_xkb_list_components_cookie_t>,
    pub(crate) xcb_xkb_listing_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_listing_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_listing_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_listing_iterator_t)>,
    pub(crate) xcb_xkb_listing_string: LazySymbol<unsafe fn(R: *const xcb_xkb_listing_t) -> *mut xcb_xkb_string8_t>,
    pub(crate) xcb_xkb_listing_string_end: LazySymbol<unsafe fn(R: *const xcb_xkb_listing_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_listing_string_length: LazySymbol<unsafe fn(R: *const xcb_xkb_listing_t) -> c_int>,
    pub(crate) xcb_xkb_lock_behavior_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_lock_behavior_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_lock_behavior_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_lock_behavior_iterator_t)>,
    pub(crate) xcb_xkb_mod_def_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_mod_def_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_mod_def_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_mod_def_iterator_t)>,
    pub(crate) xcb_xkb_outline_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_outline_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_outline_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_outline_iterator_t)>,
    pub(crate) xcb_xkb_outline_points: LazySymbol<unsafe fn(R: *const xcb_xkb_outline_t) -> *mut xcb_point_t>,
    pub(crate) xcb_xkb_outline_points_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_outline_t) -> xcb_point_iterator_t>,
    pub(crate) xcb_xkb_outline_points_length: LazySymbol<unsafe fn(R: *const xcb_xkb_outline_t) -> c_int>,
    pub(crate) xcb_xkb_overlay_behavior_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_overlay_behavior_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_overlay_behavior_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_overlay_behavior_iterator_t)>,
    pub(crate) xcb_xkb_overlay_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_overlay_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_overlay_key_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_overlay_key_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_overlay_key_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_overlay_key_iterator_t)>,
    pub(crate) xcb_xkb_overlay_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_overlay_iterator_t)>,
    pub(crate) xcb_xkb_overlay_row_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_overlay_row_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_overlay_row_keys: LazySymbol<unsafe fn(R: *const xcb_xkb_overlay_row_t) -> *mut xcb_xkb_overlay_key_t>,
    pub(crate) xcb_xkb_overlay_row_keys_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_overlay_row_t) -> xcb_xkb_overlay_key_iterator_t>,
    pub(crate) xcb_xkb_overlay_row_keys_length: LazySymbol<unsafe fn(R: *const xcb_xkb_overlay_row_t) -> c_int>,
    pub(crate) xcb_xkb_overlay_row_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_overlay_row_iterator_t)>,
    pub(crate) xcb_xkb_overlay_rows_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_overlay_t) -> xcb_xkb_overlay_row_iterator_t>,
    pub(crate) xcb_xkb_overlay_rows_length: LazySymbol<unsafe fn(R: *const xcb_xkb_overlay_t) -> c_int>,
    pub(crate) xcb_xkb_per_client_flags: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, change: u32, value: u32, ctrls_to_change: u32, auto_ctrls: u32, auto_ctrls_values: u32) -> xcb_xkb_per_client_flags_cookie_t>,
    pub(crate) xcb_xkb_per_client_flags_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_per_client_flags_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_per_client_flags_reply_t>,
    pub(crate) xcb_xkb_per_client_flags_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, change: u32, value: u32, ctrls_to_change: u32, auto_ctrls: u32, auto_ctrls_values: u32) -> xcb_xkb_per_client_flags_cookie_t>,
    pub(crate) xcb_xkb_permament_lock_behavior_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_permament_lock_behavior_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_permament_lock_behavior_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_permament_lock_behavior_iterator_t)>,
    pub(crate) xcb_xkb_permament_overlay_behavior_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_permament_overlay_behavior_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_permament_overlay_behavior_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_permament_overlay_behavior_iterator_t)>,
    pub(crate) xcb_xkb_permament_radio_group_behavior_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_permament_radio_group_behavior_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_permament_radio_group_behavior_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_permament_radio_group_behavior_iterator_t)>,
    pub(crate) xcb_xkb_radio_group_behavior_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_radio_group_behavior_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_radio_group_behavior_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_radio_group_behavior_iterator_t)>,
    pub(crate) xcb_xkb_row_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_row_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_row_keys: LazySymbol<unsafe fn(R: *const xcb_xkb_row_t) -> *mut xcb_xkb_key_t>,
    pub(crate) xcb_xkb_row_keys_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_row_t) -> xcb_xkb_key_iterator_t>,
    pub(crate) xcb_xkb_row_keys_length: LazySymbol<unsafe fn(R: *const xcb_xkb_row_t) -> c_int>,
    pub(crate) xcb_xkb_row_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_row_iterator_t)>,
    pub(crate) xcb_xkb_sa_action_message_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_action_message_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_action_message_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_action_message_iterator_t)>,
    pub(crate) xcb_xkb_sa_device_btn_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_device_btn_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_device_btn_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_device_btn_iterator_t)>,
    pub(crate) xcb_xkb_sa_device_valuator_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_device_valuator_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_device_valuator_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_device_valuator_iterator_t)>,
    pub(crate) xcb_xkb_sa_iso_lock_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_iso_lock_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_iso_lock_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_iso_lock_iterator_t)>,
    pub(crate) xcb_xkb_sa_latch_group_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_latch_group_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_latch_group_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_latch_group_iterator_t)>,
    pub(crate) xcb_xkb_sa_latch_mods_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_latch_mods_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_latch_mods_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_latch_mods_iterator_t)>,
    pub(crate) xcb_xkb_sa_lock_controls_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_lock_controls_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_lock_controls_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_lock_controls_iterator_t)>,
    pub(crate) xcb_xkb_sa_lock_device_btn_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_lock_device_btn_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_lock_device_btn_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_lock_device_btn_iterator_t)>,
    pub(crate) xcb_xkb_sa_lock_group_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_lock_group_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_lock_group_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_lock_group_iterator_t)>,
    pub(crate) xcb_xkb_sa_lock_mods_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_lock_mods_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_lock_mods_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_lock_mods_iterator_t)>,
    pub(crate) xcb_xkb_sa_lock_ptr_btn_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_lock_ptr_btn_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_lock_ptr_btn_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_lock_ptr_btn_iterator_t)>,
    pub(crate) xcb_xkb_sa_move_ptr_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_move_ptr_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_move_ptr_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_move_ptr_iterator_t)>,
    pub(crate) xcb_xkb_sa_no_action_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_no_action_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_no_action_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_no_action_iterator_t)>,
    pub(crate) xcb_xkb_sa_ptr_btn_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_ptr_btn_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_ptr_btn_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_ptr_btn_iterator_t)>,
    pub(crate) xcb_xkb_sa_redirect_key_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_redirect_key_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_redirect_key_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_redirect_key_iterator_t)>,
    pub(crate) xcb_xkb_sa_set_controls_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_set_controls_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_set_controls_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_set_controls_iterator_t)>,
    pub(crate) xcb_xkb_sa_set_group_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_set_group_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_set_group_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_set_group_iterator_t)>,
    pub(crate) xcb_xkb_sa_set_mods_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_set_mods_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_set_mods_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_set_mods_iterator_t)>,
    pub(crate) xcb_xkb_sa_set_ptr_dflt_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_set_ptr_dflt_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_set_ptr_dflt_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_set_ptr_dflt_iterator_t)>,
    pub(crate) xcb_xkb_sa_switch_screen_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_switch_screen_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_switch_screen_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_switch_screen_iterator_t)>,
    pub(crate) xcb_xkb_sa_terminate_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_terminate_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sa_terminate_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sa_terminate_iterator_t)>,
    pub(crate) xcb_xkb_select_events: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, affect_which: u16, clear: u16, select_all: u16, affect_map: u16, map: u16, details: *const xcb_xkb_select_events_details_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_select_events_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, affect_which: u16, clear: u16, select_all: u16, affect_map: u16, map: u16, details: *const xcb_xkb_select_events_details_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_behavior_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_set_behavior_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_set_behavior_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_set_behavior_iterator_t)>,
    pub(crate) xcb_xkb_set_compat_map: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, recompute_actions: u8, truncate_si: u8, groups: u8, first_si: u16, n_si: u16, si: *const xcb_xkb_sym_interpret_t, group_maps: *const xcb_xkb_mod_def_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_compat_map_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, recompute_actions: u8, truncate_si: u8, groups: u8, first_si: u16, n_si: u16, si: *const xcb_xkb_sym_interpret_t, group_maps: *const xcb_xkb_mod_def_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_controls: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, affect_internal_real_mods: u8, internal_real_mods: u8, affect_ignore_lock_real_mods: u8, ignore_lock_real_mods: u8, affect_internal_virtual_mods: u16, internal_virtual_mods: u16, affect_ignore_lock_virtual_mods: u16, ignore_lock_virtual_mods: u16, mouse_keys_dflt_btn: u8, groups_wrap: u8, access_x_options: u16, affect_enabled_controls: u32, enabled_controls: u32, change_controls: u32, repeat_delay: u16, repeat_interval: u16, slow_keys_delay: u16, debounce_delay: u16, mouse_keys_delay: u16, mouse_keys_interval: u16, mouse_keys_time_to_max: u16, mouse_keys_max_speed: u16, mouse_keys_curve: i16, access_x_timeout: u16, access_x_timeout_mask: u32, access_x_timeout_values: u32, access_x_timeout_options_mask: u16, access_x_timeout_options_values: u16, per_key_repeat: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_controls_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, affect_internal_real_mods: u8, internal_real_mods: u8, affect_ignore_lock_real_mods: u8, ignore_lock_real_mods: u8, affect_internal_virtual_mods: u16, internal_virtual_mods: u16, affect_ignore_lock_virtual_mods: u16, ignore_lock_virtual_mods: u16, mouse_keys_dflt_btn: u8, groups_wrap: u8, access_x_options: u16, affect_enabled_controls: u32, enabled_controls: u32, change_controls: u32, repeat_delay: u16, repeat_interval: u16, slow_keys_delay: u16, debounce_delay: u16, mouse_keys_delay: u16, mouse_keys_interval: u16, mouse_keys_time_to_max: u16, mouse_keys_max_speed: u16, mouse_keys_curve: i16, access_x_timeout: u16, access_x_timeout_mask: u32, access_x_timeout_values: u32, access_x_timeout_options_mask: u16, access_x_timeout_options_values: u16, per_key_repeat: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_debugging_flags: LazySymbol<unsafe fn(c: *mut xcb_connection_t, msg_length: u16, affect_flags: u32, flags: u32, affect_ctrls: u32, ctrls: u32, message: *const xcb_xkb_string8_t) -> xcb_xkb_set_debugging_flags_cookie_t>,
    pub(crate) xcb_xkb_set_debugging_flags_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_set_debugging_flags_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_set_debugging_flags_reply_t>,
    pub(crate) xcb_xkb_set_debugging_flags_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, msg_length: u16, affect_flags: u32, flags: u32, affect_ctrls: u32, ctrls: u32, message: *const xcb_xkb_string8_t) -> xcb_xkb_set_debugging_flags_cookie_t>,
    pub(crate) xcb_xkb_set_device_info: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, first_btn: u8, n_btns: u8, change: u16, n_device_led_f_bs: u16, btn_actions: *const xcb_xkb_action_t, leds: *const xcb_xkb_device_led_info_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_device_info_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, first_btn: u8, n_btns: u8, change: u16, n_device_led_f_bs: u16, btn_actions: *const xcb_xkb_action_t, leds: *const xcb_xkb_device_led_info_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_explicit_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_set_explicit_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_set_explicit_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_set_explicit_iterator_t)>,
    pub(crate) xcb_xkb_set_indicator_map: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, which: u32, maps: *const xcb_xkb_indicator_map_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_indicator_map_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, which: u32, maps: *const xcb_xkb_indicator_map_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_key_type_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_set_key_type_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_set_key_type_entries: LazySymbol<unsafe fn(R: *const xcb_xkb_set_key_type_t) -> *mut xcb_xkb_kt_set_map_entry_t>,
    pub(crate) xcb_xkb_set_key_type_entries_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_set_key_type_t) -> xcb_xkb_kt_set_map_entry_iterator_t>,
    pub(crate) xcb_xkb_set_key_type_entries_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_key_type_t) -> c_int>,
    pub(crate) xcb_xkb_set_key_type_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_set_key_type_iterator_t)>,
    pub(crate) xcb_xkb_set_key_type_preserve_entries: LazySymbol<unsafe fn(R: *const xcb_xkb_set_key_type_t) -> *mut xcb_xkb_kt_set_map_entry_t>,
    pub(crate) xcb_xkb_set_key_type_preserve_entries_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_set_key_type_t) -> xcb_xkb_kt_set_map_entry_iterator_t>,
    pub(crate) xcb_xkb_set_key_type_preserve_entries_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_key_type_t) -> c_int>,
    pub(crate) xcb_xkb_set_map: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, present: u16, flags: u16, min_key_code: xcb_keycode_t, max_key_code: xcb_keycode_t, first_type: u8, n_types: u8, first_key_sym: xcb_keycode_t, n_key_syms: u8, total_syms: u16, first_key_action: xcb_keycode_t, n_key_actions: u8, total_actions: u16, first_key_behavior: xcb_keycode_t, n_key_behaviors: u8, total_key_behaviors: u8, first_key_explicit: xcb_keycode_t, n_key_explicit: u8, total_key_explicit: u8, first_mod_map_key: xcb_keycode_t, n_mod_map_keys: u8, total_mod_map_keys: u8, first_v_mod_map_key: xcb_keycode_t, n_v_mod_map_keys: u8, total_v_mod_map_keys: u8, virtual_mods: u16, values: *const xcb_xkb_set_map_values_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_map_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, present: u16, flags: u16, min_key_code: xcb_keycode_t, max_key_code: xcb_keycode_t, first_type: u8, n_types: u8, first_key_sym: xcb_keycode_t, n_key_syms: u8, total_syms: u16, first_key_action: xcb_keycode_t, n_key_actions: u8, total_actions: u16, first_key_behavior: xcb_keycode_t, n_key_behaviors: u8, total_key_behaviors: u8, first_key_explicit: xcb_keycode_t, n_key_explicit: u8, total_key_explicit: u8, first_mod_map_key: xcb_keycode_t, n_mod_map_keys: u8, total_mod_map_keys: u8, first_v_mod_map_key: xcb_keycode_t, n_v_mod_map_keys: u8, total_v_mod_map_keys: u8, virtual_mods: u16, values: *const xcb_xkb_set_map_values_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_map_values_actions: LazySymbol<unsafe fn(S: *const xcb_xkb_set_map_values_t) -> *mut xcb_xkb_action_t>,
    pub(crate) xcb_xkb_set_map_values_actions_count: LazySymbol<unsafe fn(S: *const xcb_xkb_set_map_values_t) -> *mut u8>,
    pub(crate) xcb_xkb_set_map_values_actions_count_end: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_set_map_values_actions_count_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_map_values_actions_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> xcb_xkb_action_iterator_t>,
    pub(crate) xcb_xkb_set_map_values_actions_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_map_values_behaviors: LazySymbol<unsafe fn(S: *const xcb_xkb_set_map_values_t) -> *mut xcb_xkb_set_behavior_t>,
    pub(crate) xcb_xkb_set_map_values_behaviors_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> xcb_xkb_set_behavior_iterator_t>,
    pub(crate) xcb_xkb_set_map_values_behaviors_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_map_values_explicit: LazySymbol<unsafe fn(S: *const xcb_xkb_set_map_values_t) -> *mut xcb_xkb_set_explicit_t>,
    pub(crate) xcb_xkb_set_map_values_explicit_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> xcb_xkb_set_explicit_iterator_t>,
    pub(crate) xcb_xkb_set_map_values_explicit_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_map_values_modmap: LazySymbol<unsafe fn(S: *const xcb_xkb_set_map_values_t) -> *mut xcb_xkb_key_mod_map_t>,
    pub(crate) xcb_xkb_set_map_values_modmap_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> xcb_xkb_key_mod_map_iterator_t>,
    pub(crate) xcb_xkb_set_map_values_modmap_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_map_values_syms_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> xcb_xkb_key_sym_map_iterator_t>,
    pub(crate) xcb_xkb_set_map_values_syms_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_map_values_types_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> xcb_xkb_set_key_type_iterator_t>,
    pub(crate) xcb_xkb_set_map_values_types_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_map_values_vmodmap: LazySymbol<unsafe fn(S: *const xcb_xkb_set_map_values_t) -> *mut xcb_xkb_key_v_mod_map_t>,
    pub(crate) xcb_xkb_set_map_values_vmodmap_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> xcb_xkb_key_v_mod_map_iterator_t>,
    pub(crate) xcb_xkb_set_map_values_vmodmap_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_map_values_vmods: LazySymbol<unsafe fn(S: *const xcb_xkb_set_map_values_t) -> *mut u8>,
    pub(crate) xcb_xkb_set_map_values_vmods_end: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_set_map_values_vmods_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_map_request_t, S: *const xcb_xkb_set_map_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_named_indicator: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, led_class: xcb_xkb_led_class_spec_t, led_id: xcb_xkb_id_spec_t, indicator: xcb_atom_t, set_state: u8, on: u8, set_map: u8, create_map: u8, map_flags: u8, map_which_groups: u8, map_groups: u8, map_which_mods: u8, map_real_mods: u8, map_vmods: u16, map_ctrls: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_named_indicator_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, led_class: xcb_xkb_led_class_spec_t, led_id: xcb_xkb_id_spec_t, indicator: xcb_atom_t, set_state: u8, on: u8, set_map: u8, create_map: u8, map_flags: u8, map_which_groups: u8, map_groups: u8, map_which_mods: u8, map_real_mods: u8, map_vmods: u16, map_ctrls: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_names: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, virtual_mods: u16, which: u32, first_type: u8, n_types: u8, first_kt_levelt: u8, n_kt_levels: u8, indicators: u32, group_names: u8, n_radio_groups: u8, first_key: xcb_keycode_t, n_keys: u8, n_key_aliases: u8, total_kt_level_names: u16, values: *const xcb_xkb_set_names_values_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_names_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_spec: xcb_xkb_device_spec_t, virtual_mods: u16, which: u32, first_type: u8, n_types: u8, first_kt_levelt: u8, n_kt_levels: u8, indicators: u32, group_names: u8, n_radio_groups: u8, first_key: xcb_keycode_t, n_keys: u8, n_key_aliases: u8, total_kt_level_names: u16, values: *const xcb_xkb_set_names_values_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xkb_set_names_values_groups: LazySymbol<unsafe fn(S: *const xcb_xkb_set_names_values_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_set_names_values_groups_end: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_set_names_values_groups_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_names_values_indicator_names: LazySymbol<unsafe fn(S: *const xcb_xkb_set_names_values_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_set_names_values_indicator_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_set_names_values_indicator_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_names_values_key_aliases: LazySymbol<unsafe fn(S: *const xcb_xkb_set_names_values_t) -> *mut xcb_xkb_key_alias_t>,
    pub(crate) xcb_xkb_set_names_values_key_aliases_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> xcb_xkb_key_alias_iterator_t>,
    pub(crate) xcb_xkb_set_names_values_key_aliases_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_names_values_key_names: LazySymbol<unsafe fn(S: *const xcb_xkb_set_names_values_t) -> *mut xcb_xkb_key_name_t>,
    pub(crate) xcb_xkb_set_names_values_key_names_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> xcb_xkb_key_name_iterator_t>,
    pub(crate) xcb_xkb_set_names_values_key_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_names_values_kt_level_names: LazySymbol<unsafe fn(S: *const xcb_xkb_set_names_values_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_set_names_values_kt_level_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_set_names_values_kt_level_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_names_values_n_levels_per_type: LazySymbol<unsafe fn(S: *const xcb_xkb_set_names_values_t) -> *mut u8>,
    pub(crate) xcb_xkb_set_names_values_n_levels_per_type_end: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_set_names_values_n_levels_per_type_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_names_values_radio_group_names: LazySymbol<unsafe fn(S: *const xcb_xkb_set_names_values_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_set_names_values_radio_group_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_set_names_values_radio_group_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_names_values_type_names: LazySymbol<unsafe fn(S: *const xcb_xkb_set_names_values_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_set_names_values_type_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_set_names_values_type_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> c_int>,
    pub(crate) xcb_xkb_set_names_values_virtual_mod_names: LazySymbol<unsafe fn(S: *const xcb_xkb_set_names_values_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xkb_set_names_values_virtual_mod_names_end: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_set_names_values_virtual_mod_names_length: LazySymbol<unsafe fn(R: *const xcb_xkb_set_names_request_t, S: *const xcb_xkb_set_names_values_t) -> c_int>,
    pub(crate) xcb_xkb_shape_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_shape_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_shape_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_shape_iterator_t)>,
    pub(crate) xcb_xkb_shape_outlines_iterator: LazySymbol<unsafe fn(R: *const xcb_xkb_shape_t) -> xcb_xkb_outline_iterator_t>,
    pub(crate) xcb_xkb_shape_outlines_length: LazySymbol<unsafe fn(R: *const xcb_xkb_shape_t) -> c_int>,
    pub(crate) xcb_xkb_si_action_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_si_action_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_si_action_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_si_action_iterator_t)>,
    pub(crate) xcb_xkb_string8_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_string8_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_string8_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_string8_iterator_t)>,
    pub(crate) xcb_xkb_sym_interpret_end: LazySymbol<unsafe fn(i: *mut xcb_xkb_sym_interpret_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xkb_sym_interpret_next: LazySymbol<unsafe fn(i: *mut xcb_xkb_sym_interpret_iterator_t)>,
    pub(crate) xcb_xkb_use_extension: LazySymbol<unsafe fn(c: *mut xcb_connection_t, wanted_major: u16, wanted_minor: u16) -> xcb_xkb_use_extension_cookie_t>,
    pub(crate) xcb_xkb_use_extension_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xkb_use_extension_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xkb_use_extension_reply_t>,
    pub(crate) xcb_xkb_use_extension_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, wanted_major: u16, wanted_minor: u16) -> xcb_xkb_use_extension_cookie_t>,
}
