use crate::ffi::*;
use crate::lazy::*;
use libloading::{Error, Library};
use std::os::raw::*;

#[rustfmt::skip]
pub struct XcbGlx {
    pub(crate) lib: NamedLibrary,
    pub(crate) xcb_glx_are_textures_resident: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, n: i32, textures: *const u32) -> xcb_glx_are_textures_resident_cookie_t>,
    pub(crate) xcb_glx_are_textures_resident_data: LazySymbol<unsafe fn(R: *const xcb_glx_are_textures_resident_reply_t) -> *mut u8>,
    pub(crate) xcb_glx_are_textures_resident_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_are_textures_resident_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_are_textures_resident_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_are_textures_resident_reply_t) -> c_int>,
    pub(crate) xcb_glx_are_textures_resident_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_are_textures_resident_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_are_textures_resident_reply_t>,
    pub(crate) xcb_glx_are_textures_resident_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, n: i32, textures: *const u32) -> xcb_glx_are_textures_resident_cookie_t>,
    pub(crate) xcb_glx_bool32_end: LazySymbol<unsafe fn(i: *mut xcb_glx_bool32_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_bool32_next: LazySymbol<unsafe fn(i: *mut xcb_glx_bool32_iterator_t)>,
    pub(crate) xcb_glx_change_drawable_attributes: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_glx_drawable_t, num_attribs: u32, attribs: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_change_drawable_attributes_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_glx_drawable_t, num_attribs: u32, attribs: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_client_info: LazySymbol<unsafe fn(c: *mut xcb_connection_t, major_version: u32, minor_version: u32, str_len: u32, string: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_client_info_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, major_version: u32, minor_version: u32, str_len: u32, string: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_context_end: LazySymbol<unsafe fn(i: *mut xcb_glx_context_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_context_next: LazySymbol<unsafe fn(i: *mut xcb_glx_context_iterator_t)>,
    pub(crate) xcb_glx_context_tag_end: LazySymbol<unsafe fn(i: *mut xcb_glx_context_tag_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_context_tag_next: LazySymbol<unsafe fn(i: *mut xcb_glx_context_tag_iterator_t)>,
    pub(crate) xcb_glx_copy_context: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src: xcb_glx_context_t, dest: xcb_glx_context_t, mask: u32, src_context_tag: xcb_glx_context_tag_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_copy_context_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src: xcb_glx_context_t, dest: xcb_glx_context_t, mask: u32, src_context_tag: xcb_glx_context_tag_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_context: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context: xcb_glx_context_t, visual: xcb_visualid_t, screen: u32, share_list: xcb_glx_context_t, is_direct: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_context_attribs_arb: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context: xcb_glx_context_t, fbconfig: xcb_glx_fbconfig_t, screen: u32, share_list: xcb_glx_context_t, is_direct: u8, num_attribs: u32, attribs: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_context_attribs_arb_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context: xcb_glx_context_t, fbconfig: xcb_glx_fbconfig_t, screen: u32, share_list: xcb_glx_context_t, is_direct: u8, num_attribs: u32, attribs: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_context_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context: xcb_glx_context_t, visual: xcb_visualid_t, screen: u32, share_list: xcb_glx_context_t, is_direct: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_glx_pixmap: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, visual: xcb_visualid_t, pixmap: xcb_pixmap_t, glx_pixmap: xcb_glx_pixmap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_glx_pixmap_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, visual: xcb_visualid_t, pixmap: xcb_pixmap_t, glx_pixmap: xcb_glx_pixmap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_new_context: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context: xcb_glx_context_t, fbconfig: xcb_glx_fbconfig_t, screen: u32, render_type: u32, share_list: xcb_glx_context_t, is_direct: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_new_context_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context: xcb_glx_context_t, fbconfig: xcb_glx_fbconfig_t, screen: u32, render_type: u32, share_list: xcb_glx_context_t, is_direct: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_pbuffer: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, fbconfig: xcb_glx_fbconfig_t, pbuffer: xcb_glx_pbuffer_t, num_attribs: u32, attribs: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_pbuffer_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, fbconfig: xcb_glx_fbconfig_t, pbuffer: xcb_glx_pbuffer_t, num_attribs: u32, attribs: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_pixmap: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, fbconfig: xcb_glx_fbconfig_t, pixmap: xcb_pixmap_t, glx_pixmap: xcb_glx_pixmap_t, num_attribs: u32, attribs: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_pixmap_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, fbconfig: xcb_glx_fbconfig_t, pixmap: xcb_pixmap_t, glx_pixmap: xcb_glx_pixmap_t, num_attribs: u32, attribs: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_window: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, fbconfig: xcb_glx_fbconfig_t, window: xcb_window_t, glx_window: xcb_glx_window_t, num_attribs: u32, attribs: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_create_window_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, fbconfig: xcb_glx_fbconfig_t, window: xcb_window_t, glx_window: xcb_glx_window_t, num_attribs: u32, attribs: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_delete_lists: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, list: u32, range: i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_delete_lists_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, list: u32, range: i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_delete_queries_arb: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, n: i32, ids: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_delete_queries_arb_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, n: i32, ids: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_delete_textures: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, n: i32, textures: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_delete_textures_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, n: i32, textures: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_delete_window: LazySymbol<unsafe fn(c: *mut xcb_connection_t, glxwindow: xcb_glx_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_delete_window_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, glxwindow: xcb_glx_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_destroy_context: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context: xcb_glx_context_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_destroy_context_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context: xcb_glx_context_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_destroy_glx_pixmap: LazySymbol<unsafe fn(c: *mut xcb_connection_t, glx_pixmap: xcb_glx_pixmap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_destroy_glx_pixmap_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, glx_pixmap: xcb_glx_pixmap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_destroy_pbuffer: LazySymbol<unsafe fn(c: *mut xcb_connection_t, pbuffer: xcb_glx_pbuffer_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_destroy_pbuffer_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, pbuffer: xcb_glx_pbuffer_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_destroy_pixmap: LazySymbol<unsafe fn(c: *mut xcb_connection_t, glx_pixmap: xcb_glx_pixmap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_destroy_pixmap_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, glx_pixmap: xcb_glx_pixmap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_drawable_end: LazySymbol<unsafe fn(i: *mut xcb_glx_drawable_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_drawable_next: LazySymbol<unsafe fn(i: *mut xcb_glx_drawable_iterator_t)>,
    pub(crate) xcb_glx_end_list: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_end_list_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_fbconfig_end: LazySymbol<unsafe fn(i: *mut xcb_glx_fbconfig_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_fbconfig_next: LazySymbol<unsafe fn(i: *mut xcb_glx_fbconfig_iterator_t)>,
    pub(crate) xcb_glx_feedback_buffer: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, size: i32, type_: i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_feedback_buffer_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, size: i32, type_: i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_finish: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t) -> xcb_glx_finish_cookie_t>,
    pub(crate) xcb_glx_finish_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_finish_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_finish_reply_t>,
    pub(crate) xcb_glx_finish_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t) -> xcb_glx_finish_cookie_t>,
    pub(crate) xcb_glx_float32_end: LazySymbol<unsafe fn(i: *mut xcb_glx_float32_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_float32_next: LazySymbol<unsafe fn(i: *mut xcb_glx_float32_iterator_t)>,
    pub(crate) xcb_glx_float64_end: LazySymbol<unsafe fn(i: *mut xcb_glx_float64_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_float64_next: LazySymbol<unsafe fn(i: *mut xcb_glx_float64_iterator_t)>,
    pub(crate) xcb_glx_flush: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_flush_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_gen_lists: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, range: i32) -> xcb_glx_gen_lists_cookie_t>,
    pub(crate) xcb_glx_gen_lists_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_gen_lists_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_gen_lists_reply_t>,
    pub(crate) xcb_glx_gen_lists_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, range: i32) -> xcb_glx_gen_lists_cookie_t>,
    pub(crate) xcb_glx_gen_queries_arb: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, n: i32) -> xcb_glx_gen_queries_arb_cookie_t>,
    pub(crate) xcb_glx_gen_queries_arb_data: LazySymbol<unsafe fn(R: *const xcb_glx_gen_queries_arb_reply_t) -> *mut u32>,
    pub(crate) xcb_glx_gen_queries_arb_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_gen_queries_arb_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_gen_queries_arb_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_gen_queries_arb_reply_t) -> c_int>,
    pub(crate) xcb_glx_gen_queries_arb_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_gen_queries_arb_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_gen_queries_arb_reply_t>,
    pub(crate) xcb_glx_gen_queries_arb_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, n: i32) -> xcb_glx_gen_queries_arb_cookie_t>,
    pub(crate) xcb_glx_gen_textures: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, n: i32) -> xcb_glx_gen_textures_cookie_t>,
    pub(crate) xcb_glx_gen_textures_data: LazySymbol<unsafe fn(R: *const xcb_glx_gen_textures_reply_t) -> *mut u32>,
    pub(crate) xcb_glx_gen_textures_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_gen_textures_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_gen_textures_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_gen_textures_reply_t) -> c_int>,
    pub(crate) xcb_glx_gen_textures_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_gen_textures_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_gen_textures_reply_t>,
    pub(crate) xcb_glx_gen_textures_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, n: i32) -> xcb_glx_gen_textures_cookie_t>,
    pub(crate) xcb_glx_get_booleanv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, pname: i32) -> xcb_glx_get_booleanv_cookie_t>,
    pub(crate) xcb_glx_get_booleanv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_booleanv_reply_t) -> *mut u8>,
    pub(crate) xcb_glx_get_booleanv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_booleanv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_booleanv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_booleanv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_booleanv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_booleanv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_booleanv_reply_t>,
    pub(crate) xcb_glx_get_booleanv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, pname: i32) -> xcb_glx_get_booleanv_cookie_t>,
    pub(crate) xcb_glx_get_clip_plane: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, plane: i32) -> xcb_glx_get_clip_plane_cookie_t>,
    pub(crate) xcb_glx_get_clip_plane_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_clip_plane_reply_t) -> *mut xcb_glx_float64_t>,
    pub(crate) xcb_glx_get_clip_plane_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_clip_plane_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_clip_plane_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_clip_plane_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_clip_plane_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_clip_plane_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_clip_plane_reply_t>,
    pub(crate) xcb_glx_get_clip_plane_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, plane: i32) -> xcb_glx_get_clip_plane_cookie_t>,
    pub(crate) xcb_glx_get_color_table: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, format: u32, type_: u32, swap_bytes: u8) -> xcb_glx_get_color_table_cookie_t>,
    pub(crate) xcb_glx_get_color_table_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_color_table_reply_t) -> *mut u8>,
    pub(crate) xcb_glx_get_color_table_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_color_table_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_color_table_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_color_table_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_color_table_parameterfv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_color_table_parameterfv_cookie_t>,
    pub(crate) xcb_glx_get_color_table_parameterfv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_color_table_parameterfv_reply_t) -> *mut xcb_glx_float32_t>,
    pub(crate) xcb_glx_get_color_table_parameterfv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_color_table_parameterfv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_color_table_parameterfv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_color_table_parameterfv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_color_table_parameterfv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_color_table_parameterfv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_color_table_parameterfv_reply_t>,
    pub(crate) xcb_glx_get_color_table_parameterfv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_color_table_parameterfv_cookie_t>,
    pub(crate) xcb_glx_get_color_table_parameteriv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_color_table_parameteriv_cookie_t>,
    pub(crate) xcb_glx_get_color_table_parameteriv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_color_table_parameteriv_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_color_table_parameteriv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_color_table_parameteriv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_color_table_parameteriv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_color_table_parameteriv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_color_table_parameteriv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_color_table_parameteriv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_color_table_parameteriv_reply_t>,
    pub(crate) xcb_glx_get_color_table_parameteriv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_color_table_parameteriv_cookie_t>,
    pub(crate) xcb_glx_get_color_table_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_color_table_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_color_table_reply_t>,
    pub(crate) xcb_glx_get_color_table_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, format: u32, type_: u32, swap_bytes: u8) -> xcb_glx_get_color_table_cookie_t>,
    pub(crate) xcb_glx_get_compressed_tex_image_arb: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, level: i32) -> xcb_glx_get_compressed_tex_image_arb_cookie_t>,
    pub(crate) xcb_glx_get_compressed_tex_image_arb_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_compressed_tex_image_arb_reply_t) -> *mut u8>,
    pub(crate) xcb_glx_get_compressed_tex_image_arb_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_compressed_tex_image_arb_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_compressed_tex_image_arb_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_compressed_tex_image_arb_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_compressed_tex_image_arb_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_compressed_tex_image_arb_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_compressed_tex_image_arb_reply_t>,
    pub(crate) xcb_glx_get_compressed_tex_image_arb_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, level: i32) -> xcb_glx_get_compressed_tex_image_arb_cookie_t>,
    pub(crate) xcb_glx_get_convolution_filter: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, format: u32, type_: u32, swap_bytes: u8) -> xcb_glx_get_convolution_filter_cookie_t>,
    pub(crate) xcb_glx_get_convolution_filter_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_convolution_filter_reply_t) -> *mut u8>,
    pub(crate) xcb_glx_get_convolution_filter_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_convolution_filter_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_convolution_filter_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_convolution_filter_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_convolution_filter_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_convolution_filter_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_convolution_filter_reply_t>,
    pub(crate) xcb_glx_get_convolution_filter_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, format: u32, type_: u32, swap_bytes: u8) -> xcb_glx_get_convolution_filter_cookie_t>,
    pub(crate) xcb_glx_get_convolution_parameterfv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_convolution_parameterfv_cookie_t>,
    pub(crate) xcb_glx_get_convolution_parameterfv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_convolution_parameterfv_reply_t) -> *mut xcb_glx_float32_t>,
    pub(crate) xcb_glx_get_convolution_parameterfv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_convolution_parameterfv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_convolution_parameterfv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_convolution_parameterfv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_convolution_parameterfv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_convolution_parameterfv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_convolution_parameterfv_reply_t>,
    pub(crate) xcb_glx_get_convolution_parameterfv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_convolution_parameterfv_cookie_t>,
    pub(crate) xcb_glx_get_convolution_parameteriv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_convolution_parameteriv_cookie_t>,
    pub(crate) xcb_glx_get_convolution_parameteriv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_convolution_parameteriv_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_convolution_parameteriv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_convolution_parameteriv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_convolution_parameteriv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_convolution_parameteriv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_convolution_parameteriv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_convolution_parameteriv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_convolution_parameteriv_reply_t>,
    pub(crate) xcb_glx_get_convolution_parameteriv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_convolution_parameteriv_cookie_t>,
    pub(crate) xcb_glx_get_doublev: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, pname: u32) -> xcb_glx_get_doublev_cookie_t>,
    pub(crate) xcb_glx_get_doublev_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_doublev_reply_t) -> *mut xcb_glx_float64_t>,
    pub(crate) xcb_glx_get_doublev_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_doublev_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_doublev_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_doublev_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_doublev_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_doublev_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_doublev_reply_t>,
    pub(crate) xcb_glx_get_doublev_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, pname: u32) -> xcb_glx_get_doublev_cookie_t>,
    pub(crate) xcb_glx_get_drawable_attributes: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_glx_drawable_t) -> xcb_glx_get_drawable_attributes_cookie_t>,
    pub(crate) xcb_glx_get_drawable_attributes_attribs: LazySymbol<unsafe fn(R: *const xcb_glx_get_drawable_attributes_reply_t) -> *mut u32>,
    pub(crate) xcb_glx_get_drawable_attributes_attribs_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_drawable_attributes_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_drawable_attributes_attribs_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_drawable_attributes_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_drawable_attributes_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_drawable_attributes_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_drawable_attributes_reply_t>,
    pub(crate) xcb_glx_get_drawable_attributes_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_glx_drawable_t) -> xcb_glx_get_drawable_attributes_cookie_t>,
    pub(crate) xcb_glx_get_error: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t) -> xcb_glx_get_error_cookie_t>,
    pub(crate) xcb_glx_get_error_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_error_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_error_reply_t>,
    pub(crate) xcb_glx_get_error_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t) -> xcb_glx_get_error_cookie_t>,
    pub(crate) xcb_glx_get_fb_configs: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_glx_get_fb_configs_cookie_t>,
    pub(crate) xcb_glx_get_fb_configs_property_list: LazySymbol<unsafe fn(R: *const xcb_glx_get_fb_configs_reply_t) -> *mut u32>,
    pub(crate) xcb_glx_get_fb_configs_property_list_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_fb_configs_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_fb_configs_property_list_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_fb_configs_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_fb_configs_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_fb_configs_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_fb_configs_reply_t>,
    pub(crate) xcb_glx_get_fb_configs_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_glx_get_fb_configs_cookie_t>,
    pub(crate) xcb_glx_get_floatv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, pname: u32) -> xcb_glx_get_floatv_cookie_t>,
    pub(crate) xcb_glx_get_floatv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_floatv_reply_t) -> *mut xcb_glx_float32_t>,
    pub(crate) xcb_glx_get_floatv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_floatv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_floatv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_floatv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_floatv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_floatv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_floatv_reply_t>,
    pub(crate) xcb_glx_get_floatv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, pname: u32) -> xcb_glx_get_floatv_cookie_t>,
    pub(crate) xcb_glx_get_histogram: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, format: u32, type_: u32, swap_bytes: u8, reset: u8) -> xcb_glx_get_histogram_cookie_t>,
    pub(crate) xcb_glx_get_histogram_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_histogram_reply_t) -> *mut u8>,
    pub(crate) xcb_glx_get_histogram_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_histogram_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_histogram_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_histogram_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_histogram_parameterfv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_histogram_parameterfv_cookie_t>,
    pub(crate) xcb_glx_get_histogram_parameterfv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_histogram_parameterfv_reply_t) -> *mut xcb_glx_float32_t>,
    pub(crate) xcb_glx_get_histogram_parameterfv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_histogram_parameterfv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_histogram_parameterfv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_histogram_parameterfv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_histogram_parameterfv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_histogram_parameterfv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_histogram_parameterfv_reply_t>,
    pub(crate) xcb_glx_get_histogram_parameterfv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_histogram_parameterfv_cookie_t>,
    pub(crate) xcb_glx_get_histogram_parameteriv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_histogram_parameteriv_cookie_t>,
    pub(crate) xcb_glx_get_histogram_parameteriv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_histogram_parameteriv_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_histogram_parameteriv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_histogram_parameteriv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_histogram_parameteriv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_histogram_parameteriv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_histogram_parameteriv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_histogram_parameteriv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_histogram_parameteriv_reply_t>,
    pub(crate) xcb_glx_get_histogram_parameteriv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_histogram_parameteriv_cookie_t>,
    pub(crate) xcb_glx_get_histogram_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_histogram_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_histogram_reply_t>,
    pub(crate) xcb_glx_get_histogram_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, format: u32, type_: u32, swap_bytes: u8, reset: u8) -> xcb_glx_get_histogram_cookie_t>,
    pub(crate) xcb_glx_get_integerv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, pname: u32) -> xcb_glx_get_integerv_cookie_t>,
    pub(crate) xcb_glx_get_integerv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_integerv_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_integerv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_integerv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_integerv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_integerv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_integerv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_integerv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_integerv_reply_t>,
    pub(crate) xcb_glx_get_integerv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, pname: u32) -> xcb_glx_get_integerv_cookie_t>,
    pub(crate) xcb_glx_get_lightfv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, light: u32, pname: u32) -> xcb_glx_get_lightfv_cookie_t>,
    pub(crate) xcb_glx_get_lightfv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_lightfv_reply_t) -> *mut xcb_glx_float32_t>,
    pub(crate) xcb_glx_get_lightfv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_lightfv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_lightfv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_lightfv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_lightfv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_lightfv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_lightfv_reply_t>,
    pub(crate) xcb_glx_get_lightfv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, light: u32, pname: u32) -> xcb_glx_get_lightfv_cookie_t>,
    pub(crate) xcb_glx_get_lightiv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, light: u32, pname: u32) -> xcb_glx_get_lightiv_cookie_t>,
    pub(crate) xcb_glx_get_lightiv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_lightiv_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_lightiv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_lightiv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_lightiv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_lightiv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_lightiv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_lightiv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_lightiv_reply_t>,
    pub(crate) xcb_glx_get_lightiv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, light: u32, pname: u32) -> xcb_glx_get_lightiv_cookie_t>,
    pub(crate) xcb_glx_get_mapdv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, query: u32) -> xcb_glx_get_mapdv_cookie_t>,
    pub(crate) xcb_glx_get_mapdv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_mapdv_reply_t) -> *mut xcb_glx_float64_t>,
    pub(crate) xcb_glx_get_mapdv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_mapdv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_mapdv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_mapdv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_mapdv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_mapdv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_mapdv_reply_t>,
    pub(crate) xcb_glx_get_mapdv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, query: u32) -> xcb_glx_get_mapdv_cookie_t>,
    pub(crate) xcb_glx_get_mapfv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, query: u32) -> xcb_glx_get_mapfv_cookie_t>,
    pub(crate) xcb_glx_get_mapfv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_mapfv_reply_t) -> *mut xcb_glx_float32_t>,
    pub(crate) xcb_glx_get_mapfv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_mapfv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_mapfv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_mapfv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_mapfv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_mapfv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_mapfv_reply_t>,
    pub(crate) xcb_glx_get_mapfv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, query: u32) -> xcb_glx_get_mapfv_cookie_t>,
    pub(crate) xcb_glx_get_mapiv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, query: u32) -> xcb_glx_get_mapiv_cookie_t>,
    pub(crate) xcb_glx_get_mapiv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_mapiv_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_mapiv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_mapiv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_mapiv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_mapiv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_mapiv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_mapiv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_mapiv_reply_t>,
    pub(crate) xcb_glx_get_mapiv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, query: u32) -> xcb_glx_get_mapiv_cookie_t>,
    pub(crate) xcb_glx_get_materialfv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, face: u32, pname: u32) -> xcb_glx_get_materialfv_cookie_t>,
    pub(crate) xcb_glx_get_materialfv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_materialfv_reply_t) -> *mut xcb_glx_float32_t>,
    pub(crate) xcb_glx_get_materialfv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_materialfv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_materialfv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_materialfv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_materialfv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_materialfv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_materialfv_reply_t>,
    pub(crate) xcb_glx_get_materialfv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, face: u32, pname: u32) -> xcb_glx_get_materialfv_cookie_t>,
    pub(crate) xcb_glx_get_materialiv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, face: u32, pname: u32) -> xcb_glx_get_materialiv_cookie_t>,
    pub(crate) xcb_glx_get_materialiv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_materialiv_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_materialiv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_materialiv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_materialiv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_materialiv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_materialiv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_materialiv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_materialiv_reply_t>,
    pub(crate) xcb_glx_get_materialiv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, face: u32, pname: u32) -> xcb_glx_get_materialiv_cookie_t>,
    pub(crate) xcb_glx_get_minmax: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, format: u32, type_: u32, swap_bytes: u8, reset: u8) -> xcb_glx_get_minmax_cookie_t>,
    pub(crate) xcb_glx_get_minmax_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_minmax_reply_t) -> *mut u8>,
    pub(crate) xcb_glx_get_minmax_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_minmax_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_minmax_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_minmax_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_minmax_parameterfv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_minmax_parameterfv_cookie_t>,
    pub(crate) xcb_glx_get_minmax_parameterfv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_minmax_parameterfv_reply_t) -> *mut xcb_glx_float32_t>,
    pub(crate) xcb_glx_get_minmax_parameterfv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_minmax_parameterfv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_minmax_parameterfv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_minmax_parameterfv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_minmax_parameterfv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_minmax_parameterfv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_minmax_parameterfv_reply_t>,
    pub(crate) xcb_glx_get_minmax_parameterfv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_minmax_parameterfv_cookie_t>,
    pub(crate) xcb_glx_get_minmax_parameteriv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_minmax_parameteriv_cookie_t>,
    pub(crate) xcb_glx_get_minmax_parameteriv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_minmax_parameteriv_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_minmax_parameteriv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_minmax_parameteriv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_minmax_parameteriv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_minmax_parameteriv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_minmax_parameteriv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_minmax_parameteriv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_minmax_parameteriv_reply_t>,
    pub(crate) xcb_glx_get_minmax_parameteriv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_minmax_parameteriv_cookie_t>,
    pub(crate) xcb_glx_get_minmax_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_minmax_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_minmax_reply_t>,
    pub(crate) xcb_glx_get_minmax_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, format: u32, type_: u32, swap_bytes: u8, reset: u8) -> xcb_glx_get_minmax_cookie_t>,
    pub(crate) xcb_glx_get_pixel_mapfv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, map: u32) -> xcb_glx_get_pixel_mapfv_cookie_t>,
    pub(crate) xcb_glx_get_pixel_mapfv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_pixel_mapfv_reply_t) -> *mut xcb_glx_float32_t>,
    pub(crate) xcb_glx_get_pixel_mapfv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_pixel_mapfv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_pixel_mapfv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_pixel_mapfv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_pixel_mapfv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_pixel_mapfv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_pixel_mapfv_reply_t>,
    pub(crate) xcb_glx_get_pixel_mapfv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, map: u32) -> xcb_glx_get_pixel_mapfv_cookie_t>,
    pub(crate) xcb_glx_get_pixel_mapuiv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, map: u32) -> xcb_glx_get_pixel_mapuiv_cookie_t>,
    pub(crate) xcb_glx_get_pixel_mapuiv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_pixel_mapuiv_reply_t) -> *mut u32>,
    pub(crate) xcb_glx_get_pixel_mapuiv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_pixel_mapuiv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_pixel_mapuiv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_pixel_mapuiv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_pixel_mapuiv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_pixel_mapuiv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_pixel_mapuiv_reply_t>,
    pub(crate) xcb_glx_get_pixel_mapuiv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, map: u32) -> xcb_glx_get_pixel_mapuiv_cookie_t>,
    pub(crate) xcb_glx_get_pixel_mapusv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, map: u32) -> xcb_glx_get_pixel_mapusv_cookie_t>,
    pub(crate) xcb_glx_get_pixel_mapusv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_pixel_mapusv_reply_t) -> *mut u16>,
    pub(crate) xcb_glx_get_pixel_mapusv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_pixel_mapusv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_pixel_mapusv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_pixel_mapusv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_pixel_mapusv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_pixel_mapusv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_pixel_mapusv_reply_t>,
    pub(crate) xcb_glx_get_pixel_mapusv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, map: u32) -> xcb_glx_get_pixel_mapusv_cookie_t>,
    pub(crate) xcb_glx_get_polygon_stipple: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, lsb_first: u8) -> xcb_glx_get_polygon_stipple_cookie_t>,
    pub(crate) xcb_glx_get_polygon_stipple_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_polygon_stipple_reply_t) -> *mut u8>,
    pub(crate) xcb_glx_get_polygon_stipple_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_polygon_stipple_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_polygon_stipple_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_polygon_stipple_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_polygon_stipple_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_polygon_stipple_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_polygon_stipple_reply_t>,
    pub(crate) xcb_glx_get_polygon_stipple_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, lsb_first: u8) -> xcb_glx_get_polygon_stipple_cookie_t>,
    pub(crate) xcb_glx_get_query_objectiv_arb: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, id: u32, pname: u32) -> xcb_glx_get_query_objectiv_arb_cookie_t>,
    pub(crate) xcb_glx_get_query_objectiv_arb_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_query_objectiv_arb_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_query_objectiv_arb_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_query_objectiv_arb_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_query_objectiv_arb_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_query_objectiv_arb_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_query_objectiv_arb_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_query_objectiv_arb_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_query_objectiv_arb_reply_t>,
    pub(crate) xcb_glx_get_query_objectiv_arb_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, id: u32, pname: u32) -> xcb_glx_get_query_objectiv_arb_cookie_t>,
    pub(crate) xcb_glx_get_query_objectuiv_arb: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, id: u32, pname: u32) -> xcb_glx_get_query_objectuiv_arb_cookie_t>,
    pub(crate) xcb_glx_get_query_objectuiv_arb_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_query_objectuiv_arb_reply_t) -> *mut u32>,
    pub(crate) xcb_glx_get_query_objectuiv_arb_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_query_objectuiv_arb_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_query_objectuiv_arb_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_query_objectuiv_arb_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_query_objectuiv_arb_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_query_objectuiv_arb_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_query_objectuiv_arb_reply_t>,
    pub(crate) xcb_glx_get_query_objectuiv_arb_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, id: u32, pname: u32) -> xcb_glx_get_query_objectuiv_arb_cookie_t>,
    pub(crate) xcb_glx_get_queryiv_arb: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_queryiv_arb_cookie_t>,
    pub(crate) xcb_glx_get_queryiv_arb_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_queryiv_arb_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_queryiv_arb_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_queryiv_arb_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_queryiv_arb_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_queryiv_arb_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_queryiv_arb_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_queryiv_arb_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_queryiv_arb_reply_t>,
    pub(crate) xcb_glx_get_queryiv_arb_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_queryiv_arb_cookie_t>,
    pub(crate) xcb_glx_get_separable_filter: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, format: u32, type_: u32, swap_bytes: u8) -> xcb_glx_get_separable_filter_cookie_t>,
    pub(crate) xcb_glx_get_separable_filter_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_separable_filter_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_separable_filter_reply_t>,
    pub(crate) xcb_glx_get_separable_filter_rows_and_cols: LazySymbol<unsafe fn(R: *const xcb_glx_get_separable_filter_reply_t) -> *mut u8>,
    pub(crate) xcb_glx_get_separable_filter_rows_and_cols_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_separable_filter_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_separable_filter_rows_and_cols_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_separable_filter_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_separable_filter_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, format: u32, type_: u32, swap_bytes: u8) -> xcb_glx_get_separable_filter_cookie_t>,
    pub(crate) xcb_glx_get_string: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, name: u32) -> xcb_glx_get_string_cookie_t>,
    pub(crate) xcb_glx_get_string_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_string_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_string_reply_t>,
    pub(crate) xcb_glx_get_string_string: LazySymbol<unsafe fn(R: *const xcb_glx_get_string_reply_t) -> *mut c_char>,
    pub(crate) xcb_glx_get_string_string_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_string_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_string_string_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_string_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_string_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, name: u32) -> xcb_glx_get_string_cookie_t>,
    pub(crate) xcb_glx_get_tex_envfv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_tex_envfv_cookie_t>,
    pub(crate) xcb_glx_get_tex_envfv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_envfv_reply_t) -> *mut xcb_glx_float32_t>,
    pub(crate) xcb_glx_get_tex_envfv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_envfv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_tex_envfv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_envfv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_tex_envfv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_tex_envfv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_tex_envfv_reply_t>,
    pub(crate) xcb_glx_get_tex_envfv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_tex_envfv_cookie_t>,
    pub(crate) xcb_glx_get_tex_enviv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_tex_enviv_cookie_t>,
    pub(crate) xcb_glx_get_tex_enviv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_enviv_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_tex_enviv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_enviv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_tex_enviv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_enviv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_tex_enviv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_tex_enviv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_tex_enviv_reply_t>,
    pub(crate) xcb_glx_get_tex_enviv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_tex_enviv_cookie_t>,
    pub(crate) xcb_glx_get_tex_gendv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, coord: u32, pname: u32) -> xcb_glx_get_tex_gendv_cookie_t>,
    pub(crate) xcb_glx_get_tex_gendv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_gendv_reply_t) -> *mut xcb_glx_float64_t>,
    pub(crate) xcb_glx_get_tex_gendv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_gendv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_tex_gendv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_gendv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_tex_gendv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_tex_gendv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_tex_gendv_reply_t>,
    pub(crate) xcb_glx_get_tex_gendv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, coord: u32, pname: u32) -> xcb_glx_get_tex_gendv_cookie_t>,
    pub(crate) xcb_glx_get_tex_genfv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, coord: u32, pname: u32) -> xcb_glx_get_tex_genfv_cookie_t>,
    pub(crate) xcb_glx_get_tex_genfv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_genfv_reply_t) -> *mut xcb_glx_float32_t>,
    pub(crate) xcb_glx_get_tex_genfv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_genfv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_tex_genfv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_genfv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_tex_genfv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_tex_genfv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_tex_genfv_reply_t>,
    pub(crate) xcb_glx_get_tex_genfv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, coord: u32, pname: u32) -> xcb_glx_get_tex_genfv_cookie_t>,
    pub(crate) xcb_glx_get_tex_geniv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, coord: u32, pname: u32) -> xcb_glx_get_tex_geniv_cookie_t>,
    pub(crate) xcb_glx_get_tex_geniv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_geniv_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_tex_geniv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_geniv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_tex_geniv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_geniv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_tex_geniv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_tex_geniv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_tex_geniv_reply_t>,
    pub(crate) xcb_glx_get_tex_geniv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, coord: u32, pname: u32) -> xcb_glx_get_tex_geniv_cookie_t>,
    pub(crate) xcb_glx_get_tex_image: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, level: i32, format: u32, type_: u32, swap_bytes: u8) -> xcb_glx_get_tex_image_cookie_t>,
    pub(crate) xcb_glx_get_tex_image_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_image_reply_t) -> *mut u8>,
    pub(crate) xcb_glx_get_tex_image_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_image_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_tex_image_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_image_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_tex_image_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_tex_image_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_tex_image_reply_t>,
    pub(crate) xcb_glx_get_tex_image_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, level: i32, format: u32, type_: u32, swap_bytes: u8) -> xcb_glx_get_tex_image_cookie_t>,
    pub(crate) xcb_glx_get_tex_level_parameterfv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, level: i32, pname: u32) -> xcb_glx_get_tex_level_parameterfv_cookie_t>,
    pub(crate) xcb_glx_get_tex_level_parameterfv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_level_parameterfv_reply_t) -> *mut xcb_glx_float32_t>,
    pub(crate) xcb_glx_get_tex_level_parameterfv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_level_parameterfv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_tex_level_parameterfv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_level_parameterfv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_tex_level_parameterfv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_tex_level_parameterfv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_tex_level_parameterfv_reply_t>,
    pub(crate) xcb_glx_get_tex_level_parameterfv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, level: i32, pname: u32) -> xcb_glx_get_tex_level_parameterfv_cookie_t>,
    pub(crate) xcb_glx_get_tex_level_parameteriv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, level: i32, pname: u32) -> xcb_glx_get_tex_level_parameteriv_cookie_t>,
    pub(crate) xcb_glx_get_tex_level_parameteriv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_level_parameteriv_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_tex_level_parameteriv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_level_parameteriv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_tex_level_parameteriv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_level_parameteriv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_tex_level_parameteriv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_tex_level_parameteriv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_tex_level_parameteriv_reply_t>,
    pub(crate) xcb_glx_get_tex_level_parameteriv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, level: i32, pname: u32) -> xcb_glx_get_tex_level_parameteriv_cookie_t>,
    pub(crate) xcb_glx_get_tex_parameterfv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_tex_parameterfv_cookie_t>,
    pub(crate) xcb_glx_get_tex_parameterfv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_parameterfv_reply_t) -> *mut xcb_glx_float32_t>,
    pub(crate) xcb_glx_get_tex_parameterfv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_parameterfv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_tex_parameterfv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_parameterfv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_tex_parameterfv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_tex_parameterfv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_tex_parameterfv_reply_t>,
    pub(crate) xcb_glx_get_tex_parameterfv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_tex_parameterfv_cookie_t>,
    pub(crate) xcb_glx_get_tex_parameteriv: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_tex_parameteriv_cookie_t>,
    pub(crate) xcb_glx_get_tex_parameteriv_data: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_parameteriv_reply_t) -> *mut i32>,
    pub(crate) xcb_glx_get_tex_parameteriv_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_parameteriv_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_tex_parameteriv_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_tex_parameteriv_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_tex_parameteriv_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_tex_parameteriv_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_tex_parameteriv_reply_t>,
    pub(crate) xcb_glx_get_tex_parameteriv_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, target: u32, pname: u32) -> xcb_glx_get_tex_parameteriv_cookie_t>,
    pub(crate) xcb_glx_get_visual_configs: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_glx_get_visual_configs_cookie_t>,
    pub(crate) xcb_glx_get_visual_configs_property_list: LazySymbol<unsafe fn(R: *const xcb_glx_get_visual_configs_reply_t) -> *mut u32>,
    pub(crate) xcb_glx_get_visual_configs_property_list_end: LazySymbol<unsafe fn(R: *const xcb_glx_get_visual_configs_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_get_visual_configs_property_list_length: LazySymbol<unsafe fn(R: *const xcb_glx_get_visual_configs_reply_t) -> c_int>,
    pub(crate) xcb_glx_get_visual_configs_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_get_visual_configs_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_get_visual_configs_reply_t>,
    pub(crate) xcb_glx_get_visual_configs_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_glx_get_visual_configs_cookie_t>,
    pub(crate) xcb_glx_id: LazySymbol<*mut xcb_extension_t>,
    pub(crate) xcb_glx_is_direct: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context: xcb_glx_context_t) -> xcb_glx_is_direct_cookie_t>,
    pub(crate) xcb_glx_is_direct_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_is_direct_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_is_direct_reply_t>,
    pub(crate) xcb_glx_is_direct_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context: xcb_glx_context_t) -> xcb_glx_is_direct_cookie_t>,
    pub(crate) xcb_glx_is_list: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, list: u32) -> xcb_glx_is_list_cookie_t>,
    pub(crate) xcb_glx_is_list_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_is_list_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_is_list_reply_t>,
    pub(crate) xcb_glx_is_list_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, list: u32) -> xcb_glx_is_list_cookie_t>,
    pub(crate) xcb_glx_is_query_arb: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, id: u32) -> xcb_glx_is_query_arb_cookie_t>,
    pub(crate) xcb_glx_is_query_arb_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_is_query_arb_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_is_query_arb_reply_t>,
    pub(crate) xcb_glx_is_query_arb_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, id: u32) -> xcb_glx_is_query_arb_cookie_t>,
    pub(crate) xcb_glx_is_texture: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, texture: u32) -> xcb_glx_is_texture_cookie_t>,
    pub(crate) xcb_glx_is_texture_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_is_texture_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_is_texture_reply_t>,
    pub(crate) xcb_glx_is_texture_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, texture: u32) -> xcb_glx_is_texture_cookie_t>,
    pub(crate) xcb_glx_make_context_current: LazySymbol<unsafe fn(c: *mut xcb_connection_t, old_context_tag: xcb_glx_context_tag_t, drawable: xcb_glx_drawable_t, read_drawable: xcb_glx_drawable_t, context: xcb_glx_context_t) -> xcb_glx_make_context_current_cookie_t>,
    pub(crate) xcb_glx_make_context_current_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_make_context_current_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_make_context_current_reply_t>,
    pub(crate) xcb_glx_make_context_current_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, old_context_tag: xcb_glx_context_tag_t, drawable: xcb_glx_drawable_t, read_drawable: xcb_glx_drawable_t, context: xcb_glx_context_t) -> xcb_glx_make_context_current_cookie_t>,
    pub(crate) xcb_glx_make_current: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_glx_drawable_t, context: xcb_glx_context_t, old_context_tag: xcb_glx_context_tag_t) -> xcb_glx_make_current_cookie_t>,
    pub(crate) xcb_glx_make_current_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_make_current_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_make_current_reply_t>,
    pub(crate) xcb_glx_make_current_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_glx_drawable_t, context: xcb_glx_context_t, old_context_tag: xcb_glx_context_tag_t) -> xcb_glx_make_current_cookie_t>,
    pub(crate) xcb_glx_new_list: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, list: u32, mode: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_new_list_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, list: u32, mode: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_pbuffer_end: LazySymbol<unsafe fn(i: *mut xcb_glx_pbuffer_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_pbuffer_next: LazySymbol<unsafe fn(i: *mut xcb_glx_pbuffer_iterator_t)>,
    pub(crate) xcb_glx_pixel_storef: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, pname: u32, datum: xcb_glx_float32_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_pixel_storef_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, pname: u32, datum: xcb_glx_float32_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_pixel_storei: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, pname: u32, datum: i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_pixel_storei_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, pname: u32, datum: i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_pixmap_end: LazySymbol<unsafe fn(i: *mut xcb_glx_pixmap_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_pixmap_next: LazySymbol<unsafe fn(i: *mut xcb_glx_pixmap_iterator_t)>,
    pub(crate) xcb_glx_query_context: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context: xcb_glx_context_t) -> xcb_glx_query_context_cookie_t>,
    pub(crate) xcb_glx_query_context_attribs: LazySymbol<unsafe fn(R: *const xcb_glx_query_context_reply_t) -> *mut u32>,
    pub(crate) xcb_glx_query_context_attribs_end: LazySymbol<unsafe fn(R: *const xcb_glx_query_context_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_query_context_attribs_length: LazySymbol<unsafe fn(R: *const xcb_glx_query_context_reply_t) -> c_int>,
    pub(crate) xcb_glx_query_context_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_query_context_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_query_context_reply_t>,
    pub(crate) xcb_glx_query_context_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context: xcb_glx_context_t) -> xcb_glx_query_context_cookie_t>,
    pub(crate) xcb_glx_query_extensions_string: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_glx_query_extensions_string_cookie_t>,
    pub(crate) xcb_glx_query_extensions_string_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_query_extensions_string_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_query_extensions_string_reply_t>,
    pub(crate) xcb_glx_query_extensions_string_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32) -> xcb_glx_query_extensions_string_cookie_t>,
    pub(crate) xcb_glx_query_server_string: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, name: u32) -> xcb_glx_query_server_string_cookie_t>,
    pub(crate) xcb_glx_query_server_string_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_query_server_string_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_query_server_string_reply_t>,
    pub(crate) xcb_glx_query_server_string_string: LazySymbol<unsafe fn(R: *const xcb_glx_query_server_string_reply_t) -> *mut c_char>,
    pub(crate) xcb_glx_query_server_string_string_end: LazySymbol<unsafe fn(R: *const xcb_glx_query_server_string_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_query_server_string_string_length: LazySymbol<unsafe fn(R: *const xcb_glx_query_server_string_reply_t) -> c_int>,
    pub(crate) xcb_glx_query_server_string_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, screen: u32, name: u32) -> xcb_glx_query_server_string_cookie_t>,
    pub(crate) xcb_glx_query_version: LazySymbol<unsafe fn(c: *mut xcb_connection_t, major_version: u32, minor_version: u32) -> xcb_glx_query_version_cookie_t>,
    pub(crate) xcb_glx_query_version_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_query_version_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_query_version_reply_t>,
    pub(crate) xcb_glx_query_version_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, major_version: u32, minor_version: u32) -> xcb_glx_query_version_cookie_t>,
    pub(crate) xcb_glx_read_pixels: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, x: i32, y: i32, width: i32, height: i32, format: u32, type_: u32, swap_bytes: u8, lsb_first: u8) -> xcb_glx_read_pixels_cookie_t>,
    pub(crate) xcb_glx_read_pixels_data: LazySymbol<unsafe fn(R: *const xcb_glx_read_pixels_reply_t) -> *mut u8>,
    pub(crate) xcb_glx_read_pixels_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_read_pixels_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_read_pixels_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_read_pixels_reply_t) -> c_int>,
    pub(crate) xcb_glx_read_pixels_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_read_pixels_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_read_pixels_reply_t>,
    pub(crate) xcb_glx_read_pixels_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, x: i32, y: i32, width: i32, height: i32, format: u32, type_: u32, swap_bytes: u8, lsb_first: u8) -> xcb_glx_read_pixels_cookie_t>,
    pub(crate) xcb_glx_render: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, data_len: u32, data: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_render_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, data_len: u32, data: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_render_large: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, request_num: u16, request_total: u16, data_len: u32, data: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_render_large_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, request_num: u16, request_total: u16, data_len: u32, data: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_render_mode: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, mode: u32) -> xcb_glx_render_mode_cookie_t>,
    pub(crate) xcb_glx_render_mode_data: LazySymbol<unsafe fn(R: *const xcb_glx_render_mode_reply_t) -> *mut u32>,
    pub(crate) xcb_glx_render_mode_data_end: LazySymbol<unsafe fn(R: *const xcb_glx_render_mode_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_render_mode_data_length: LazySymbol<unsafe fn(R: *const xcb_glx_render_mode_reply_t) -> c_int>,
    pub(crate) xcb_glx_render_mode_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_render_mode_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_render_mode_reply_t>,
    pub(crate) xcb_glx_render_mode_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, mode: u32) -> xcb_glx_render_mode_cookie_t>,
    pub(crate) xcb_glx_select_buffer: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, size: i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_select_buffer_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, size: i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_set_client_info_2arb: LazySymbol<unsafe fn(c: *mut xcb_connection_t, major_version: u32, minor_version: u32, num_versions: u32, gl_str_len: u32, glx_str_len: u32, gl_versions: *const u32, gl_extension_string: *const c_char, glx_extension_string: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_set_client_info_2arb_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, major_version: u32, minor_version: u32, num_versions: u32, gl_str_len: u32, glx_str_len: u32, gl_versions: *const u32, gl_extension_string: *const c_char, glx_extension_string: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_set_client_info_arb: LazySymbol<unsafe fn(c: *mut xcb_connection_t, major_version: u32, minor_version: u32, num_versions: u32, gl_str_len: u32, glx_str_len: u32, gl_versions: *const u32, gl_extension_string: *const c_char, glx_extension_string: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_set_client_info_arb_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, major_version: u32, minor_version: u32, num_versions: u32, gl_str_len: u32, glx_str_len: u32, gl_versions: *const u32, gl_extension_string: *const c_char, glx_extension_string: *const c_char) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_swap_buffers: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, drawable: xcb_glx_drawable_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_swap_buffers_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, drawable: xcb_glx_drawable_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_use_x_font: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, font: xcb_font_t, first: u32, count: u32, list_base: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_use_x_font_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t, font: xcb_font_t, first: u32, count: u32, list_base: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_vendor_private: LazySymbol<unsafe fn(c: *mut xcb_connection_t, vendor_code: u32, context_tag: xcb_glx_context_tag_t, data_len: u32, data: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_vendor_private_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, vendor_code: u32, context_tag: xcb_glx_context_tag_t, data_len: u32, data: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_vendor_private_with_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, vendor_code: u32, context_tag: xcb_glx_context_tag_t, data_len: u32, data: *const u8) -> xcb_glx_vendor_private_with_reply_cookie_t>,
    pub(crate) xcb_glx_vendor_private_with_reply_data_2: LazySymbol<unsafe fn(R: *const xcb_glx_vendor_private_with_reply_reply_t) -> *mut u8>,
    pub(crate) xcb_glx_vendor_private_with_reply_data_2_end: LazySymbol<unsafe fn(R: *const xcb_glx_vendor_private_with_reply_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_vendor_private_with_reply_data_2_length: LazySymbol<unsafe fn(R: *const xcb_glx_vendor_private_with_reply_reply_t) -> c_int>,
    pub(crate) xcb_glx_vendor_private_with_reply_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_glx_vendor_private_with_reply_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_glx_vendor_private_with_reply_reply_t>,
    pub(crate) xcb_glx_vendor_private_with_reply_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, vendor_code: u32, context_tag: xcb_glx_context_tag_t, data_len: u32, data: *const u8) -> xcb_glx_vendor_private_with_reply_cookie_t>,
    pub(crate) xcb_glx_wait_gl: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_wait_gl_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_wait_x: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_wait_x_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, context_tag: xcb_glx_context_tag_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_glx_window_end: LazySymbol<unsafe fn(i: *mut xcb_glx_window_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_glx_window_next: LazySymbol<unsafe fn(i: *mut xcb_glx_window_iterator_t)>,
}
