use crate::lazy::*;
use crate::*;
use libloading::{Error, Library};
use std::os::raw::*;

#[rustfmt::skip]
pub struct XcbXv {
    pub(crate) lib: NamedLibrary,
    pub(crate) xcb_xv_adaptor_info_end: LazySymbol<unsafe fn(i: *mut xcb_xv_adaptor_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_adaptor_info_formats: LazySymbol<unsafe fn(R: *const xcb_xv_adaptor_info_t) -> *mut xcb_xv_format_t>,
    pub(crate) xcb_xv_adaptor_info_formats_iterator: LazySymbol<unsafe fn(R: *const xcb_xv_adaptor_info_t) -> xcb_xv_format_iterator_t>,
    pub(crate) xcb_xv_adaptor_info_formats_length: LazySymbol<unsafe fn(R: *const xcb_xv_adaptor_info_t) -> c_int>,
    pub(crate) xcb_xv_adaptor_info_name: LazySymbol<unsafe fn(R: *const xcb_xv_adaptor_info_t) -> *mut c_char>,
    pub(crate) xcb_xv_adaptor_info_name_end: LazySymbol<unsafe fn(R: *const xcb_xv_adaptor_info_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_adaptor_info_name_length: LazySymbol<unsafe fn(R: *const xcb_xv_adaptor_info_t) -> c_int>,
    pub(crate) xcb_xv_adaptor_info_next: LazySymbol<unsafe fn(i: *mut xcb_xv_adaptor_info_iterator_t)>,
    pub(crate) xcb_xv_attribute_info_end: LazySymbol<unsafe fn(i: *mut xcb_xv_attribute_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_attribute_info_name: LazySymbol<unsafe fn(R: *const xcb_xv_attribute_info_t) -> *mut c_char>,
    pub(crate) xcb_xv_attribute_info_name_end: LazySymbol<unsafe fn(R: *const xcb_xv_attribute_info_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_attribute_info_name_length: LazySymbol<unsafe fn(R: *const xcb_xv_attribute_info_t) -> c_int>,
    pub(crate) xcb_xv_attribute_info_next: LazySymbol<unsafe fn(i: *mut xcb_xv_attribute_info_iterator_t)>,
    pub(crate) xcb_xv_encoding_end: LazySymbol<unsafe fn(i: *mut xcb_xv_encoding_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_encoding_info_end: LazySymbol<unsafe fn(i: *mut xcb_xv_encoding_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_encoding_info_name: LazySymbol<unsafe fn(R: *const xcb_xv_encoding_info_t) -> *mut c_char>,
    pub(crate) xcb_xv_encoding_info_name_end: LazySymbol<unsafe fn(R: *const xcb_xv_encoding_info_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_encoding_info_name_length: LazySymbol<unsafe fn(R: *const xcb_xv_encoding_info_t) -> c_int>,
    pub(crate) xcb_xv_encoding_info_next: LazySymbol<unsafe fn(i: *mut xcb_xv_encoding_info_iterator_t)>,
    pub(crate) xcb_xv_encoding_next: LazySymbol<unsafe fn(i: *mut xcb_xv_encoding_iterator_t)>,
    pub(crate) xcb_xv_format_end: LazySymbol<unsafe fn(i: *mut xcb_xv_format_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_format_next: LazySymbol<unsafe fn(i: *mut xcb_xv_format_iterator_t)>,
    pub(crate) xcb_xv_get_port_attribute: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, attribute: xcb_atom_t) -> xcb_xv_get_port_attribute_cookie_t>,
    pub(crate) xcb_xv_get_port_attribute_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xv_get_port_attribute_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xv_get_port_attribute_reply_t>,
    pub(crate) xcb_xv_get_port_attribute_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, attribute: xcb_atom_t) -> xcb_xv_get_port_attribute_cookie_t>,
    pub(crate) xcb_xv_get_still: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, vid_x: i16, vid_y: i16, vid_w: u16, vid_h: u16, drw_x: i16, drw_y: i16, drw_w: u16, drw_h: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_get_still_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, vid_x: i16, vid_y: i16, vid_w: u16, vid_h: u16, drw_x: i16, drw_y: i16, drw_w: u16, drw_h: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_get_video: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, vid_x: i16, vid_y: i16, vid_w: u16, vid_h: u16, drw_x: i16, drw_y: i16, drw_w: u16, drw_h: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_get_video_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, vid_x: i16, vid_y: i16, vid_w: u16, vid_h: u16, drw_x: i16, drw_y: i16, drw_w: u16, drw_h: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_grab_port: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, time: xcb_timestamp_t) -> xcb_xv_grab_port_cookie_t>,
    pub(crate) xcb_xv_grab_port_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xv_grab_port_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xv_grab_port_reply_t>,
    pub(crate) xcb_xv_grab_port_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, time: xcb_timestamp_t) -> xcb_xv_grab_port_cookie_t>,
    pub(crate) xcb_xv_id: LazySymbol<*mut xcb_extension_t>,
    pub(crate) xcb_xv_image_data: LazySymbol<unsafe fn(R: *const xcb_xv_image_t) -> *mut u8>,
    pub(crate) xcb_xv_image_data_end: LazySymbol<unsafe fn(R: *const xcb_xv_image_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_image_data_length: LazySymbol<unsafe fn(R: *const xcb_xv_image_t) -> c_int>,
    pub(crate) xcb_xv_image_end: LazySymbol<unsafe fn(i: *mut xcb_xv_image_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_image_format_info_end: LazySymbol<unsafe fn(i: *mut xcb_xv_image_format_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_image_format_info_next: LazySymbol<unsafe fn(i: *mut xcb_xv_image_format_info_iterator_t)>,
    pub(crate) xcb_xv_image_next: LazySymbol<unsafe fn(i: *mut xcb_xv_image_iterator_t)>,
    pub(crate) xcb_xv_image_offsets: LazySymbol<unsafe fn(R: *const xcb_xv_image_t) -> *mut u32>,
    pub(crate) xcb_xv_image_offsets_end: LazySymbol<unsafe fn(R: *const xcb_xv_image_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_image_offsets_length: LazySymbol<unsafe fn(R: *const xcb_xv_image_t) -> c_int>,
    pub(crate) xcb_xv_image_pitches: LazySymbol<unsafe fn(R: *const xcb_xv_image_t) -> *mut u32>,
    pub(crate) xcb_xv_image_pitches_end: LazySymbol<unsafe fn(R: *const xcb_xv_image_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_image_pitches_length: LazySymbol<unsafe fn(R: *const xcb_xv_image_t) -> c_int>,
    pub(crate) xcb_xv_list_image_formats: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t) -> xcb_xv_list_image_formats_cookie_t>,
    pub(crate) xcb_xv_list_image_formats_format: LazySymbol<unsafe fn(R: *const xcb_xv_list_image_formats_reply_t) -> *mut xcb_xv_image_format_info_t>,
    pub(crate) xcb_xv_list_image_formats_format_iterator: LazySymbol<unsafe fn(R: *const xcb_xv_list_image_formats_reply_t) -> xcb_xv_image_format_info_iterator_t>,
    pub(crate) xcb_xv_list_image_formats_format_length: LazySymbol<unsafe fn(R: *const xcb_xv_list_image_formats_reply_t) -> c_int>,
    pub(crate) xcb_xv_list_image_formats_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xv_list_image_formats_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xv_list_image_formats_reply_t>,
    pub(crate) xcb_xv_list_image_formats_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t) -> xcb_xv_list_image_formats_cookie_t>,
    pub(crate) xcb_xv_port_end: LazySymbol<unsafe fn(i: *mut xcb_xv_port_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_port_next: LazySymbol<unsafe fn(i: *mut xcb_xv_port_iterator_t)>,
    pub(crate) xcb_xv_put_image: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, id: u32, src_x: i16, src_y: i16, src_w: u16, src_h: u16, drw_x: i16, drw_y: i16, drw_w: u16, drw_h: u16, width: u16, height: u16, data_len: u32, data: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_put_image_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, id: u32, src_x: i16, src_y: i16, src_w: u16, src_h: u16, drw_x: i16, drw_y: i16, drw_w: u16, drw_h: u16, width: u16, height: u16, data_len: u32, data: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_put_still: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, vid_x: i16, vid_y: i16, vid_w: u16, vid_h: u16, drw_x: i16, drw_y: i16, drw_w: u16, drw_h: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_put_still_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, vid_x: i16, vid_y: i16, vid_w: u16, vid_h: u16, drw_x: i16, drw_y: i16, drw_w: u16, drw_h: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_put_video: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, vid_x: i16, vid_y: i16, vid_w: u16, vid_h: u16, drw_x: i16, drw_y: i16, drw_w: u16, drw_h: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_put_video_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, vid_x: i16, vid_y: i16, vid_w: u16, vid_h: u16, drw_x: i16, drw_y: i16, drw_w: u16, drw_h: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_query_adaptors: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_xv_query_adaptors_cookie_t>,
    pub(crate) xcb_xv_query_adaptors_info_iterator: LazySymbol<unsafe fn(R: *const xcb_xv_query_adaptors_reply_t) -> xcb_xv_adaptor_info_iterator_t>,
    pub(crate) xcb_xv_query_adaptors_info_length: LazySymbol<unsafe fn(R: *const xcb_xv_query_adaptors_reply_t) -> c_int>,
    pub(crate) xcb_xv_query_adaptors_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xv_query_adaptors_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xv_query_adaptors_reply_t>,
    pub(crate) xcb_xv_query_adaptors_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_xv_query_adaptors_cookie_t>,
    pub(crate) xcb_xv_query_best_size: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, vid_w: u16, vid_h: u16, drw_w: u16, drw_h: u16, motion: u8) -> xcb_xv_query_best_size_cookie_t>,
    pub(crate) xcb_xv_query_best_size_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xv_query_best_size_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xv_query_best_size_reply_t>,
    pub(crate) xcb_xv_query_best_size_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, vid_w: u16, vid_h: u16, drw_w: u16, drw_h: u16, motion: u8) -> xcb_xv_query_best_size_cookie_t>,
    pub(crate) xcb_xv_query_encodings: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t) -> xcb_xv_query_encodings_cookie_t>,
    pub(crate) xcb_xv_query_encodings_info_iterator: LazySymbol<unsafe fn(R: *const xcb_xv_query_encodings_reply_t) -> xcb_xv_encoding_info_iterator_t>,
    pub(crate) xcb_xv_query_encodings_info_length: LazySymbol<unsafe fn(R: *const xcb_xv_query_encodings_reply_t) -> c_int>,
    pub(crate) xcb_xv_query_encodings_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xv_query_encodings_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xv_query_encodings_reply_t>,
    pub(crate) xcb_xv_query_encodings_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t) -> xcb_xv_query_encodings_cookie_t>,
    pub(crate) xcb_xv_query_extension: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_xv_query_extension_cookie_t>,
    pub(crate) xcb_xv_query_extension_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xv_query_extension_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xv_query_extension_reply_t>,
    pub(crate) xcb_xv_query_extension_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_xv_query_extension_cookie_t>,
    pub(crate) xcb_xv_query_image_attributes: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, id: u32, width: u16, height: u16) -> xcb_xv_query_image_attributes_cookie_t>,
    pub(crate) xcb_xv_query_image_attributes_offsets: LazySymbol<unsafe fn(R: *const xcb_xv_query_image_attributes_reply_t) -> *mut u32>,
    pub(crate) xcb_xv_query_image_attributes_offsets_end: LazySymbol<unsafe fn(R: *const xcb_xv_query_image_attributes_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_query_image_attributes_offsets_length: LazySymbol<unsafe fn(R: *const xcb_xv_query_image_attributes_reply_t) -> c_int>,
    pub(crate) xcb_xv_query_image_attributes_pitches: LazySymbol<unsafe fn(R: *const xcb_xv_query_image_attributes_reply_t) -> *mut u32>,
    pub(crate) xcb_xv_query_image_attributes_pitches_end: LazySymbol<unsafe fn(R: *const xcb_xv_query_image_attributes_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_query_image_attributes_pitches_length: LazySymbol<unsafe fn(R: *const xcb_xv_query_image_attributes_reply_t) -> c_int>,
    pub(crate) xcb_xv_query_image_attributes_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xv_query_image_attributes_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xv_query_image_attributes_reply_t>,
    pub(crate) xcb_xv_query_image_attributes_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, id: u32, width: u16, height: u16) -> xcb_xv_query_image_attributes_cookie_t>,
    pub(crate) xcb_xv_query_port_attributes: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t) -> xcb_xv_query_port_attributes_cookie_t>,
    pub(crate) xcb_xv_query_port_attributes_attributes_iterator: LazySymbol<unsafe fn(R: *const xcb_xv_query_port_attributes_reply_t) -> xcb_xv_attribute_info_iterator_t>,
    pub(crate) xcb_xv_query_port_attributes_attributes_length: LazySymbol<unsafe fn(R: *const xcb_xv_query_port_attributes_reply_t) -> c_int>,
    pub(crate) xcb_xv_query_port_attributes_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xv_query_port_attributes_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xv_query_port_attributes_reply_t>,
    pub(crate) xcb_xv_query_port_attributes_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t) -> xcb_xv_query_port_attributes_cookie_t>,
    pub(crate) xcb_xv_rational_end: LazySymbol<unsafe fn(i: *mut xcb_xv_rational_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xv_rational_next: LazySymbol<unsafe fn(i: *mut xcb_xv_rational_iterator_t)>,
    pub(crate) xcb_xv_select_port_notify: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, onoff: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_select_port_notify_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, onoff: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_select_video_notify: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, onoff: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_select_video_notify_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t, onoff: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_set_port_attribute: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, attribute: xcb_atom_t, value: i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_set_port_attribute_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, attribute: xcb_atom_t, value: i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_shm_put_image: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, shmseg: xcb_shm_seg_t, id: u32, offset: u32, src_x: i16, src_y: i16, src_w: u16, src_h: u16, drw_x: i16, drw_y: i16, drw_w: u16, drw_h: u16, width: u16, height: u16, send_event: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_shm_put_image_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t, gc: xcb_gcontext_t, shmseg: xcb_shm_seg_t, id: u32, offset: u32, src_x: i16, src_y: i16, src_w: u16, src_h: u16, drw_x: i16, drw_y: i16, drw_w: u16, drw_h: u16, width: u16, height: u16, send_event: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_stop_video: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_stop_video_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, drawable: xcb_drawable_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_ungrab_port: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xv_ungrab_port_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, port: xcb_xv_port_t, time: xcb_timestamp_t) -> xcb_void_cookie_t>,
}
