use crate::ffi::*;
use crate::lazy::*;
use libloading::{Error, Library};
use std::os::raw::*;

#[rustfmt::skip]
pub struct XcbRender {
    pub(crate) lib: NamedLibrary,
    pub(crate) xcb_render_add_glyphs: LazySymbol<unsafe fn(c: *mut xcb_connection_t, glyphset: xcb_render_glyphset_t, glyphs_len: u32, glyphids: *const u32, glyphs: *const xcb_render_glyphinfo_t, data_len: u32, data: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_add_glyphs_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, glyphset: xcb_render_glyphset_t, glyphs_len: u32, glyphids: *const u32, glyphs: *const xcb_render_glyphinfo_t, data_len: u32, data: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_add_traps: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, x_off: i16, y_off: i16, traps_len: u32, traps: *const xcb_render_trap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_add_traps_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, x_off: i16, y_off: i16, traps_len: u32, traps: *const xcb_render_trap_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_animcursorelt_end: LazySymbol<unsafe fn(i: *mut xcb_render_animcursorelt_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_animcursorelt_next: LazySymbol<unsafe fn(i: *mut xcb_render_animcursorelt_iterator_t)>,
    pub(crate) xcb_render_change_picture: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_change_picture_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_color_end: LazySymbol<unsafe fn(i: *mut xcb_render_color_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_color_next: LazySymbol<unsafe fn(i: *mut xcb_render_color_iterator_t)>,
    pub(crate) xcb_render_composite: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, mask: xcb_render_picture_t, dst: xcb_render_picture_t, src_x: i16, src_y: i16, mask_x: i16, mask_y: i16, dst_x: i16, dst_y: i16, width: u16, height: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_composite_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, mask: xcb_render_picture_t, dst: xcb_render_picture_t, src_x: i16, src_y: i16, mask_x: i16, mask_y: i16, dst_x: i16, dst_y: i16, width: u16, height: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_composite_glyphs_16: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, glyphset: xcb_render_glyphset_t, src_x: i16, src_y: i16, glyphcmds_len: u32, glyphcmds: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_composite_glyphs_16_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, glyphset: xcb_render_glyphset_t, src_x: i16, src_y: i16, glyphcmds_len: u32, glyphcmds: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_composite_glyphs_32: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, glyphset: xcb_render_glyphset_t, src_x: i16, src_y: i16, glyphcmds_len: u32, glyphcmds: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_composite_glyphs_32_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, glyphset: xcb_render_glyphset_t, src_x: i16, src_y: i16, glyphcmds_len: u32, glyphcmds: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_composite_glyphs_8: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, glyphset: xcb_render_glyphset_t, src_x: i16, src_y: i16, glyphcmds_len: u32, glyphcmds: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_composite_glyphs_8_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, glyphset: xcb_render_glyphset_t, src_x: i16, src_y: i16, glyphcmds_len: u32, glyphcmds: *const u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_anim_cursor: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cid: xcb_cursor_t, cursors_len: u32, cursors: *const xcb_render_animcursorelt_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_anim_cursor_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cid: xcb_cursor_t, cursors_len: u32, cursors: *const xcb_render_animcursorelt_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_conical_gradient: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, center: xcb_render_pointfix_t, angle: xcb_render_fixed_t, num_stops: u32, stops: *const xcb_render_fixed_t, colors: *const xcb_render_color_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_conical_gradient_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, center: xcb_render_pointfix_t, angle: xcb_render_fixed_t, num_stops: u32, stops: *const xcb_render_fixed_t, colors: *const xcb_render_color_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_cursor: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cid: xcb_cursor_t, source: xcb_render_picture_t, x: u16, y: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_cursor_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cid: xcb_cursor_t, source: xcb_render_picture_t, x: u16, y: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_glyph_set: LazySymbol<unsafe fn(c: *mut xcb_connection_t, gsid: xcb_render_glyphset_t, format: xcb_render_pictformat_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_glyph_set_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, gsid: xcb_render_glyphset_t, format: xcb_render_pictformat_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_linear_gradient: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, p1: xcb_render_pointfix_t, p2: xcb_render_pointfix_t, num_stops: u32, stops: *const xcb_render_fixed_t, colors: *const xcb_render_color_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_linear_gradient_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, p1: xcb_render_pointfix_t, p2: xcb_render_pointfix_t, num_stops: u32, stops: *const xcb_render_fixed_t, colors: *const xcb_render_color_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_picture: LazySymbol<unsafe fn(c: *mut xcb_connection_t, pid: xcb_render_picture_t, drawable: xcb_drawable_t, format: xcb_render_pictformat_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_picture_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, pid: xcb_render_picture_t, drawable: xcb_drawable_t, format: xcb_render_pictformat_t, value_mask: u32, value_list: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_radial_gradient: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, inner: xcb_render_pointfix_t, outer: xcb_render_pointfix_t, inner_radius: xcb_render_fixed_t, outer_radius: xcb_render_fixed_t, num_stops: u32, stops: *const xcb_render_fixed_t, colors: *const xcb_render_color_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_radial_gradient_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, inner: xcb_render_pointfix_t, outer: xcb_render_pointfix_t, inner_radius: xcb_render_fixed_t, outer_radius: xcb_render_fixed_t, num_stops: u32, stops: *const xcb_render_fixed_t, colors: *const xcb_render_color_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_solid_fill: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, color: xcb_render_color_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_create_solid_fill_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, color: xcb_render_color_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_directformat_end: LazySymbol<unsafe fn(i: *mut xcb_render_directformat_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_directformat_next: LazySymbol<unsafe fn(i: *mut xcb_render_directformat_iterator_t)>,
    pub(crate) xcb_render_fill_rectangles: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, dst: xcb_render_picture_t, color: xcb_render_color_t, rects_len: u32, rects: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_fill_rectangles_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, dst: xcb_render_picture_t, color: xcb_render_color_t, rects_len: u32, rects: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_fixed_end: LazySymbol<unsafe fn(i: *mut xcb_render_fixed_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_fixed_next: LazySymbol<unsafe fn(i: *mut xcb_render_fixed_iterator_t)>,
    pub(crate) xcb_render_free_glyph_set: LazySymbol<unsafe fn(c: *mut xcb_connection_t, glyphset: xcb_render_glyphset_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_free_glyph_set_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, glyphset: xcb_render_glyphset_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_free_glyphs: LazySymbol<unsafe fn(c: *mut xcb_connection_t, glyphset: xcb_render_glyphset_t, glyphs_len: u32, glyphs: *const xcb_render_glyph_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_free_glyphs_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, glyphset: xcb_render_glyphset_t, glyphs_len: u32, glyphs: *const xcb_render_glyph_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_free_picture: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_free_picture_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_glyph_end: LazySymbol<unsafe fn(i: *mut xcb_render_glyph_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_glyph_next: LazySymbol<unsafe fn(i: *mut xcb_render_glyph_iterator_t)>,
    pub(crate) xcb_render_glyphinfo_end: LazySymbol<unsafe fn(i: *mut xcb_render_glyphinfo_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_glyphinfo_next: LazySymbol<unsafe fn(i: *mut xcb_render_glyphinfo_iterator_t)>,
    pub(crate) xcb_render_glyphset_end: LazySymbol<unsafe fn(i: *mut xcb_render_glyphset_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_glyphset_next: LazySymbol<unsafe fn(i: *mut xcb_render_glyphset_iterator_t)>,
    pub(crate) xcb_render_id: LazySymbol<*mut xcb_extension_t>,
    pub(crate) xcb_render_indexvalue_end: LazySymbol<unsafe fn(i: *mut xcb_render_indexvalue_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_indexvalue_next: LazySymbol<unsafe fn(i: *mut xcb_render_indexvalue_iterator_t)>,
    pub(crate) xcb_render_linefix_end: LazySymbol<unsafe fn(i: *mut xcb_render_linefix_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_linefix_next: LazySymbol<unsafe fn(i: *mut xcb_render_linefix_iterator_t)>,
    pub(crate) xcb_render_pictdepth_end: LazySymbol<unsafe fn(i: *mut xcb_render_pictdepth_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_pictdepth_next: LazySymbol<unsafe fn(i: *mut xcb_render_pictdepth_iterator_t)>,
    pub(crate) xcb_render_pictdepth_visuals: LazySymbol<unsafe fn(R: *const xcb_render_pictdepth_t) -> *mut xcb_render_pictvisual_t>,
    pub(crate) xcb_render_pictdepth_visuals_iterator: LazySymbol<unsafe fn(R: *const xcb_render_pictdepth_t) -> xcb_render_pictvisual_iterator_t>,
    pub(crate) xcb_render_pictdepth_visuals_length: LazySymbol<unsafe fn(R: *const xcb_render_pictdepth_t) -> c_int>,
    pub(crate) xcb_render_pictformat_end: LazySymbol<unsafe fn(i: *mut xcb_render_pictformat_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_pictformat_next: LazySymbol<unsafe fn(i: *mut xcb_render_pictformat_iterator_t)>,
    pub(crate) xcb_render_pictforminfo_end: LazySymbol<unsafe fn(i: *mut xcb_render_pictforminfo_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_pictforminfo_next: LazySymbol<unsafe fn(i: *mut xcb_render_pictforminfo_iterator_t)>,
    pub(crate) xcb_render_pictscreen_depths_iterator: LazySymbol<unsafe fn(R: *const xcb_render_pictscreen_t) -> xcb_render_pictdepth_iterator_t>,
    pub(crate) xcb_render_pictscreen_depths_length: LazySymbol<unsafe fn(R: *const xcb_render_pictscreen_t) -> c_int>,
    pub(crate) xcb_render_pictscreen_end: LazySymbol<unsafe fn(i: *mut xcb_render_pictscreen_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_pictscreen_next: LazySymbol<unsafe fn(i: *mut xcb_render_pictscreen_iterator_t)>,
    pub(crate) xcb_render_picture_end: LazySymbol<unsafe fn(i: *mut xcb_render_picture_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_picture_next: LazySymbol<unsafe fn(i: *mut xcb_render_picture_iterator_t)>,
    pub(crate) xcb_render_pictvisual_end: LazySymbol<unsafe fn(i: *mut xcb_render_pictvisual_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_pictvisual_next: LazySymbol<unsafe fn(i: *mut xcb_render_pictvisual_iterator_t)>,
    pub(crate) xcb_render_pointfix_end: LazySymbol<unsafe fn(i: *mut xcb_render_pointfix_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_pointfix_next: LazySymbol<unsafe fn(i: *mut xcb_render_pointfix_iterator_t)>,
    pub(crate) xcb_render_query_filters: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t) -> xcb_render_query_filters_cookie_t>,
    pub(crate) xcb_render_query_filters_aliases: LazySymbol<unsafe fn(R: *const xcb_render_query_filters_reply_t) -> *mut u16>,
    pub(crate) xcb_render_query_filters_aliases_end: LazySymbol<unsafe fn(R: *const xcb_render_query_filters_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_query_filters_aliases_length: LazySymbol<unsafe fn(R: *const xcb_render_query_filters_reply_t) -> c_int>,
    pub(crate) xcb_render_query_filters_filters_iterator: LazySymbol<unsafe fn(R: *const xcb_render_query_filters_reply_t) -> xcb_str_iterator_t>,
    pub(crate) xcb_render_query_filters_filters_length: LazySymbol<unsafe fn(R: *const xcb_render_query_filters_reply_t) -> c_int>,
    pub(crate) xcb_render_query_filters_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_render_query_filters_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_render_query_filters_reply_t>,
    pub(crate) xcb_render_query_filters_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, drawable: xcb_drawable_t) -> xcb_render_query_filters_cookie_t>,
    pub(crate) xcb_render_query_pict_formats: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_render_query_pict_formats_cookie_t>,
    pub(crate) xcb_render_query_pict_formats_formats: LazySymbol<unsafe fn(R: *const xcb_render_query_pict_formats_reply_t) -> *mut xcb_render_pictforminfo_t>,
    pub(crate) xcb_render_query_pict_formats_formats_iterator: LazySymbol<unsafe fn(R: *const xcb_render_query_pict_formats_reply_t) -> xcb_render_pictforminfo_iterator_t>,
    pub(crate) xcb_render_query_pict_formats_formats_length: LazySymbol<unsafe fn(R: *const xcb_render_query_pict_formats_reply_t) -> c_int>,
    pub(crate) xcb_render_query_pict_formats_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_render_query_pict_formats_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_render_query_pict_formats_reply_t>,
    pub(crate) xcb_render_query_pict_formats_screens_iterator: LazySymbol<unsafe fn(R: *const xcb_render_query_pict_formats_reply_t) -> xcb_render_pictscreen_iterator_t>,
    pub(crate) xcb_render_query_pict_formats_screens_length: LazySymbol<unsafe fn(R: *const xcb_render_query_pict_formats_reply_t) -> c_int>,
    pub(crate) xcb_render_query_pict_formats_subpixels: LazySymbol<unsafe fn(R: *const xcb_render_query_pict_formats_reply_t) -> *mut u32>,
    pub(crate) xcb_render_query_pict_formats_subpixels_end: LazySymbol<unsafe fn(R: *const xcb_render_query_pict_formats_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_query_pict_formats_subpixels_length: LazySymbol<unsafe fn(R: *const xcb_render_query_pict_formats_reply_t) -> c_int>,
    pub(crate) xcb_render_query_pict_formats_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_render_query_pict_formats_cookie_t>,
    pub(crate) xcb_render_query_pict_index_values: LazySymbol<unsafe fn(c: *mut xcb_connection_t, format: xcb_render_pictformat_t) -> xcb_render_query_pict_index_values_cookie_t>,
    pub(crate) xcb_render_query_pict_index_values_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_render_query_pict_index_values_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_render_query_pict_index_values_reply_t>,
    pub(crate) xcb_render_query_pict_index_values_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, format: xcb_render_pictformat_t) -> xcb_render_query_pict_index_values_cookie_t>,
    pub(crate) xcb_render_query_pict_index_values_values: LazySymbol<unsafe fn(R: *const xcb_render_query_pict_index_values_reply_t) -> *mut xcb_render_indexvalue_t>,
    pub(crate) xcb_render_query_pict_index_values_values_iterator: LazySymbol<unsafe fn(R: *const xcb_render_query_pict_index_values_reply_t) -> xcb_render_indexvalue_iterator_t>,
    pub(crate) xcb_render_query_pict_index_values_values_length: LazySymbol<unsafe fn(R: *const xcb_render_query_pict_index_values_reply_t) -> c_int>,
    pub(crate) xcb_render_query_version: LazySymbol<unsafe fn(c: *mut xcb_connection_t, client_major_version: u32, client_minor_version: u32) -> xcb_render_query_version_cookie_t>,
    pub(crate) xcb_render_query_version_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_render_query_version_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_render_query_version_reply_t>,
    pub(crate) xcb_render_query_version_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, client_major_version: u32, client_minor_version: u32) -> xcb_render_query_version_cookie_t>,
    pub(crate) xcb_render_reference_glyph_set: LazySymbol<unsafe fn(c: *mut xcb_connection_t, gsid: xcb_render_glyphset_t, existing: xcb_render_glyphset_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_reference_glyph_set_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, gsid: xcb_render_glyphset_t, existing: xcb_render_glyphset_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_set_picture_clip_rectangles: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, clip_x_origin: i16, clip_y_origin: i16, rectangles_len: u32, rectangles: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_set_picture_clip_rectangles_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, clip_x_origin: i16, clip_y_origin: i16, rectangles_len: u32, rectangles: *const xcb_rectangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_set_picture_filter: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, filter_len: u16, filter: *const c_char, values_len: u32, values: *const xcb_render_fixed_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_set_picture_filter_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, filter_len: u16, filter: *const c_char, values_len: u32, values: *const xcb_render_fixed_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_set_picture_transform: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, transform: xcb_render_transform_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_set_picture_transform_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, picture: xcb_render_picture_t, transform: xcb_render_transform_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_spanfix_end: LazySymbol<unsafe fn(i: *mut xcb_render_spanfix_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_spanfix_next: LazySymbol<unsafe fn(i: *mut xcb_render_spanfix_iterator_t)>,
    pub(crate) xcb_render_transform_end: LazySymbol<unsafe fn(i: *mut xcb_render_transform_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_transform_next: LazySymbol<unsafe fn(i: *mut xcb_render_transform_iterator_t)>,
    pub(crate) xcb_render_trap_end: LazySymbol<unsafe fn(i: *mut xcb_render_trap_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_trap_next: LazySymbol<unsafe fn(i: *mut xcb_render_trap_iterator_t)>,
    pub(crate) xcb_render_trapezoid_end: LazySymbol<unsafe fn(i: *mut xcb_render_trapezoid_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_trapezoid_next: LazySymbol<unsafe fn(i: *mut xcb_render_trapezoid_iterator_t)>,
    pub(crate) xcb_render_trapezoids: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, src_x: i16, src_y: i16, traps_len: u32, traps: *const xcb_render_trapezoid_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_trapezoids_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, src_x: i16, src_y: i16, traps_len: u32, traps: *const xcb_render_trapezoid_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_tri_fan: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, src_x: i16, src_y: i16, points_len: u32, points: *const xcb_render_pointfix_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_tri_fan_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, src_x: i16, src_y: i16, points_len: u32, points: *const xcb_render_pointfix_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_tri_strip: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, src_x: i16, src_y: i16, points_len: u32, points: *const xcb_render_pointfix_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_tri_strip_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, src_x: i16, src_y: i16, points_len: u32, points: *const xcb_render_pointfix_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_triangle_end: LazySymbol<unsafe fn(i: *mut xcb_render_triangle_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_render_triangle_next: LazySymbol<unsafe fn(i: *mut xcb_render_triangle_iterator_t)>,
    pub(crate) xcb_render_triangles: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, src_x: i16, src_y: i16, triangles_len: u32, triangles: *const xcb_render_triangle_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_render_triangles_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, op: u8, src: xcb_render_picture_t, dst: xcb_render_picture_t, mask_format: xcb_render_pictformat_t, src_x: i16, src_y: i16, triangles_len: u32, triangles: *const xcb_render_triangle_t) -> xcb_void_cookie_t>,
}
