use crate::ffi::*;
use crate::lazy::*;
use libloading::{Error, Library};
use std::os::raw::*;

#[rustfmt::skip]
pub struct XcbRandr {
    pub(crate) lib: NamedLibrary,
    pub(crate) xcb_randr_add_output_mode: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, mode: xcb_randr_mode_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_add_output_mode_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, mode: xcb_randr_mode_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_change_output_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, property: xcb_atom_t, type_: xcb_atom_t, format: u8, mode: u8, num_units: u32, data: *const c_void) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_change_output_property_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, property: xcb_atom_t, type_: xcb_atom_t, format: u8, mode: u8, num_units: u32, data: *const c_void) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_change_provider_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, property: xcb_atom_t, type_: xcb_atom_t, format: u8, mode: u8, num_items: u32, data: *const c_void) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_change_provider_property_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, property: xcb_atom_t, type_: xcb_atom_t, format: u8, mode: u8, num_items: u32, data: *const c_void) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_configure_output_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, property: xcb_atom_t, pending: u8, range: u8, values_len: u32, values: *const i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_configure_output_property_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, property: xcb_atom_t, pending: u8, range: u8, values_len: u32, values: *const i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_configure_provider_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, property: xcb_atom_t, pending: u8, range: u8, values_len: u32, values: *const i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_configure_provider_property_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, property: xcb_atom_t, pending: u8, range: u8, values_len: u32, values: *const i32) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_create_mode: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, mode_info: xcb_randr_mode_info_t, name_len: u32, name: *const c_char) -> xcb_randr_create_mode_cookie_t>,
    pub(crate) xcb_randr_create_mode_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_create_mode_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_create_mode_reply_t>,
    pub(crate) xcb_randr_create_mode_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, mode_info: xcb_randr_mode_info_t, name_len: u32, name: *const c_char) -> xcb_randr_create_mode_cookie_t>,
    pub(crate) xcb_randr_crtc_change_end: LazySymbol<unsafe fn(i: *mut xcb_randr_crtc_change_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_crtc_change_next: LazySymbol<unsafe fn(i: *mut xcb_randr_crtc_change_iterator_t)>,
    pub(crate) xcb_randr_crtc_end: LazySymbol<unsafe fn(i: *mut xcb_randr_crtc_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_crtc_next: LazySymbol<unsafe fn(i: *mut xcb_randr_crtc_iterator_t)>,
    pub(crate) xcb_randr_delete_output_mode: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, mode: xcb_randr_mode_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_delete_output_mode_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, mode: xcb_randr_mode_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_delete_output_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, property: xcb_atom_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_delete_output_property_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, property: xcb_atom_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_delete_provider_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, property: xcb_atom_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_delete_provider_property_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, property: xcb_atom_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_destroy_mode: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: xcb_randr_mode_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_destroy_mode_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mode: xcb_randr_mode_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_get_crtc_gamma: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t) -> xcb_randr_get_crtc_gamma_cookie_t>,
    pub(crate) xcb_randr_get_crtc_gamma_blue: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_gamma_reply_t) -> *mut u16>,
    pub(crate) xcb_randr_get_crtc_gamma_blue_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_gamma_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_crtc_gamma_blue_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_gamma_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_crtc_gamma_green: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_gamma_reply_t) -> *mut u16>,
    pub(crate) xcb_randr_get_crtc_gamma_green_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_gamma_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_crtc_gamma_green_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_gamma_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_crtc_gamma_red: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_gamma_reply_t) -> *mut u16>,
    pub(crate) xcb_randr_get_crtc_gamma_red_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_gamma_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_crtc_gamma_red_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_gamma_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_crtc_gamma_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_crtc_gamma_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_crtc_gamma_reply_t>,
    pub(crate) xcb_randr_get_crtc_gamma_size: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t) -> xcb_randr_get_crtc_gamma_size_cookie_t>,
    pub(crate) xcb_randr_get_crtc_gamma_size_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_crtc_gamma_size_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_crtc_gamma_size_reply_t>,
    pub(crate) xcb_randr_get_crtc_gamma_size_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t) -> xcb_randr_get_crtc_gamma_size_cookie_t>,
    pub(crate) xcb_randr_get_crtc_gamma_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t) -> xcb_randr_get_crtc_gamma_cookie_t>,
    pub(crate) xcb_randr_get_crtc_info: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t, config_timestamp: xcb_timestamp_t) -> xcb_randr_get_crtc_info_cookie_t>,
    pub(crate) xcb_randr_get_crtc_info_outputs: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_info_reply_t) -> *mut xcb_randr_output_t>,
    pub(crate) xcb_randr_get_crtc_info_outputs_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_crtc_info_outputs_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_info_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_crtc_info_possible: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_info_reply_t) -> *mut xcb_randr_output_t>,
    pub(crate) xcb_randr_get_crtc_info_possible_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_crtc_info_possible_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_info_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_crtc_info_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_crtc_info_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_crtc_info_reply_t>,
    pub(crate) xcb_randr_get_crtc_info_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t, config_timestamp: xcb_timestamp_t) -> xcb_randr_get_crtc_info_cookie_t>,
    pub(crate) xcb_randr_get_crtc_transform: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t) -> xcb_randr_get_crtc_transform_cookie_t>,
    pub(crate) xcb_randr_get_crtc_transform_current_filter_name: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_transform_reply_t) -> *mut c_char>,
    pub(crate) xcb_randr_get_crtc_transform_current_filter_name_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_transform_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_crtc_transform_current_filter_name_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_transform_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_crtc_transform_current_params: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_transform_reply_t) -> *mut xcb_render_fixed_t>,
    pub(crate) xcb_randr_get_crtc_transform_current_params_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_transform_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_crtc_transform_current_params_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_transform_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_crtc_transform_pending_filter_name: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_transform_reply_t) -> *mut c_char>,
    pub(crate) xcb_randr_get_crtc_transform_pending_filter_name_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_transform_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_crtc_transform_pending_filter_name_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_transform_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_crtc_transform_pending_params: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_transform_reply_t) -> *mut xcb_render_fixed_t>,
    pub(crate) xcb_randr_get_crtc_transform_pending_params_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_transform_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_crtc_transform_pending_params_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_crtc_transform_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_crtc_transform_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_crtc_transform_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_crtc_transform_reply_t>,
    pub(crate) xcb_randr_get_crtc_transform_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t) -> xcb_randr_get_crtc_transform_cookie_t>,
    pub(crate) xcb_randr_get_output_info: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, config_timestamp: xcb_timestamp_t) -> xcb_randr_get_output_info_cookie_t>,
    pub(crate) xcb_randr_get_output_info_clones: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_info_reply_t) -> *mut xcb_randr_output_t>,
    pub(crate) xcb_randr_get_output_info_clones_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_output_info_clones_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_info_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_output_info_crtcs: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_info_reply_t) -> *mut xcb_randr_crtc_t>,
    pub(crate) xcb_randr_get_output_info_crtcs_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_output_info_crtcs_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_info_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_output_info_modes: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_info_reply_t) -> *mut xcb_randr_mode_t>,
    pub(crate) xcb_randr_get_output_info_modes_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_output_info_modes_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_info_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_output_info_name: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_info_reply_t) -> *mut u8>,
    pub(crate) xcb_randr_get_output_info_name_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_output_info_name_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_info_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_output_info_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_output_info_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_output_info_reply_t>,
    pub(crate) xcb_randr_get_output_info_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, config_timestamp: xcb_timestamp_t) -> xcb_randr_get_output_info_cookie_t>,
    pub(crate) xcb_randr_get_output_primary: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_randr_get_output_primary_cookie_t>,
    pub(crate) xcb_randr_get_output_primary_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_output_primary_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_output_primary_reply_t>,
    pub(crate) xcb_randr_get_output_primary_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_randr_get_output_primary_cookie_t>,
    pub(crate) xcb_randr_get_output_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, property: xcb_atom_t, type_: xcb_atom_t, long_offset: u32, long_length: u32, delete: u8, pending: u8) -> xcb_randr_get_output_property_cookie_t>,
    pub(crate) xcb_randr_get_output_property_data: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_property_reply_t) -> *mut u8>,
    pub(crate) xcb_randr_get_output_property_data_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_property_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_output_property_data_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_output_property_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_output_property_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_output_property_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_output_property_reply_t>,
    pub(crate) xcb_randr_get_output_property_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, property: xcb_atom_t, type_: xcb_atom_t, long_offset: u32, long_length: u32, delete: u8, pending: u8) -> xcb_randr_get_output_property_cookie_t>,
    pub(crate) xcb_randr_get_panning: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t) -> xcb_randr_get_panning_cookie_t>,
    pub(crate) xcb_randr_get_panning_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_panning_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_panning_reply_t>,
    pub(crate) xcb_randr_get_panning_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t) -> xcb_randr_get_panning_cookie_t>,
    pub(crate) xcb_randr_get_provider_info: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, config_timestamp: xcb_timestamp_t) -> xcb_randr_get_provider_info_cookie_t>,
    pub(crate) xcb_randr_get_provider_info_associated_capability: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> *mut u32>,
    pub(crate) xcb_randr_get_provider_info_associated_capability_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_provider_info_associated_capability_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_provider_info_associated_providers: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> *mut xcb_randr_provider_t>,
    pub(crate) xcb_randr_get_provider_info_associated_providers_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_provider_info_associated_providers_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_provider_info_crtcs: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> *mut xcb_randr_crtc_t>,
    pub(crate) xcb_randr_get_provider_info_crtcs_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_provider_info_crtcs_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_provider_info_name: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> *mut c_char>,
    pub(crate) xcb_randr_get_provider_info_name_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_provider_info_name_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_provider_info_outputs: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> *mut xcb_randr_output_t>,
    pub(crate) xcb_randr_get_provider_info_outputs_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_provider_info_outputs_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_info_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_provider_info_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_provider_info_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_provider_info_reply_t>,
    pub(crate) xcb_randr_get_provider_info_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, config_timestamp: xcb_timestamp_t) -> xcb_randr_get_provider_info_cookie_t>,
    pub(crate) xcb_randr_get_provider_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, property: xcb_atom_t, type_: xcb_atom_t, long_offset: u32, long_length: u32, delete: u8, pending: u8) -> xcb_randr_get_provider_property_cookie_t>,
    pub(crate) xcb_randr_get_provider_property_data: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_property_reply_t) -> *mut c_void>,
    pub(crate) xcb_randr_get_provider_property_data_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_property_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_provider_property_data_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_provider_property_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_provider_property_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_provider_property_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_provider_property_reply_t>,
    pub(crate) xcb_randr_get_provider_property_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, property: xcb_atom_t, type_: xcb_atom_t, long_offset: u32, long_length: u32, delete: u8, pending: u8) -> xcb_randr_get_provider_property_cookie_t>,
    pub(crate) xcb_randr_get_providers: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_randr_get_providers_cookie_t>,
    pub(crate) xcb_randr_get_providers_providers: LazySymbol<unsafe fn(R: *const xcb_randr_get_providers_reply_t) -> *mut xcb_randr_provider_t>,
    pub(crate) xcb_randr_get_providers_providers_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_providers_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_providers_providers_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_providers_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_providers_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_providers_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_providers_reply_t>,
    pub(crate) xcb_randr_get_providers_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_randr_get_providers_cookie_t>,
    pub(crate) xcb_randr_get_screen_info: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_randr_get_screen_info_cookie_t>,
    pub(crate) xcb_randr_get_screen_info_rates_iterator: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_info_reply_t) -> xcb_randr_refresh_rates_iterator_t>,
    pub(crate) xcb_randr_get_screen_info_rates_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_info_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_screen_info_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_screen_info_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_screen_info_reply_t>,
    pub(crate) xcb_randr_get_screen_info_sizes: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_info_reply_t) -> *mut xcb_randr_screen_size_t>,
    pub(crate) xcb_randr_get_screen_info_sizes_iterator: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_info_reply_t) -> xcb_randr_screen_size_iterator_t>,
    pub(crate) xcb_randr_get_screen_info_sizes_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_info_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_screen_info_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_randr_get_screen_info_cookie_t>,
    pub(crate) xcb_randr_get_screen_resources: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_randr_get_screen_resources_cookie_t>,
    pub(crate) xcb_randr_get_screen_resources_crtcs: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_reply_t) -> *mut xcb_randr_crtc_t>,
    pub(crate) xcb_randr_get_screen_resources_crtcs_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_screen_resources_crtcs_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_screen_resources_current: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_randr_get_screen_resources_current_cookie_t>,
    pub(crate) xcb_randr_get_screen_resources_current_crtcs: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_current_reply_t) -> *mut xcb_randr_crtc_t>,
    pub(crate) xcb_randr_get_screen_resources_current_crtcs_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_current_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_screen_resources_current_crtcs_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_current_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_screen_resources_current_modes: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_current_reply_t) -> *mut xcb_randr_mode_info_t>,
    pub(crate) xcb_randr_get_screen_resources_current_modes_iterator: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_current_reply_t) -> xcb_randr_mode_info_iterator_t>,
    pub(crate) xcb_randr_get_screen_resources_current_modes_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_current_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_screen_resources_current_names: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_current_reply_t) -> *mut u8>,
    pub(crate) xcb_randr_get_screen_resources_current_names_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_current_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_screen_resources_current_names_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_current_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_screen_resources_current_outputs: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_current_reply_t) -> *mut xcb_randr_output_t>,
    pub(crate) xcb_randr_get_screen_resources_current_outputs_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_current_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_screen_resources_current_outputs_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_current_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_screen_resources_current_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_screen_resources_current_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_screen_resources_current_reply_t>,
    pub(crate) xcb_randr_get_screen_resources_current_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_randr_get_screen_resources_current_cookie_t>,
    pub(crate) xcb_randr_get_screen_resources_modes: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_reply_t) -> *mut xcb_randr_mode_info_t>,
    pub(crate) xcb_randr_get_screen_resources_modes_iterator: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_reply_t) -> xcb_randr_mode_info_iterator_t>,
    pub(crate) xcb_randr_get_screen_resources_modes_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_screen_resources_names: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_reply_t) -> *mut u8>,
    pub(crate) xcb_randr_get_screen_resources_names_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_screen_resources_names_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_screen_resources_outputs: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_reply_t) -> *mut xcb_randr_output_t>,
    pub(crate) xcb_randr_get_screen_resources_outputs_end: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_get_screen_resources_outputs_length: LazySymbol<unsafe fn(R: *const xcb_randr_get_screen_resources_reply_t) -> c_int>,
    pub(crate) xcb_randr_get_screen_resources_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_screen_resources_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_screen_resources_reply_t>,
    pub(crate) xcb_randr_get_screen_resources_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_randr_get_screen_resources_cookie_t>,
    pub(crate) xcb_randr_get_screen_size_range: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_randr_get_screen_size_range_cookie_t>,
    pub(crate) xcb_randr_get_screen_size_range_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_get_screen_size_range_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_get_screen_size_range_reply_t>,
    pub(crate) xcb_randr_get_screen_size_range_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_randr_get_screen_size_range_cookie_t>,
    pub(crate) xcb_randr_id: LazySymbol<*mut xcb_extension_t>,
    pub(crate) xcb_randr_list_output_properties: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t) -> xcb_randr_list_output_properties_cookie_t>,
    pub(crate) xcb_randr_list_output_properties_atoms: LazySymbol<unsafe fn(R: *const xcb_randr_list_output_properties_reply_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_randr_list_output_properties_atoms_end: LazySymbol<unsafe fn(R: *const xcb_randr_list_output_properties_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_list_output_properties_atoms_length: LazySymbol<unsafe fn(R: *const xcb_randr_list_output_properties_reply_t) -> c_int>,
    pub(crate) xcb_randr_list_output_properties_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_list_output_properties_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_list_output_properties_reply_t>,
    pub(crate) xcb_randr_list_output_properties_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t) -> xcb_randr_list_output_properties_cookie_t>,
    pub(crate) xcb_randr_list_provider_properties: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t) -> xcb_randr_list_provider_properties_cookie_t>,
    pub(crate) xcb_randr_list_provider_properties_atoms: LazySymbol<unsafe fn(R: *const xcb_randr_list_provider_properties_reply_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_randr_list_provider_properties_atoms_end: LazySymbol<unsafe fn(R: *const xcb_randr_list_provider_properties_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_list_provider_properties_atoms_length: LazySymbol<unsafe fn(R: *const xcb_randr_list_provider_properties_reply_t) -> c_int>,
    pub(crate) xcb_randr_list_provider_properties_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_list_provider_properties_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_list_provider_properties_reply_t>,
    pub(crate) xcb_randr_list_provider_properties_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t) -> xcb_randr_list_provider_properties_cookie_t>,
    pub(crate) xcb_randr_mode_end: LazySymbol<unsafe fn(i: *mut xcb_randr_mode_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_mode_info_end: LazySymbol<unsafe fn(i: *mut xcb_randr_mode_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_mode_info_next: LazySymbol<unsafe fn(i: *mut xcb_randr_mode_info_iterator_t)>,
    pub(crate) xcb_randr_mode_next: LazySymbol<unsafe fn(i: *mut xcb_randr_mode_iterator_t)>,
    pub(crate) xcb_randr_notify_data_end: LazySymbol<unsafe fn(i: *mut xcb_randr_notify_data_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_notify_data_next: LazySymbol<unsafe fn(i: *mut xcb_randr_notify_data_iterator_t)>,
    pub(crate) xcb_randr_output_change_end: LazySymbol<unsafe fn(i: *mut xcb_randr_output_change_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_output_change_next: LazySymbol<unsafe fn(i: *mut xcb_randr_output_change_iterator_t)>,
    pub(crate) xcb_randr_output_end: LazySymbol<unsafe fn(i: *mut xcb_randr_output_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_output_next: LazySymbol<unsafe fn(i: *mut xcb_randr_output_iterator_t)>,
    pub(crate) xcb_randr_output_property_end: LazySymbol<unsafe fn(i: *mut xcb_randr_output_property_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_output_property_next: LazySymbol<unsafe fn(i: *mut xcb_randr_output_property_iterator_t)>,
    pub(crate) xcb_randr_provider_change_end: LazySymbol<unsafe fn(i: *mut xcb_randr_provider_change_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_provider_change_next: LazySymbol<unsafe fn(i: *mut xcb_randr_provider_change_iterator_t)>,
    pub(crate) xcb_randr_provider_end: LazySymbol<unsafe fn(i: *mut xcb_randr_provider_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_provider_next: LazySymbol<unsafe fn(i: *mut xcb_randr_provider_iterator_t)>,
    pub(crate) xcb_randr_provider_property_end: LazySymbol<unsafe fn(i: *mut xcb_randr_provider_property_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_provider_property_next: LazySymbol<unsafe fn(i: *mut xcb_randr_provider_property_iterator_t)>,
    pub(crate) xcb_randr_query_output_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, property: xcb_atom_t) -> xcb_randr_query_output_property_cookie_t>,
    pub(crate) xcb_randr_query_output_property_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_query_output_property_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_query_output_property_reply_t>,
    pub(crate) xcb_randr_query_output_property_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, output: xcb_randr_output_t, property: xcb_atom_t) -> xcb_randr_query_output_property_cookie_t>,
    pub(crate) xcb_randr_query_output_property_valid_values: LazySymbol<unsafe fn(R: *const xcb_randr_query_output_property_reply_t) -> *mut i32>,
    pub(crate) xcb_randr_query_output_property_valid_values_end: LazySymbol<unsafe fn(R: *const xcb_randr_query_output_property_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_query_output_property_valid_values_length: LazySymbol<unsafe fn(R: *const xcb_randr_query_output_property_reply_t) -> c_int>,
    pub(crate) xcb_randr_query_provider_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, property: xcb_atom_t) -> xcb_randr_query_provider_property_cookie_t>,
    pub(crate) xcb_randr_query_provider_property_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_query_provider_property_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_query_provider_property_reply_t>,
    pub(crate) xcb_randr_query_provider_property_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, property: xcb_atom_t) -> xcb_randr_query_provider_property_cookie_t>,
    pub(crate) xcb_randr_query_provider_property_valid_values: LazySymbol<unsafe fn(R: *const xcb_randr_query_provider_property_reply_t) -> *mut i32>,
    pub(crate) xcb_randr_query_provider_property_valid_values_end: LazySymbol<unsafe fn(R: *const xcb_randr_query_provider_property_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_query_provider_property_valid_values_length: LazySymbol<unsafe fn(R: *const xcb_randr_query_provider_property_reply_t) -> c_int>,
    pub(crate) xcb_randr_query_version: LazySymbol<unsafe fn(c: *mut xcb_connection_t, major_version: u32, minor_version: u32) -> xcb_randr_query_version_cookie_t>,
    pub(crate) xcb_randr_query_version_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_query_version_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_query_version_reply_t>,
    pub(crate) xcb_randr_query_version_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, major_version: u32, minor_version: u32) -> xcb_randr_query_version_cookie_t>,
    pub(crate) xcb_randr_refresh_rates_end: LazySymbol<unsafe fn(i: *mut xcb_randr_refresh_rates_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_refresh_rates_next: LazySymbol<unsafe fn(i: *mut xcb_randr_refresh_rates_iterator_t)>,
    pub(crate) xcb_randr_refresh_rates_rates: LazySymbol<unsafe fn(R: *const xcb_randr_refresh_rates_t) -> *mut u16>,
    pub(crate) xcb_randr_refresh_rates_rates_end: LazySymbol<unsafe fn(R: *const xcb_randr_refresh_rates_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_refresh_rates_rates_length: LazySymbol<unsafe fn(R: *const xcb_randr_refresh_rates_t) -> c_int>,
    pub(crate) xcb_randr_resource_change_end: LazySymbol<unsafe fn(i: *mut xcb_randr_resource_change_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_resource_change_next: LazySymbol<unsafe fn(i: *mut xcb_randr_resource_change_iterator_t)>,
    pub(crate) xcb_randr_screen_size_end: LazySymbol<unsafe fn(i: *mut xcb_randr_screen_size_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_randr_screen_size_next: LazySymbol<unsafe fn(i: *mut xcb_randr_screen_size_iterator_t)>,
    pub(crate) xcb_randr_select_input: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, enable: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_select_input_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, enable: u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_set_crtc_config: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t, timestamp: xcb_timestamp_t, config_timestamp: xcb_timestamp_t, x: i16, y: i16, mode: xcb_randr_mode_t, rotation: u16, outputs_len: u32, outputs: *const xcb_randr_output_t) -> xcb_randr_set_crtc_config_cookie_t>,
    pub(crate) xcb_randr_set_crtc_config_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_set_crtc_config_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_set_crtc_config_reply_t>,
    pub(crate) xcb_randr_set_crtc_config_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t, timestamp: xcb_timestamp_t, config_timestamp: xcb_timestamp_t, x: i16, y: i16, mode: xcb_randr_mode_t, rotation: u16, outputs_len: u32, outputs: *const xcb_randr_output_t) -> xcb_randr_set_crtc_config_cookie_t>,
    pub(crate) xcb_randr_set_crtc_gamma: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t, size: u16, red: *const u16, green: *const u16, blue: *const u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_set_crtc_gamma_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t, size: u16, red: *const u16, green: *const u16, blue: *const u16) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_set_crtc_transform: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t, transform: xcb_render_transform_t, filter_len: u16, filter_name: *const c_char, filter_params_len: u32, filter_params: *const xcb_render_fixed_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_set_crtc_transform_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t, transform: xcb_render_transform_t, filter_len: u16, filter_name: *const c_char, filter_params_len: u32, filter_params: *const xcb_render_fixed_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_set_output_primary: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, output: xcb_randr_output_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_set_output_primary_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, output: xcb_randr_output_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_set_panning: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t, timestamp: xcb_timestamp_t, left: u16, top: u16, width: u16, height: u16, track_left: u16, track_top: u16, track_width: u16, track_height: u16, border_left: i16, border_top: i16, border_right: i16, border_bottom: i16) -> xcb_randr_set_panning_cookie_t>,
    pub(crate) xcb_randr_set_panning_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_set_panning_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_set_panning_reply_t>,
    pub(crate) xcb_randr_set_panning_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, crtc: xcb_randr_crtc_t, timestamp: xcb_timestamp_t, left: u16, top: u16, width: u16, height: u16, track_left: u16, track_top: u16, track_width: u16, track_height: u16, border_left: i16, border_top: i16, border_right: i16, border_bottom: i16) -> xcb_randr_set_panning_cookie_t>,
    pub(crate) xcb_randr_set_provider_offload_sink: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, sink_provider: xcb_randr_provider_t, config_timestamp: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_set_provider_offload_sink_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, sink_provider: xcb_randr_provider_t, config_timestamp: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_set_provider_output_source: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, source_provider: xcb_randr_provider_t, config_timestamp: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_set_provider_output_source_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, provider: xcb_randr_provider_t, source_provider: xcb_randr_provider_t, config_timestamp: xcb_timestamp_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_set_screen_config: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, timestamp: xcb_timestamp_t, config_timestamp: xcb_timestamp_t, size_id: u16, rotation: u16, rate: u16) -> xcb_randr_set_screen_config_cookie_t>,
    pub(crate) xcb_randr_set_screen_config_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_randr_set_screen_config_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_randr_set_screen_config_reply_t>,
    pub(crate) xcb_randr_set_screen_config_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, timestamp: xcb_timestamp_t, config_timestamp: xcb_timestamp_t, size_id: u16, rotation: u16, rate: u16) -> xcb_randr_set_screen_config_cookie_t>,
    pub(crate) xcb_randr_set_screen_size: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, width: u16, height: u16, mm_width: u32, mm_height: u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_randr_set_screen_size_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, width: u16, height: u16, mm_width: u32, mm_height: u32) -> xcb_void_cookie_t>,
}
