use crate::lazy::*;
use crate::*;
use libloading::{Error, Library};
use std::os::raw::*;

#[rustfmt::skip]
pub struct XcbXinput {
    pub(crate) lib: NamedLibrary,
    pub(crate) xcb_xinput_add_master_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_add_master_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_add_master_name: LazySymbol<unsafe fn(R: *const xcb_xinput_add_master_t) -> *mut c_char>,
    pub(crate) xcb_xinput_add_master_name_end: LazySymbol<unsafe fn(R: *const xcb_xinput_add_master_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_add_master_name_length: LazySymbol<unsafe fn(R: *const xcb_xinput_add_master_t) -> c_int>,
    pub(crate) xcb_xinput_add_master_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_add_master_iterator_t)>,
    pub(crate) xcb_xinput_allow_device_events: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t, mode: u8, device_id: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_allow_device_events_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t, mode: u8, device_id: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_attach_slave_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_attach_slave_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_attach_slave_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_attach_slave_iterator_t)>,
    pub(crate) xcb_xinput_axis_info_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_axis_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_axis_info_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_axis_info_iterator_t)>,
    pub(crate) xcb_xinput_barrier_release_pointer_info_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_barrier_release_pointer_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_barrier_release_pointer_info_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_barrier_release_pointer_info_iterator_t)>,
    pub(crate) xcb_xinput_bell_feedback_ctl_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_bell_feedback_ctl_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_bell_feedback_ctl_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_bell_feedback_ctl_iterator_t)>,
    pub(crate) xcb_xinput_bell_feedback_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_bell_feedback_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_bell_feedback_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_bell_feedback_state_iterator_t)>,
    pub(crate) xcb_xinput_button_class_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_button_class_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_button_class_labels: LazySymbol<unsafe fn(R: *const xcb_xinput_button_class_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xinput_button_class_labels_end: LazySymbol<unsafe fn(R: *const xcb_xinput_button_class_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_button_class_labels_length: LazySymbol<unsafe fn(R: *const xcb_xinput_button_class_t) -> c_int>,
    pub(crate) xcb_xinput_button_class_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_button_class_iterator_t)>,
    pub(crate) xcb_xinput_button_class_state: LazySymbol<unsafe fn(R: *const xcb_xinput_button_class_t) -> *mut u32>,
    pub(crate) xcb_xinput_button_class_state_end: LazySymbol<unsafe fn(R: *const xcb_xinput_button_class_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_button_class_state_length: LazySymbol<unsafe fn(R: *const xcb_xinput_button_class_t) -> c_int>,
    pub(crate) xcb_xinput_button_info_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_button_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_button_info_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_button_info_iterator_t)>,
    pub(crate) xcb_xinput_button_press_button_mask: LazySymbol<unsafe fn(R: *const xcb_xinput_button_press_event_t) -> *mut u32>,
    pub(crate) xcb_xinput_button_press_button_mask_end: LazySymbol<unsafe fn(R: *const xcb_xinput_button_press_event_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_button_press_button_mask_length: LazySymbol<unsafe fn(R: *const xcb_xinput_button_press_event_t) -> c_int>,
    pub(crate) xcb_xinput_button_press_valuator_mask: LazySymbol<unsafe fn(R: *const xcb_xinput_button_press_event_t) -> *mut u32>,
    pub(crate) xcb_xinput_button_press_valuator_mask_end: LazySymbol<unsafe fn(R: *const xcb_xinput_button_press_event_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_button_press_valuator_mask_length: LazySymbol<unsafe fn(R: *const xcb_xinput_button_press_event_t) -> c_int>,
    pub(crate) xcb_xinput_button_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_button_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_button_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_button_state_iterator_t)>,
    pub(crate) xcb_xinput_change_device_control: LazySymbol<unsafe fn(c: *mut xcb_connection_t, control_id: u16, device_id: u8, control: *mut xcb_xinput_device_ctl_t) -> xcb_xinput_change_device_control_cookie_t>,
    pub(crate) xcb_xinput_change_device_control_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_change_device_control_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_change_device_control_reply_t>,
    pub(crate) xcb_xinput_change_device_control_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, control_id: u16, device_id: u8, control: *mut xcb_xinput_device_ctl_t) -> xcb_xinput_change_device_control_cookie_t>,
    pub(crate) xcb_xinput_change_device_dont_propagate_list: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, num_classes: u16, mode: u8, classes: *const xcb_xinput_event_class_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_change_device_dont_propagate_list_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, num_classes: u16, mode: u8, classes: *const xcb_xinput_event_class_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_change_device_key_mapping: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, first_keycode: xcb_xinput_key_code_t, keysyms_per_keycode: u8, keycode_count: u8, keysyms: *const xcb_keysym_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_change_device_key_mapping_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, first_keycode: xcb_xinput_key_code_t, keysyms_per_keycode: u8, keycode_count: u8, keysyms: *const xcb_keysym_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_change_device_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, property: xcb_atom_t, type_: xcb_atom_t, device_id: u8, format: u8, mode: u8, num_items: u32, items: *const xcb_xinput_change_device_property_items_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_change_device_property_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, property: xcb_atom_t, type_: xcb_atom_t, device_id: u8, format: u8, mode: u8, num_items: u32, items: *const xcb_xinput_change_device_property_items_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_change_device_property_items_data_16: LazySymbol<unsafe fn(S: *const xcb_xinput_change_device_property_items_t) -> *mut u16>,
    pub(crate) xcb_xinput_change_device_property_items_data_16_end: LazySymbol<unsafe fn(R: *const xcb_xinput_change_device_property_request_t, S: *const xcb_xinput_change_device_property_items_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_change_device_property_items_data_16_length: LazySymbol<unsafe fn(R: *const xcb_xinput_change_device_property_request_t, S: *const xcb_xinput_change_device_property_items_t) -> c_int>,
    pub(crate) xcb_xinput_change_device_property_items_data_32: LazySymbol<unsafe fn(S: *const xcb_xinput_change_device_property_items_t) -> *mut u32>,
    pub(crate) xcb_xinput_change_device_property_items_data_32_end: LazySymbol<unsafe fn(R: *const xcb_xinput_change_device_property_request_t, S: *const xcb_xinput_change_device_property_items_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_change_device_property_items_data_32_length: LazySymbol<unsafe fn(R: *const xcb_xinput_change_device_property_request_t, S: *const xcb_xinput_change_device_property_items_t) -> c_int>,
    pub(crate) xcb_xinput_change_device_property_items_data_8: LazySymbol<unsafe fn(S: *const xcb_xinput_change_device_property_items_t) -> *mut u8>,
    pub(crate) xcb_xinput_change_device_property_items_data_8_end: LazySymbol<unsafe fn(R: *const xcb_xinput_change_device_property_request_t, S: *const xcb_xinput_change_device_property_items_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_change_device_property_items_data_8_length: LazySymbol<unsafe fn(R: *const xcb_xinput_change_device_property_request_t, S: *const xcb_xinput_change_device_property_items_t) -> c_int>,
    pub(crate) xcb_xinput_change_feedback_control: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mask: u32, device_id: u8, feedback_id: u8, feedback: *mut xcb_xinput_feedback_ctl_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_change_feedback_control_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, mask: u32, device_id: u8, feedback_id: u8, feedback: *mut xcb_xinput_feedback_ctl_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_change_keyboard_device: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_change_keyboard_device_cookie_t>,
    pub(crate) xcb_xinput_change_keyboard_device_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_change_keyboard_device_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_change_keyboard_device_reply_t>,
    pub(crate) xcb_xinput_change_keyboard_device_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_change_keyboard_device_cookie_t>,
    pub(crate) xcb_xinput_change_pointer_device: LazySymbol<unsafe fn(c: *mut xcb_connection_t, x_axis: u8, y_axis: u8, device_id: u8) -> xcb_xinput_change_pointer_device_cookie_t>,
    pub(crate) xcb_xinput_change_pointer_device_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_change_pointer_device_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_change_pointer_device_reply_t>,
    pub(crate) xcb_xinput_change_pointer_device_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, x_axis: u8, y_axis: u8, device_id: u8) -> xcb_xinput_change_pointer_device_cookie_t>,
    pub(crate) xcb_xinput_close_device: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_close_device_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_delete_device_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, property: xcb_atom_t, device_id: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_delete_device_property_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, property: xcb_atom_t, device_id: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_detach_slave_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_detach_slave_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_detach_slave_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_detach_slave_iterator_t)>,
    pub(crate) xcb_xinput_device_abs_area_ctrl_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_abs_area_ctrl_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_abs_area_ctrl_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_abs_area_ctrl_iterator_t)>,
    pub(crate) xcb_xinput_device_abs_area_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_abs_area_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_abs_area_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_abs_area_state_iterator_t)>,
    pub(crate) xcb_xinput_device_abs_calib_ctl_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_abs_calib_ctl_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_abs_calib_ctl_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_abs_calib_ctl_iterator_t)>,
    pub(crate) xcb_xinput_device_abs_calib_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_abs_calib_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_abs_calib_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_abs_calib_state_iterator_t)>,
    pub(crate) xcb_xinput_device_bell: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, feedback_id: u8, feedback_class: u8, percent: i8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_device_bell_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, feedback_id: u8, feedback_class: u8, percent: i8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_device_changed_classes_iterator: LazySymbol<unsafe fn(R: *const xcb_xinput_device_changed_event_t) -> xcb_xinput_device_class_iterator_t>,
    pub(crate) xcb_xinput_device_changed_classes_length: LazySymbol<unsafe fn(R: *const xcb_xinput_device_changed_event_t) -> c_int>,
    pub(crate) xcb_xinput_device_class_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_class_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_class_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_class_iterator_t)>,
    pub(crate) xcb_xinput_device_class_uninterpreted_data: LazySymbol<unsafe fn(R: *const xcb_xinput_device_class_t) -> *mut u8>,
    pub(crate) xcb_xinput_device_class_uninterpreted_data_end: LazySymbol<unsafe fn(R: *const xcb_xinput_device_class_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_class_uninterpreted_data_length: LazySymbol<unsafe fn(R: *const xcb_xinput_device_class_t) -> c_int>,
    pub(crate) xcb_xinput_device_core_ctrl_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_core_ctrl_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_core_ctrl_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_core_ctrl_iterator_t)>,
    pub(crate) xcb_xinput_device_core_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_core_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_core_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_core_state_iterator_t)>,
    pub(crate) xcb_xinput_device_ctl_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_ctl_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_ctl_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_ctl_iterator_t)>,
    pub(crate) xcb_xinput_device_ctl_uninterpreted_data: LazySymbol<unsafe fn(R: *const xcb_xinput_device_ctl_t) -> *mut u8>,
    pub(crate) xcb_xinput_device_ctl_uninterpreted_data_end: LazySymbol<unsafe fn(R: *const xcb_xinput_device_ctl_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_ctl_uninterpreted_data_length: LazySymbol<unsafe fn(R: *const xcb_xinput_device_ctl_t) -> c_int>,
    pub(crate) xcb_xinput_device_enable_ctrl_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_enable_ctrl_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_enable_ctrl_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_enable_ctrl_iterator_t)>,
    pub(crate) xcb_xinput_device_enable_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_enable_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_enable_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_enable_state_iterator_t)>,
    pub(crate) xcb_xinput_device_id_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_id_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_id_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_id_iterator_t)>,
    pub(crate) xcb_xinput_device_info_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_info_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_info_iterator_t)>,
    pub(crate) xcb_xinput_device_name_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_name_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_name_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_name_iterator_t)>,
    pub(crate) xcb_xinput_device_name_string: LazySymbol<unsafe fn(R: *const xcb_xinput_device_name_t) -> *mut c_char>,
    pub(crate) xcb_xinput_device_name_string_end: LazySymbol<unsafe fn(R: *const xcb_xinput_device_name_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_name_string_length: LazySymbol<unsafe fn(R: *const xcb_xinput_device_name_t) -> c_int>,
    pub(crate) xcb_xinput_device_resolution_ctl_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_resolution_ctl_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_resolution_ctl_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_resolution_ctl_iterator_t)>,
    pub(crate) xcb_xinput_device_resolution_ctl_resolution_values: LazySymbol<unsafe fn(R: *const xcb_xinput_device_resolution_ctl_t) -> *mut u32>,
    pub(crate) xcb_xinput_device_resolution_ctl_resolution_values_end: LazySymbol<unsafe fn(R: *const xcb_xinput_device_resolution_ctl_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_resolution_ctl_resolution_values_length: LazySymbol<unsafe fn(R: *const xcb_xinput_device_resolution_ctl_t) -> c_int>,
    pub(crate) xcb_xinput_device_resolution_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_resolution_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_resolution_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_resolution_state_iterator_t)>,
    pub(crate) xcb_xinput_device_resolution_state_resolution_max: LazySymbol<unsafe fn(R: *const xcb_xinput_device_resolution_state_t) -> *mut u32>,
    pub(crate) xcb_xinput_device_resolution_state_resolution_max_end: LazySymbol<unsafe fn(R: *const xcb_xinput_device_resolution_state_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_resolution_state_resolution_max_length: LazySymbol<unsafe fn(R: *const xcb_xinput_device_resolution_state_t) -> c_int>,
    pub(crate) xcb_xinput_device_resolution_state_resolution_min: LazySymbol<unsafe fn(R: *const xcb_xinput_device_resolution_state_t) -> *mut u32>,
    pub(crate) xcb_xinput_device_resolution_state_resolution_min_end: LazySymbol<unsafe fn(R: *const xcb_xinput_device_resolution_state_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_resolution_state_resolution_min_length: LazySymbol<unsafe fn(R: *const xcb_xinput_device_resolution_state_t) -> c_int>,
    pub(crate) xcb_xinput_device_resolution_state_resolution_values: LazySymbol<unsafe fn(R: *const xcb_xinput_device_resolution_state_t) -> *mut u32>,
    pub(crate) xcb_xinput_device_resolution_state_resolution_values_end: LazySymbol<unsafe fn(R: *const xcb_xinput_device_resolution_state_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_resolution_state_resolution_values_length: LazySymbol<unsafe fn(R: *const xcb_xinput_device_resolution_state_t) -> c_int>,
    pub(crate) xcb_xinput_device_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_state_iterator_t)>,
    pub(crate) xcb_xinput_device_state_uninterpreted_data: LazySymbol<unsafe fn(R: *const xcb_xinput_device_state_t) -> *mut u8>,
    pub(crate) xcb_xinput_device_state_uninterpreted_data_end: LazySymbol<unsafe fn(R: *const xcb_xinput_device_state_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_state_uninterpreted_data_length: LazySymbol<unsafe fn(R: *const xcb_xinput_device_state_t) -> c_int>,
    pub(crate) xcb_xinput_device_time_coord_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_time_coord_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_device_time_coord_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_device_time_coord_iterator_t)>,
    pub(crate) xcb_xinput_enter_buttons: LazySymbol<unsafe fn(R: *const xcb_xinput_enter_event_t) -> *mut u32>,
    pub(crate) xcb_xinput_enter_buttons_end: LazySymbol<unsafe fn(R: *const xcb_xinput_enter_event_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_enter_buttons_length: LazySymbol<unsafe fn(R: *const xcb_xinput_enter_event_t) -> c_int>,
    pub(crate) xcb_xinput_event_class_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_event_class_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_event_class_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_event_class_iterator_t)>,
    pub(crate) xcb_xinput_event_mask_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_event_mask_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_event_mask_mask: LazySymbol<unsafe fn(R: *const xcb_xinput_event_mask_t) -> *mut u32>,
    pub(crate) xcb_xinput_event_mask_mask_end: LazySymbol<unsafe fn(R: *const xcb_xinput_event_mask_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_event_mask_mask_length: LazySymbol<unsafe fn(R: *const xcb_xinput_event_mask_t) -> c_int>,
    pub(crate) xcb_xinput_event_mask_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_event_mask_iterator_t)>,
    pub(crate) xcb_xinput_feedback_ctl_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_feedback_ctl_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_feedback_ctl_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_feedback_ctl_iterator_t)>,
    pub(crate) xcb_xinput_feedback_ctl_uninterpreted_data: LazySymbol<unsafe fn(R: *const xcb_xinput_feedback_ctl_t) -> *mut u8>,
    pub(crate) xcb_xinput_feedback_ctl_uninterpreted_data_end: LazySymbol<unsafe fn(R: *const xcb_xinput_feedback_ctl_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_feedback_ctl_uninterpreted_data_length: LazySymbol<unsafe fn(R: *const xcb_xinput_feedback_ctl_t) -> c_int>,
    pub(crate) xcb_xinput_feedback_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_feedback_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_feedback_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_feedback_state_iterator_t)>,
    pub(crate) xcb_xinput_feedback_state_uninterpreted_data: LazySymbol<unsafe fn(R: *const xcb_xinput_feedback_state_t) -> *mut u8>,
    pub(crate) xcb_xinput_feedback_state_uninterpreted_data_end: LazySymbol<unsafe fn(R: *const xcb_xinput_feedback_state_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_feedback_state_uninterpreted_data_length: LazySymbol<unsafe fn(R: *const xcb_xinput_feedback_state_t) -> c_int>,
    pub(crate) xcb_xinput_fp1616_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_fp1616_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_fp1616_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_fp1616_iterator_t)>,
    pub(crate) xcb_xinput_fp3232_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_fp3232_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_fp3232_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_fp3232_iterator_t)>,
    pub(crate) xcb_xinput_get_device_button_mapping: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_get_device_button_mapping_cookie_t>,
    pub(crate) xcb_xinput_get_device_button_mapping_map: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_button_mapping_reply_t) -> *mut u8>,
    pub(crate) xcb_xinput_get_device_button_mapping_map_end: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_button_mapping_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_get_device_button_mapping_map_length: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_button_mapping_reply_t) -> c_int>,
    pub(crate) xcb_xinput_get_device_button_mapping_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_get_device_button_mapping_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_get_device_button_mapping_reply_t>,
    pub(crate) xcb_xinput_get_device_button_mapping_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_get_device_button_mapping_cookie_t>,
    pub(crate) xcb_xinput_get_device_control: LazySymbol<unsafe fn(c: *mut xcb_connection_t, control_id: u16, device_id: u8) -> xcb_xinput_get_device_control_cookie_t>,
    pub(crate) xcb_xinput_get_device_control_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_get_device_control_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_get_device_control_reply_t>,
    pub(crate) xcb_xinput_get_device_control_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, control_id: u16, device_id: u8) -> xcb_xinput_get_device_control_cookie_t>,
    pub(crate) xcb_xinput_get_device_dont_propagate_list: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_xinput_get_device_dont_propagate_list_cookie_t>,
    pub(crate) xcb_xinput_get_device_dont_propagate_list_classes: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_dont_propagate_list_reply_t) -> *mut xcb_xinput_event_class_t>,
    pub(crate) xcb_xinput_get_device_dont_propagate_list_classes_end: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_dont_propagate_list_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_get_device_dont_propagate_list_classes_length: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_dont_propagate_list_reply_t) -> c_int>,
    pub(crate) xcb_xinput_get_device_dont_propagate_list_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_get_device_dont_propagate_list_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_get_device_dont_propagate_list_reply_t>,
    pub(crate) xcb_xinput_get_device_dont_propagate_list_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_xinput_get_device_dont_propagate_list_cookie_t>,
    pub(crate) xcb_xinput_get_device_focus: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_get_device_focus_cookie_t>,
    pub(crate) xcb_xinput_get_device_focus_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_get_device_focus_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_get_device_focus_reply_t>,
    pub(crate) xcb_xinput_get_device_focus_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_get_device_focus_cookie_t>,
    pub(crate) xcb_xinput_get_device_key_mapping: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, first_keycode: xcb_xinput_key_code_t, count: u8) -> xcb_xinput_get_device_key_mapping_cookie_t>,
    pub(crate) xcb_xinput_get_device_key_mapping_keysyms: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_key_mapping_reply_t) -> *mut xcb_keysym_t>,
    pub(crate) xcb_xinput_get_device_key_mapping_keysyms_end: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_key_mapping_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_get_device_key_mapping_keysyms_length: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_key_mapping_reply_t) -> c_int>,
    pub(crate) xcb_xinput_get_device_key_mapping_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_get_device_key_mapping_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_get_device_key_mapping_reply_t>,
    pub(crate) xcb_xinput_get_device_key_mapping_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, first_keycode: xcb_xinput_key_code_t, count: u8) -> xcb_xinput_get_device_key_mapping_cookie_t>,
    pub(crate) xcb_xinput_get_device_modifier_mapping: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_get_device_modifier_mapping_cookie_t>,
    pub(crate) xcb_xinput_get_device_modifier_mapping_keymaps: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_modifier_mapping_reply_t) -> *mut u8>,
    pub(crate) xcb_xinput_get_device_modifier_mapping_keymaps_end: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_modifier_mapping_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_get_device_modifier_mapping_keymaps_length: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_modifier_mapping_reply_t) -> c_int>,
    pub(crate) xcb_xinput_get_device_modifier_mapping_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_get_device_modifier_mapping_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_get_device_modifier_mapping_reply_t>,
    pub(crate) xcb_xinput_get_device_modifier_mapping_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_get_device_modifier_mapping_cookie_t>,
    pub(crate) xcb_xinput_get_device_motion_events: LazySymbol<unsafe fn(c: *mut xcb_connection_t, start: xcb_timestamp_t, stop: xcb_timestamp_t, device_id: u8) -> xcb_xinput_get_device_motion_events_cookie_t>,
    pub(crate) xcb_xinput_get_device_motion_events_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_get_device_motion_events_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_get_device_motion_events_reply_t>,
    pub(crate) xcb_xinput_get_device_motion_events_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, start: xcb_timestamp_t, stop: xcb_timestamp_t, device_id: u8) -> xcb_xinput_get_device_motion_events_cookie_t>,
    pub(crate) xcb_xinput_get_device_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, property: xcb_atom_t, type_: xcb_atom_t, offset: u32, len: u32, device_id: u8, delete: u8) -> xcb_xinput_get_device_property_cookie_t>,
    pub(crate) xcb_xinput_get_device_property_items: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_property_reply_t) -> *mut c_void>,
    pub(crate) xcb_xinput_get_device_property_items_data_16: LazySymbol<unsafe fn(S: *const xcb_xinput_get_device_property_items_t) -> *mut u16>,
    pub(crate) xcb_xinput_get_device_property_items_data_16_end: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_property_reply_t, S: *const xcb_xinput_get_device_property_items_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_get_device_property_items_data_16_length: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_property_reply_t, S: *const xcb_xinput_get_device_property_items_t) -> c_int>,
    pub(crate) xcb_xinput_get_device_property_items_data_32: LazySymbol<unsafe fn(S: *const xcb_xinput_get_device_property_items_t) -> *mut u32>,
    pub(crate) xcb_xinput_get_device_property_items_data_32_end: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_property_reply_t, S: *const xcb_xinput_get_device_property_items_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_get_device_property_items_data_32_length: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_property_reply_t, S: *const xcb_xinput_get_device_property_items_t) -> c_int>,
    pub(crate) xcb_xinput_get_device_property_items_data_8: LazySymbol<unsafe fn(S: *const xcb_xinput_get_device_property_items_t) -> *mut u8>,
    pub(crate) xcb_xinput_get_device_property_items_data_8_end: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_property_reply_t, S: *const xcb_xinput_get_device_property_items_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_get_device_property_items_data_8_length: LazySymbol<unsafe fn(R: *const xcb_xinput_get_device_property_reply_t, S: *const xcb_xinput_get_device_property_items_t) -> c_int>,
    pub(crate) xcb_xinput_get_device_property_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_get_device_property_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_get_device_property_reply_t>,
    pub(crate) xcb_xinput_get_device_property_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, property: xcb_atom_t, type_: xcb_atom_t, offset: u32, len: u32, device_id: u8, delete: u8) -> xcb_xinput_get_device_property_cookie_t>,
    pub(crate) xcb_xinput_get_extension_version: LazySymbol<unsafe fn(c: *mut xcb_connection_t, name_len: u16, name: *const c_char) -> xcb_xinput_get_extension_version_cookie_t>,
    pub(crate) xcb_xinput_get_extension_version_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_get_extension_version_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_get_extension_version_reply_t>,
    pub(crate) xcb_xinput_get_extension_version_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, name_len: u16, name: *const c_char) -> xcb_xinput_get_extension_version_cookie_t>,
    pub(crate) xcb_xinput_get_feedback_control: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_get_feedback_control_cookie_t>,
    pub(crate) xcb_xinput_get_feedback_control_feedbacks_iterator: LazySymbol<unsafe fn(R: *const xcb_xinput_get_feedback_control_reply_t) -> xcb_xinput_feedback_state_iterator_t>,
    pub(crate) xcb_xinput_get_feedback_control_feedbacks_length: LazySymbol<unsafe fn(R: *const xcb_xinput_get_feedback_control_reply_t) -> c_int>,
    pub(crate) xcb_xinput_get_feedback_control_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_get_feedback_control_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_get_feedback_control_reply_t>,
    pub(crate) xcb_xinput_get_feedback_control_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_get_feedback_control_cookie_t>,
    pub(crate) xcb_xinput_get_selected_extension_events: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_xinput_get_selected_extension_events_cookie_t>,
    pub(crate) xcb_xinput_get_selected_extension_events_all_classes: LazySymbol<unsafe fn(R: *const xcb_xinput_get_selected_extension_events_reply_t) -> *mut xcb_xinput_event_class_t>,
    pub(crate) xcb_xinput_get_selected_extension_events_all_classes_end: LazySymbol<unsafe fn(R: *const xcb_xinput_get_selected_extension_events_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_get_selected_extension_events_all_classes_length: LazySymbol<unsafe fn(R: *const xcb_xinput_get_selected_extension_events_reply_t) -> c_int>,
    pub(crate) xcb_xinput_get_selected_extension_events_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_get_selected_extension_events_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_get_selected_extension_events_reply_t>,
    pub(crate) xcb_xinput_get_selected_extension_events_this_classes: LazySymbol<unsafe fn(R: *const xcb_xinput_get_selected_extension_events_reply_t) -> *mut xcb_xinput_event_class_t>,
    pub(crate) xcb_xinput_get_selected_extension_events_this_classes_end: LazySymbol<unsafe fn(R: *const xcb_xinput_get_selected_extension_events_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_get_selected_extension_events_this_classes_length: LazySymbol<unsafe fn(R: *const xcb_xinput_get_selected_extension_events_reply_t) -> c_int>,
    pub(crate) xcb_xinput_get_selected_extension_events_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_xinput_get_selected_extension_events_cookie_t>,
    pub(crate) xcb_xinput_grab_device: LazySymbol<unsafe fn(c: *mut xcb_connection_t, grab_window: xcb_window_t, time: xcb_timestamp_t, num_classes: u16, this_device_mode: u8, other_device_mode: u8, owner_events: u8, device_id: u8, classes: *const xcb_xinput_event_class_t) -> xcb_xinput_grab_device_cookie_t>,
    pub(crate) xcb_xinput_grab_device_button: LazySymbol<unsafe fn(c: *mut xcb_connection_t, grab_window: xcb_window_t, grabbed_device: u8, modifier_device: u8, num_classes: u16, modifiers: u16, this_device_mode: u8, other_device_mode: u8, button: u8, owner_events: u8, classes: *const xcb_xinput_event_class_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_grab_device_button_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, grab_window: xcb_window_t, grabbed_device: u8, modifier_device: u8, num_classes: u16, modifiers: u16, this_device_mode: u8, other_device_mode: u8, button: u8, owner_events: u8, classes: *const xcb_xinput_event_class_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_grab_device_key: LazySymbol<unsafe fn(c: *mut xcb_connection_t, grab_window: xcb_window_t, num_classes: u16, modifiers: u16, modifier_device: u8, grabbed_device: u8, key: u8, this_device_mode: u8, other_device_mode: u8, owner_events: u8, classes: *const xcb_xinput_event_class_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_grab_device_key_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, grab_window: xcb_window_t, num_classes: u16, modifiers: u16, modifier_device: u8, grabbed_device: u8, key: u8, this_device_mode: u8, other_device_mode: u8, owner_events: u8, classes: *const xcb_xinput_event_class_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_grab_device_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_grab_device_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_grab_device_reply_t>,
    pub(crate) xcb_xinput_grab_device_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, grab_window: xcb_window_t, time: xcb_timestamp_t, num_classes: u16, this_device_mode: u8, other_device_mode: u8, owner_events: u8, device_id: u8, classes: *const xcb_xinput_event_class_t) -> xcb_xinput_grab_device_cookie_t>,
    pub(crate) xcb_xinput_grab_modifier_info_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_grab_modifier_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_grab_modifier_info_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_grab_modifier_info_iterator_t)>,
    pub(crate) xcb_xinput_group_info_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_group_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_group_info_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_group_info_iterator_t)>,
    pub(crate) xcb_xinput_hierarchy_change_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_hierarchy_change_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_hierarchy_change_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_hierarchy_change_iterator_t)>,
    pub(crate) xcb_xinput_hierarchy_change_uninterpreted_data: LazySymbol<unsafe fn(R: *const xcb_xinput_hierarchy_change_t) -> *mut u8>,
    pub(crate) xcb_xinput_hierarchy_change_uninterpreted_data_end: LazySymbol<unsafe fn(R: *const xcb_xinput_hierarchy_change_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_hierarchy_change_uninterpreted_data_length: LazySymbol<unsafe fn(R: *const xcb_xinput_hierarchy_change_t) -> c_int>,
    pub(crate) xcb_xinput_hierarchy_info_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_hierarchy_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_hierarchy_info_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_hierarchy_info_iterator_t)>,
    pub(crate) xcb_xinput_hierarchy_infos: LazySymbol<unsafe fn(R: *const xcb_xinput_hierarchy_event_t) -> *mut xcb_xinput_hierarchy_info_t>,
    pub(crate) xcb_xinput_hierarchy_infos_iterator: LazySymbol<unsafe fn(R: *const xcb_xinput_hierarchy_event_t) -> xcb_xinput_hierarchy_info_iterator_t>,
    pub(crate) xcb_xinput_hierarchy_infos_length: LazySymbol<unsafe fn(R: *const xcb_xinput_hierarchy_event_t) -> c_int>,
    pub(crate) xcb_xinput_id: LazySymbol<*mut xcb_extension_t>,
    pub(crate) xcb_xinput_input_class_info_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_input_class_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_input_class_info_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_input_class_info_iterator_t)>,
    pub(crate) xcb_xinput_input_info_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_input_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_input_info_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_input_info_iterator_t)>,
    pub(crate) xcb_xinput_input_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_input_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_input_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_input_state_iterator_t)>,
    pub(crate) xcb_xinput_input_state_uninterpreted_data: LazySymbol<unsafe fn(R: *const xcb_xinput_input_state_t) -> *mut u8>,
    pub(crate) xcb_xinput_input_state_uninterpreted_data_end: LazySymbol<unsafe fn(R: *const xcb_xinput_input_state_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_input_state_uninterpreted_data_length: LazySymbol<unsafe fn(R: *const xcb_xinput_input_state_t) -> c_int>,
    pub(crate) xcb_xinput_integer_feedback_ctl_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_integer_feedback_ctl_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_integer_feedback_ctl_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_integer_feedback_ctl_iterator_t)>,
    pub(crate) xcb_xinput_integer_feedback_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_integer_feedback_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_integer_feedback_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_integer_feedback_state_iterator_t)>,
    pub(crate) xcb_xinput_kbd_feedback_ctl_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_kbd_feedback_ctl_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_kbd_feedback_ctl_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_kbd_feedback_ctl_iterator_t)>,
    pub(crate) xcb_xinput_kbd_feedback_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_kbd_feedback_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_kbd_feedback_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_kbd_feedback_state_iterator_t)>,
    pub(crate) xcb_xinput_key_class_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_key_class_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_key_class_keys: LazySymbol<unsafe fn(R: *const xcb_xinput_key_class_t) -> *mut u32>,
    pub(crate) xcb_xinput_key_class_keys_end: LazySymbol<unsafe fn(R: *const xcb_xinput_key_class_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_key_class_keys_length: LazySymbol<unsafe fn(R: *const xcb_xinput_key_class_t) -> c_int>,
    pub(crate) xcb_xinput_key_class_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_key_class_iterator_t)>,
    pub(crate) xcb_xinput_key_code_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_key_code_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_key_code_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_key_code_iterator_t)>,
    pub(crate) xcb_xinput_key_info_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_key_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_key_info_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_key_info_iterator_t)>,
    pub(crate) xcb_xinput_key_press_button_mask: LazySymbol<unsafe fn(R: *const xcb_xinput_key_press_event_t) -> *mut u32>,
    pub(crate) xcb_xinput_key_press_button_mask_end: LazySymbol<unsafe fn(R: *const xcb_xinput_key_press_event_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_key_press_button_mask_length: LazySymbol<unsafe fn(R: *const xcb_xinput_key_press_event_t) -> c_int>,
    pub(crate) xcb_xinput_key_press_valuator_mask: LazySymbol<unsafe fn(R: *const xcb_xinput_key_press_event_t) -> *mut u32>,
    pub(crate) xcb_xinput_key_press_valuator_mask_end: LazySymbol<unsafe fn(R: *const xcb_xinput_key_press_event_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_key_press_valuator_mask_length: LazySymbol<unsafe fn(R: *const xcb_xinput_key_press_event_t) -> c_int>,
    pub(crate) xcb_xinput_key_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_key_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_key_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_key_state_iterator_t)>,
    pub(crate) xcb_xinput_led_feedback_ctl_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_led_feedback_ctl_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_led_feedback_ctl_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_led_feedback_ctl_iterator_t)>,
    pub(crate) xcb_xinput_led_feedback_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_led_feedback_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_led_feedback_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_led_feedback_state_iterator_t)>,
    pub(crate) xcb_xinput_list_device_properties: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_list_device_properties_cookie_t>,
    pub(crate) xcb_xinput_list_device_properties_atoms: LazySymbol<unsafe fn(R: *const xcb_xinput_list_device_properties_reply_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xinput_list_device_properties_atoms_end: LazySymbol<unsafe fn(R: *const xcb_xinput_list_device_properties_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_list_device_properties_atoms_length: LazySymbol<unsafe fn(R: *const xcb_xinput_list_device_properties_reply_t) -> c_int>,
    pub(crate) xcb_xinput_list_device_properties_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_list_device_properties_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_list_device_properties_reply_t>,
    pub(crate) xcb_xinput_list_device_properties_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_list_device_properties_cookie_t>,
    pub(crate) xcb_xinput_list_input_devices: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_xinput_list_input_devices_cookie_t>,
    pub(crate) xcb_xinput_list_input_devices_devices: LazySymbol<unsafe fn(R: *const xcb_xinput_list_input_devices_reply_t) -> *mut xcb_xinput_device_info_t>,
    pub(crate) xcb_xinput_list_input_devices_devices_iterator: LazySymbol<unsafe fn(R: *const xcb_xinput_list_input_devices_reply_t) -> xcb_xinput_device_info_iterator_t>,
    pub(crate) xcb_xinput_list_input_devices_devices_length: LazySymbol<unsafe fn(R: *const xcb_xinput_list_input_devices_reply_t) -> c_int>,
    pub(crate) xcb_xinput_list_input_devices_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_list_input_devices_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_list_input_devices_reply_t>,
    pub(crate) xcb_xinput_list_input_devices_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t) -> xcb_xinput_list_input_devices_cookie_t>,
    pub(crate) xcb_xinput_modifier_info_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_modifier_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_modifier_info_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_modifier_info_iterator_t)>,
    pub(crate) xcb_xinput_open_device: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_open_device_cookie_t>,
    pub(crate) xcb_xinput_open_device_class_info: LazySymbol<unsafe fn(R: *const xcb_xinput_open_device_reply_t) -> *mut xcb_xinput_input_class_info_t>,
    pub(crate) xcb_xinput_open_device_class_info_iterator: LazySymbol<unsafe fn(R: *const xcb_xinput_open_device_reply_t) -> xcb_xinput_input_class_info_iterator_t>,
    pub(crate) xcb_xinput_open_device_class_info_length: LazySymbol<unsafe fn(R: *const xcb_xinput_open_device_reply_t) -> c_int>,
    pub(crate) xcb_xinput_open_device_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_open_device_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_open_device_reply_t>,
    pub(crate) xcb_xinput_open_device_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_open_device_cookie_t>,
    pub(crate) xcb_xinput_ptr_feedback_ctl_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_ptr_feedback_ctl_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_ptr_feedback_ctl_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_ptr_feedback_ctl_iterator_t)>,
    pub(crate) xcb_xinput_ptr_feedback_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_ptr_feedback_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_ptr_feedback_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_ptr_feedback_state_iterator_t)>,
    pub(crate) xcb_xinput_query_device_state: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_query_device_state_cookie_t>,
    pub(crate) xcb_xinput_query_device_state_classes_iterator: LazySymbol<unsafe fn(R: *const xcb_xinput_query_device_state_reply_t) -> xcb_xinput_input_state_iterator_t>,
    pub(crate) xcb_xinput_query_device_state_classes_length: LazySymbol<unsafe fn(R: *const xcb_xinput_query_device_state_reply_t) -> c_int>,
    pub(crate) xcb_xinput_query_device_state_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_query_device_state_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_query_device_state_reply_t>,
    pub(crate) xcb_xinput_query_device_state_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8) -> xcb_xinput_query_device_state_cookie_t>,
    pub(crate) xcb_xinput_raw_button_press_valuator_mask: LazySymbol<unsafe fn(R: *const xcb_xinput_raw_button_press_event_t) -> *mut u32>,
    pub(crate) xcb_xinput_raw_button_press_valuator_mask_end: LazySymbol<unsafe fn(R: *const xcb_xinput_raw_button_press_event_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_raw_button_press_valuator_mask_length: LazySymbol<unsafe fn(R: *const xcb_xinput_raw_button_press_event_t) -> c_int>,
    pub(crate) xcb_xinput_raw_key_press_valuator_mask: LazySymbol<unsafe fn(R: *const xcb_xinput_raw_key_press_event_t) -> *mut u32>,
    pub(crate) xcb_xinput_raw_key_press_valuator_mask_end: LazySymbol<unsafe fn(R: *const xcb_xinput_raw_key_press_event_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_raw_key_press_valuator_mask_length: LazySymbol<unsafe fn(R: *const xcb_xinput_raw_key_press_event_t) -> c_int>,
    pub(crate) xcb_xinput_raw_touch_begin_valuator_mask: LazySymbol<unsafe fn(R: *const xcb_xinput_raw_touch_begin_event_t) -> *mut u32>,
    pub(crate) xcb_xinput_raw_touch_begin_valuator_mask_end: LazySymbol<unsafe fn(R: *const xcb_xinput_raw_touch_begin_event_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_raw_touch_begin_valuator_mask_length: LazySymbol<unsafe fn(R: *const xcb_xinput_raw_touch_begin_event_t) -> c_int>,
    pub(crate) xcb_xinput_remove_master_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_remove_master_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_remove_master_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_remove_master_iterator_t)>,
    pub(crate) xcb_xinput_scroll_class_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_scroll_class_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_scroll_class_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_scroll_class_iterator_t)>,
    pub(crate) xcb_xinput_select_extension_event: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, num_classes: u16, classes: *const xcb_xinput_event_class_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_select_extension_event_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, num_classes: u16, classes: *const xcb_xinput_event_class_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_send_extension_event: LazySymbol<unsafe fn(c: *mut xcb_connection_t, destination: xcb_window_t, device_id: u8, propagate: u8, num_classes: u16, num_events: u8, events: *const u8, classes: *const xcb_xinput_event_class_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_send_extension_event_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, destination: xcb_window_t, device_id: u8, propagate: u8, num_classes: u16, num_events: u8, events: *const u8, classes: *const xcb_xinput_event_class_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_set_device_button_mapping: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, map_size: u8, map: *const u8) -> xcb_xinput_set_device_button_mapping_cookie_t>,
    pub(crate) xcb_xinput_set_device_button_mapping_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_set_device_button_mapping_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_set_device_button_mapping_reply_t>,
    pub(crate) xcb_xinput_set_device_button_mapping_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, map_size: u8, map: *const u8) -> xcb_xinput_set_device_button_mapping_cookie_t>,
    pub(crate) xcb_xinput_set_device_focus: LazySymbol<unsafe fn(c: *mut xcb_connection_t, focus: xcb_window_t, time: xcb_timestamp_t, revert_to: u8, device_id: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_set_device_focus_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, focus: xcb_window_t, time: xcb_timestamp_t, revert_to: u8, device_id: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_set_device_mode: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, mode: u8) -> xcb_xinput_set_device_mode_cookie_t>,
    pub(crate) xcb_xinput_set_device_mode_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_set_device_mode_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_set_device_mode_reply_t>,
    pub(crate) xcb_xinput_set_device_mode_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, mode: u8) -> xcb_xinput_set_device_mode_cookie_t>,
    pub(crate) xcb_xinput_set_device_modifier_mapping: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, keycodes_per_modifier: u8, keymaps: *const u8) -> xcb_xinput_set_device_modifier_mapping_cookie_t>,
    pub(crate) xcb_xinput_set_device_modifier_mapping_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_set_device_modifier_mapping_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_set_device_modifier_mapping_reply_t>,
    pub(crate) xcb_xinput_set_device_modifier_mapping_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, keycodes_per_modifier: u8, keymaps: *const u8) -> xcb_xinput_set_device_modifier_mapping_cookie_t>,
    pub(crate) xcb_xinput_set_device_valuators: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, first_valuator: u8, num_valuators: u8, valuators: *const i32) -> xcb_xinput_set_device_valuators_cookie_t>,
    pub(crate) xcb_xinput_set_device_valuators_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_set_device_valuators_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_set_device_valuators_reply_t>,
    pub(crate) xcb_xinput_set_device_valuators_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, device_id: u8, first_valuator: u8, num_valuators: u8, valuators: *const i32) -> xcb_xinput_set_device_valuators_cookie_t>,
    pub(crate) xcb_xinput_string_feedback_ctl_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_string_feedback_ctl_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_string_feedback_ctl_keysyms: LazySymbol<unsafe fn(R: *const xcb_xinput_string_feedback_ctl_t) -> *mut xcb_keysym_t>,
    pub(crate) xcb_xinput_string_feedback_ctl_keysyms_end: LazySymbol<unsafe fn(R: *const xcb_xinput_string_feedback_ctl_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_string_feedback_ctl_keysyms_length: LazySymbol<unsafe fn(R: *const xcb_xinput_string_feedback_ctl_t) -> c_int>,
    pub(crate) xcb_xinput_string_feedback_ctl_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_string_feedback_ctl_iterator_t)>,
    pub(crate) xcb_xinput_string_feedback_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_string_feedback_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_string_feedback_state_keysyms: LazySymbol<unsafe fn(R: *const xcb_xinput_string_feedback_state_t) -> *mut xcb_keysym_t>,
    pub(crate) xcb_xinput_string_feedback_state_keysyms_end: LazySymbol<unsafe fn(R: *const xcb_xinput_string_feedback_state_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_string_feedback_state_keysyms_length: LazySymbol<unsafe fn(R: *const xcb_xinput_string_feedback_state_t) -> c_int>,
    pub(crate) xcb_xinput_string_feedback_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_string_feedback_state_iterator_t)>,
    pub(crate) xcb_xinput_touch_begin_button_mask: LazySymbol<unsafe fn(R: *const xcb_xinput_touch_begin_event_t) -> *mut u32>,
    pub(crate) xcb_xinput_touch_begin_button_mask_end: LazySymbol<unsafe fn(R: *const xcb_xinput_touch_begin_event_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_touch_begin_button_mask_length: LazySymbol<unsafe fn(R: *const xcb_xinput_touch_begin_event_t) -> c_int>,
    pub(crate) xcb_xinput_touch_begin_valuator_mask: LazySymbol<unsafe fn(R: *const xcb_xinput_touch_begin_event_t) -> *mut u32>,
    pub(crate) xcb_xinput_touch_begin_valuator_mask_end: LazySymbol<unsafe fn(R: *const xcb_xinput_touch_begin_event_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_touch_begin_valuator_mask_length: LazySymbol<unsafe fn(R: *const xcb_xinput_touch_begin_event_t) -> c_int>,
    pub(crate) xcb_xinput_touch_class_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_touch_class_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_touch_class_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_touch_class_iterator_t)>,
    pub(crate) xcb_xinput_ungrab_device: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t, device_id: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_ungrab_device_button: LazySymbol<unsafe fn(c: *mut xcb_connection_t, grab_window: xcb_window_t, modifiers: u16, modifier_device: u8, button: u8, grabbed_device: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_ungrab_device_button_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, grab_window: xcb_window_t, modifiers: u16, modifier_device: u8, button: u8, grabbed_device: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_ungrab_device_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t, device_id: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_ungrab_device_key: LazySymbol<unsafe fn(c: *mut xcb_connection_t, grab_window: xcb_window_t, modifiers: u16, modifier_device: u8, key: u8, grabbed_device: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_ungrab_device_key_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, grab_window: xcb_window_t, modifiers: u16, modifier_device: u8, key: u8, grabbed_device: u8) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_valuator_class_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_valuator_class_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_valuator_class_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_valuator_class_iterator_t)>,
    pub(crate) xcb_xinput_valuator_info_axes: LazySymbol<unsafe fn(R: *const xcb_xinput_valuator_info_t) -> *mut xcb_xinput_axis_info_t>,
    pub(crate) xcb_xinput_valuator_info_axes_iterator: LazySymbol<unsafe fn(R: *const xcb_xinput_valuator_info_t) -> xcb_xinput_axis_info_iterator_t>,
    pub(crate) xcb_xinput_valuator_info_axes_length: LazySymbol<unsafe fn(R: *const xcb_xinput_valuator_info_t) -> c_int>,
    pub(crate) xcb_xinput_valuator_info_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_valuator_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_valuator_info_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_valuator_info_iterator_t)>,
    pub(crate) xcb_xinput_valuator_state_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_valuator_state_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_valuator_state_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_valuator_state_iterator_t)>,
    pub(crate) xcb_xinput_valuator_state_valuators: LazySymbol<unsafe fn(R: *const xcb_xinput_valuator_state_t) -> *mut u32>,
    pub(crate) xcb_xinput_valuator_state_valuators_end: LazySymbol<unsafe fn(R: *const xcb_xinput_valuator_state_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_valuator_state_valuators_length: LazySymbol<unsafe fn(R: *const xcb_xinput_valuator_state_t) -> c_int>,
    pub(crate) xcb_xinput_xi_allow_events: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t, deviceid: xcb_xinput_device_id_t, event_mode: u8, touchid: u32, grab_window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_allow_events_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t, deviceid: xcb_xinput_device_id_t, event_mode: u8, touchid: u32, grab_window: xcb_window_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_barrier_release_pointer: LazySymbol<unsafe fn(c: *mut xcb_connection_t, num_barriers: u32, barriers: *const xcb_xinput_barrier_release_pointer_info_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_barrier_release_pointer_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, num_barriers: u32, barriers: *const xcb_xinput_barrier_release_pointer_info_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_change_cursor: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, cursor: xcb_cursor_t, deviceid: xcb_xinput_device_id_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_change_cursor_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, cursor: xcb_cursor_t, deviceid: xcb_xinput_device_id_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_change_hierarchy: LazySymbol<unsafe fn(c: *mut xcb_connection_t, num_changes: u8, changes: *const xcb_xinput_hierarchy_change_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_change_hierarchy_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, num_changes: u8, changes: *const xcb_xinput_hierarchy_change_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_change_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, deviceid: xcb_xinput_device_id_t, mode: u8, format: u8, property: xcb_atom_t, type_: xcb_atom_t, num_items: u32, items: *const xcb_xinput_xi_change_property_items_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_change_property_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, deviceid: xcb_xinput_device_id_t, mode: u8, format: u8, property: xcb_atom_t, type_: xcb_atom_t, num_items: u32, items: *const xcb_xinput_xi_change_property_items_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_change_property_items_data_16: LazySymbol<unsafe fn(S: *const xcb_xinput_xi_change_property_items_t) -> *mut u16>,
    pub(crate) xcb_xinput_xi_change_property_items_data_16_end: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_change_property_request_t, S: *const xcb_xinput_xi_change_property_items_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_xi_change_property_items_data_16_length: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_change_property_request_t, S: *const xcb_xinput_xi_change_property_items_t) -> c_int>,
    pub(crate) xcb_xinput_xi_change_property_items_data_32: LazySymbol<unsafe fn(S: *const xcb_xinput_xi_change_property_items_t) -> *mut u32>,
    pub(crate) xcb_xinput_xi_change_property_items_data_32_end: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_change_property_request_t, S: *const xcb_xinput_xi_change_property_items_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_xi_change_property_items_data_32_length: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_change_property_request_t, S: *const xcb_xinput_xi_change_property_items_t) -> c_int>,
    pub(crate) xcb_xinput_xi_change_property_items_data_8: LazySymbol<unsafe fn(S: *const xcb_xinput_xi_change_property_items_t) -> *mut u8>,
    pub(crate) xcb_xinput_xi_change_property_items_data_8_end: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_change_property_request_t, S: *const xcb_xinput_xi_change_property_items_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_xi_change_property_items_data_8_length: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_change_property_request_t, S: *const xcb_xinput_xi_change_property_items_t) -> c_int>,
    pub(crate) xcb_xinput_xi_delete_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, deviceid: xcb_xinput_device_id_t, property: xcb_atom_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_delete_property_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, deviceid: xcb_xinput_device_id_t, property: xcb_atom_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_device_info_classes_iterator: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_device_info_t) -> xcb_xinput_device_class_iterator_t>,
    pub(crate) xcb_xinput_xi_device_info_classes_length: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_device_info_t) -> c_int>,
    pub(crate) xcb_xinput_xi_device_info_end: LazySymbol<unsafe fn(i: *mut xcb_xinput_xi_device_info_iterator_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_xi_device_info_name: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_device_info_t) -> *mut c_char>,
    pub(crate) xcb_xinput_xi_device_info_name_end: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_device_info_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_xi_device_info_name_length: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_device_info_t) -> c_int>,
    pub(crate) xcb_xinput_xi_device_info_next: LazySymbol<unsafe fn(i: *mut xcb_xinput_xi_device_info_iterator_t)>,
    pub(crate) xcb_xinput_xi_get_client_pointer: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_xinput_xi_get_client_pointer_cookie_t>,
    pub(crate) xcb_xinput_xi_get_client_pointer_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_xi_get_client_pointer_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_xi_get_client_pointer_reply_t>,
    pub(crate) xcb_xinput_xi_get_client_pointer_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_xinput_xi_get_client_pointer_cookie_t>,
    pub(crate) xcb_xinput_xi_get_focus: LazySymbol<unsafe fn(c: *mut xcb_connection_t, deviceid: xcb_xinput_device_id_t) -> xcb_xinput_xi_get_focus_cookie_t>,
    pub(crate) xcb_xinput_xi_get_focus_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_xi_get_focus_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_xi_get_focus_reply_t>,
    pub(crate) xcb_xinput_xi_get_focus_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, deviceid: xcb_xinput_device_id_t) -> xcb_xinput_xi_get_focus_cookie_t>,
    pub(crate) xcb_xinput_xi_get_property: LazySymbol<unsafe fn(c: *mut xcb_connection_t, deviceid: xcb_xinput_device_id_t, delete: u8, property: xcb_atom_t, type_: xcb_atom_t, offset: u32, len: u32) -> xcb_xinput_xi_get_property_cookie_t>,
    pub(crate) xcb_xinput_xi_get_property_items: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_get_property_reply_t) -> *mut c_void>,
    pub(crate) xcb_xinput_xi_get_property_items_data_16: LazySymbol<unsafe fn(S: *const xcb_xinput_xi_get_property_items_t) -> *mut u16>,
    pub(crate) xcb_xinput_xi_get_property_items_data_16_end: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_get_property_reply_t, S: *const xcb_xinput_xi_get_property_items_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_xi_get_property_items_data_16_length: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_get_property_reply_t, S: *const xcb_xinput_xi_get_property_items_t) -> c_int>,
    pub(crate) xcb_xinput_xi_get_property_items_data_32: LazySymbol<unsafe fn(S: *const xcb_xinput_xi_get_property_items_t) -> *mut u32>,
    pub(crate) xcb_xinput_xi_get_property_items_data_32_end: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_get_property_reply_t, S: *const xcb_xinput_xi_get_property_items_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_xi_get_property_items_data_32_length: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_get_property_reply_t, S: *const xcb_xinput_xi_get_property_items_t) -> c_int>,
    pub(crate) xcb_xinput_xi_get_property_items_data_8: LazySymbol<unsafe fn(S: *const xcb_xinput_xi_get_property_items_t) -> *mut u8>,
    pub(crate) xcb_xinput_xi_get_property_items_data_8_end: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_get_property_reply_t, S: *const xcb_xinput_xi_get_property_items_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_xi_get_property_items_data_8_length: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_get_property_reply_t, S: *const xcb_xinput_xi_get_property_items_t) -> c_int>,
    pub(crate) xcb_xinput_xi_get_property_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_xi_get_property_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_xi_get_property_reply_t>,
    pub(crate) xcb_xinput_xi_get_property_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, deviceid: xcb_xinput_device_id_t, delete: u8, property: xcb_atom_t, type_: xcb_atom_t, offset: u32, len: u32) -> xcb_xinput_xi_get_property_cookie_t>,
    pub(crate) xcb_xinput_xi_get_selected_events: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_xinput_xi_get_selected_events_cookie_t>,
    pub(crate) xcb_xinput_xi_get_selected_events_masks_iterator: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_get_selected_events_reply_t) -> xcb_xinput_event_mask_iterator_t>,
    pub(crate) xcb_xinput_xi_get_selected_events_masks_length: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_get_selected_events_reply_t) -> c_int>,
    pub(crate) xcb_xinput_xi_get_selected_events_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_xi_get_selected_events_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_xi_get_selected_events_reply_t>,
    pub(crate) xcb_xinput_xi_get_selected_events_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t) -> xcb_xinput_xi_get_selected_events_cookie_t>,
    pub(crate) xcb_xinput_xi_grab_device: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, time: xcb_timestamp_t, cursor: xcb_cursor_t, deviceid: xcb_xinput_device_id_t, mode: u8, paired_device_mode: u8, owner_events: u8, mask_len: u16, mask: *const u32) -> xcb_xinput_xi_grab_device_cookie_t>,
    pub(crate) xcb_xinput_xi_grab_device_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_xi_grab_device_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_xi_grab_device_reply_t>,
    pub(crate) xcb_xinput_xi_grab_device_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, time: xcb_timestamp_t, cursor: xcb_cursor_t, deviceid: xcb_xinput_device_id_t, mode: u8, paired_device_mode: u8, owner_events: u8, mask_len: u16, mask: *const u32) -> xcb_xinput_xi_grab_device_cookie_t>,
    pub(crate) xcb_xinput_xi_list_properties: LazySymbol<unsafe fn(c: *mut xcb_connection_t, deviceid: xcb_xinput_device_id_t) -> xcb_xinput_xi_list_properties_cookie_t>,
    pub(crate) xcb_xinput_xi_list_properties_properties: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_list_properties_reply_t) -> *mut xcb_atom_t>,
    pub(crate) xcb_xinput_xi_list_properties_properties_end: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_list_properties_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_xi_list_properties_properties_length: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_list_properties_reply_t) -> c_int>,
    pub(crate) xcb_xinput_xi_list_properties_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_xi_list_properties_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_xi_list_properties_reply_t>,
    pub(crate) xcb_xinput_xi_list_properties_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, deviceid: xcb_xinput_device_id_t) -> xcb_xinput_xi_list_properties_cookie_t>,
    pub(crate) xcb_xinput_xi_passive_grab_device: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t, grab_window: xcb_window_t, cursor: xcb_cursor_t, detail: u32, deviceid: xcb_xinput_device_id_t, num_modifiers: u16, mask_len: u16, grab_type: u8, grab_mode: u8, paired_device_mode: u8, owner_events: u8, mask: *const u32, modifiers: *const u32) -> xcb_xinput_xi_passive_grab_device_cookie_t>,
    pub(crate) xcb_xinput_xi_passive_grab_device_modifiers: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_passive_grab_device_reply_t) -> *mut xcb_xinput_grab_modifier_info_t>,
    pub(crate) xcb_xinput_xi_passive_grab_device_modifiers_iterator: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_passive_grab_device_reply_t) -> xcb_xinput_grab_modifier_info_iterator_t>,
    pub(crate) xcb_xinput_xi_passive_grab_device_modifiers_length: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_passive_grab_device_reply_t) -> c_int>,
    pub(crate) xcb_xinput_xi_passive_grab_device_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_xi_passive_grab_device_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_xi_passive_grab_device_reply_t>,
    pub(crate) xcb_xinput_xi_passive_grab_device_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t, grab_window: xcb_window_t, cursor: xcb_cursor_t, detail: u32, deviceid: xcb_xinput_device_id_t, num_modifiers: u16, mask_len: u16, grab_type: u8, grab_mode: u8, paired_device_mode: u8, owner_events: u8, mask: *const u32, modifiers: *const u32) -> xcb_xinput_xi_passive_grab_device_cookie_t>,
    pub(crate) xcb_xinput_xi_passive_ungrab_device: LazySymbol<unsafe fn(c: *mut xcb_connection_t, grab_window: xcb_window_t, detail: u32, deviceid: xcb_xinput_device_id_t, num_modifiers: u16, grab_type: u8, modifiers: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_passive_ungrab_device_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, grab_window: xcb_window_t, detail: u32, deviceid: xcb_xinput_device_id_t, num_modifiers: u16, grab_type: u8, modifiers: *const u32) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_query_device: LazySymbol<unsafe fn(c: *mut xcb_connection_t, deviceid: xcb_xinput_device_id_t) -> xcb_xinput_xi_query_device_cookie_t>,
    pub(crate) xcb_xinput_xi_query_device_infos_iterator: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_query_device_reply_t) -> xcb_xinput_xi_device_info_iterator_t>,
    pub(crate) xcb_xinput_xi_query_device_infos_length: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_query_device_reply_t) -> c_int>,
    pub(crate) xcb_xinput_xi_query_device_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_xi_query_device_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_xi_query_device_reply_t>,
    pub(crate) xcb_xinput_xi_query_device_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, deviceid: xcb_xinput_device_id_t) -> xcb_xinput_xi_query_device_cookie_t>,
    pub(crate) xcb_xinput_xi_query_pointer: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, deviceid: xcb_xinput_device_id_t) -> xcb_xinput_xi_query_pointer_cookie_t>,
    pub(crate) xcb_xinput_xi_query_pointer_buttons: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_query_pointer_reply_t) -> *mut u32>,
    pub(crate) xcb_xinput_xi_query_pointer_buttons_end: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_query_pointer_reply_t) -> xcb_generic_iterator_t>,
    pub(crate) xcb_xinput_xi_query_pointer_buttons_length: LazySymbol<unsafe fn(R: *const xcb_xinput_xi_query_pointer_reply_t) -> c_int>,
    pub(crate) xcb_xinput_xi_query_pointer_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_xi_query_pointer_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_xi_query_pointer_reply_t>,
    pub(crate) xcb_xinput_xi_query_pointer_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, deviceid: xcb_xinput_device_id_t) -> xcb_xinput_xi_query_pointer_cookie_t>,
    pub(crate) xcb_xinput_xi_query_version: LazySymbol<unsafe fn(c: *mut xcb_connection_t, major_version: u16, minor_version: u16) -> xcb_xinput_xi_query_version_cookie_t>,
    pub(crate) xcb_xinput_xi_query_version_reply: LazySymbol<unsafe fn(c: *mut xcb_connection_t, cookie: xcb_xinput_xi_query_version_cookie_t, error: *mut *mut xcb_generic_error_t) -> *mut xcb_xinput_xi_query_version_reply_t>,
    pub(crate) xcb_xinput_xi_query_version_unchecked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, major_version: u16, minor_version: u16) -> xcb_xinput_xi_query_version_cookie_t>,
    pub(crate) xcb_xinput_xi_select_events: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, num_mask: u16, masks: *const xcb_xinput_event_mask_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_select_events_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, num_mask: u16, masks: *const xcb_xinput_event_mask_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_set_client_pointer: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, deviceid: xcb_xinput_device_id_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_set_client_pointer_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, deviceid: xcb_xinput_device_id_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_set_focus: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, time: xcb_timestamp_t, deviceid: xcb_xinput_device_id_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_set_focus_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, window: xcb_window_t, time: xcb_timestamp_t, deviceid: xcb_xinput_device_id_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_ungrab_device: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t, deviceid: xcb_xinput_device_id_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_ungrab_device_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, time: xcb_timestamp_t, deviceid: xcb_xinput_device_id_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_warp_pointer: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src_win: xcb_window_t, dst_win: xcb_window_t, src_x: xcb_xinput_fp1616_t, src_y: xcb_xinput_fp1616_t, src_width: u16, src_height: u16, dst_x: xcb_xinput_fp1616_t, dst_y: xcb_xinput_fp1616_t, deviceid: xcb_xinput_device_id_t) -> xcb_void_cookie_t>,
    pub(crate) xcb_xinput_xi_warp_pointer_checked: LazySymbol<unsafe fn(c: *mut xcb_connection_t, src_win: xcb_window_t, dst_win: xcb_window_t, src_x: xcb_xinput_fp1616_t, src_y: xcb_xinput_fp1616_t, src_width: u16, src_height: u16, dst_x: xcb_xinput_fp1616_t, dst_y: xcb_xinput_fp1616_t, deviceid: xcb_xinput_device_id_t) -> xcb_void_cookie_t>,
}
